"""Furina's shipped Fanfare meter, and the true-HP-loss hook.

Deliberately low in the import graph (state + constants only) so both
effects.py and powers.py can use these hooks without a cycle.

The shipped kit's Encore buffer, Charge (Kokomi) and Burst meters left the sim
on 2026-10-08 with the rest of the shipped-kit machinery; nothing current
reached them. The Fanfare meter below is the shipped one too, and the Salon's
Tab never feeds it (`stage_retires_the_shipped_meters`); the Tab keeps its own
Fanfare in `furina_tide`.

Fanfare: a READ-ONLY momentum stat since "The Tide Turns" (2026-07-24).
Generation is activity-based ONLY; it DECAYS each turn from turn 2; and it
rests on a floor built from what her cards PRINT. Cards read it and gate on
it.

Its one remaining source is true HP lost (`note_player_hp_loss`); the
Encore and Spotlight legs left with those mechanics.

There is deliberately no per-turn passive ACCRUAL path in this module or
anywhere else -- passive accrual is stall payoff, and the healing policy
exists to kill exactly that. A floor is not accrual: it is static value that
does not grow with time, so stalling still earns nothing.

The gate is Player.fanfare_cap (0 = the character has no Fanfare resource).
The cap itself is a high safety rail rather than a design dial -- under decay
the ceiling does not bind.
"""

from __future__ import annotations

from tier0 import constants as C
from tier0.engine import furina_stage
from tier0.engine.state import CombatState


def note_fanfare_change(state: CombatState, before: int) -> None:
    """A7 (Unheard Confession, 2026-07-28): pay Block whenever the meter MOVES.

    Every fanfare mutation in the sim funnels through this module -- gain,
    decay, floor-raise -- so calling this at each of those three sites is the
    whole trigger surface, and a fourth mutation added later without a call
    here is the only way to break it.

    Fires on a change in EITHER direction. The ruling's wording is "whenever
    Fanfare changes amount", and the decay half is what makes the power more
    than a second gain-rider: her meter fades 20% every turn from turn 2, so
    the card pays on the way down as well as the way up.

    A gain that lands entirely at the cap is NOT a change (applied == 0), so
    a saturated meter stops paying -- deliberate, and the same saturation the
    pass-4 telemetry made visible.

    Unscaled printed number, following salon_bow_block: this is a power's
    activity payout, not a card's printed Block, so Spotlight does not read it.
    """
    n = state.player.powers.get("fanfare_delta_block", 0)
    if not n or state.player.fanfare == before:
        return
    state.player.block += n
    state.emit("block", amount=n)
    state.emit("fanfare_delta_block", amount=n)


def stage_retires_the_shipped_meters(player) -> bool:
    """`EB-745`. Does THE STAGE retire the shipped Encore and Fanfare meters
    for this player?

    THE FIND (round two, sec.4). "Fanfare 30 (buff), generated by losing HP,
    nothing spends it" sat in every seat's status list beside the bar of the
    same name, and one seat spent a card and an energy to learn which Fanfare
    <i>Ousia Surge</i> reads. Round one's `EB-736` hid the shipped METER LINE
    from the page; the machinery underneath it kept running, so the buff row
    came back through the status list and through the wire's resources.

    THE BRIEF RETIRES THEM OUTRIGHT (sec.2's table, R269): "Encore, the
    Spotlight in both modes, the Fanfare counter and its riders" have no job
    under the Stage, and sec.3 rule 11 says her own bars are touched by
    nothing in the kit. So the arm does not merely hide them -- it never
    grants them, and a run under the flag carries neither.

    ONE GATE AT THE MINT rather than one at each funnel. The Stage retires
    the meters, so the honest place to say so is the two grant doors every leg
    reaches. C# twin:
    `FurinaResources.StageRetiresTheShippedMeters`.
    """
    return furina_stage.is_furina(player)


def gain_fanfare(state: CombatState, n: int, source: str) -> None:
    p = state.player
    if not p.fanfare_cap or n <= 0:
        return
    if stage_retires_the_shipped_meters(p):
        return                    # `EB-745`
    before = p.fanfare
    p.fanfare = min(p.fanfare_cap, p.fanfare + n)
    applied = p.fanfare - before
    note_fanfare_change(state, before)
    # Pass 4 Q1a: the clamp used to be SILENT -- only `amount` (what landed)
    # was emitted, so generation thrown away at the cap left no trace and no
    # sweep could see saturation. `requested`/`wasted` are the overflow read;
    # a fully-wasted gain emits too, which is exactly the case that matters.
    state.emit("gain_fanfare", amount=applied, source=source,
               total=p.fanfare, requested=n, wasted=n - applied)


def _decay_amount(p) -> int:
    """How much the meter fades this turn: PROPORTIONAL, always.

    R67 (2026-07-26) deleted the flat shape outright. There used to be a
    second branch here returning FANFARE_DECAY_PER_TURN whenever the
    fraction was 0, described as "one shape at a time so a sweep can switch
    shapes" -- but the 20% ruling made the fraction permanently nonzero, so
    the flat branch was unreachable and the sweep that switched shapes
    reported five identical rows. The ruled world is 20% proportional, full
    stop, and it is now the only world this function can express.

    The proportional form takes its cut of the WHOLE meter and lets the
    floor clamp protect the baseline, rather than taking a cut of the amount
    above the floor. That keeps the player-facing rule to one line ("Fanfare
    fades by N% each turn") which is the entire argument the flat shape won
    on; a rule that reads "N% of the amount above your baseline" gives back
    the legibility the flat form was chosen for.

    At least 1 always comes off while above the floor, so a small meter
    cannot stall at a value that rounds down to nothing.
    """
    if p.fanfare <= p.fanfare_floor:
        return 0
    return max(1, round(p.fanfare * C.FANFARE_DECAY_FRACTION))


def decay_fanfare(state: CombatState) -> None:
    """F-A1: the meter fades each turn, never below the floor.

    Applied at the START of the player turn and only from turn 2, so the
    opening hand plays against what the player actually built rather than
    against an immediate tax. PROPORTIONAL (20% of current, min 1) by
    [USER] ruling 2026-07-24 -- see FANFARE_DECAY_FRACTION, which REVERSED
    the plan's flat-over-proportional direction. The flat alternative it
    reversed no longer exists in the tree at all: R67 deleted the knob and
    its unreachable branch (audit 2026-07-26 §2.1).

    This is the load-bearing half of the read-only rework: without it the
    pool sits pinned at its ceiling and every card that "scales with
    Fanfare" is a constant wearing a meter.
    """
    p = state.player
    if not p.fanfare_cap or state.turn < 2:
        return
    before = p.fanfare
    p.fanfare = max(p.fanfare_floor, p.fanfare - _decay_amount(p))
    # Emitted even when nothing fell: "the meter was already resting on its
    # floor" is a distinct and interesting state from "the meter decayed",
    # and a silent no-op would make the two indistinguishable downstream --
    # the exact mistake the pass-4 clamp made.
    state.emit("fanfare_decay", amount=before - p.fanfare, total=p.fanfare,
               floor=p.fanfare_floor, at_floor=p.fanfare <= p.fanfare_floor)
    note_fanfare_change(state, before)


def gain_fanfare_floor(state: CombatState, n: int, source: str) -> None:
    """F-A3: a permanent constellation grant.

    Raises floor, cap AND current together. Raising the cap alongside the
    floor is load-bearing rather than bookkeeping: a floor that pushed
    current up toward an unmoved ceiling would simply re-pin the meter, and
    keeping the two apart is what preserved the gradient in W2.

    LEGAL under the no-passive-accrual law (kickoff §4): a floor is STATIC
    value, not accrual -- it does not grow with time, so stalling still
    earns nothing. The law is intact, not amended. Stated here because a
    floor superficially resembles the per-turn accrual §4 bans forever, and
    the distinction is the whole reason this package is allowed to exist.
    """
    p = state.player
    if not p.fanfare_cap or n <= 0:
        return                    # inert for everyone without the resource
    if stage_retires_the_shipped_meters(p):
        return                    # `EB-745`
    before = p.fanfare
    p.fanfare_floor += n
    p.fanfare_cap += n
    p.fanfare = min(p.fanfare_cap, p.fanfare + n)
    note_fanfare_change(state, before)
    state.emit("fanfare_floor_granted", amount=n, source=source,
               floor=p.fanfare_floor, cap=p.fanfare_cap, total=p.fanfare)


def raise_fanfare_cap(state: CombatState, n: int, source: str) -> None:
    """The **Fanfare Cap +X** keyword: headroom only (Track B, 2026-07-28).

    The deliberate contrast with gain_fanfare_floor above, which moves all
    three numbers. Nothing is granted here; the meter is only allowed to go
    further if activity takes it there.

    See effects._op_raise_fanfare_cap for the standing measurement note --
    the cap has not been a binding number since F-A5, so this keyword is the
    cheap half of the pair by construction rather than by tuning.
    """
    p = state.player
    if not p.fanfare_cap or n <= 0:
        return                    # inert for everyone without the resource
    if stage_retires_the_shipped_meters(p):
        return                    # `EB-745`
    p.fanfare_cap += n
    state.emit("fanfare_cap_raised", amount=n, source=source,
               cap=p.fanfare_cap, total=p.fanfare)


def drop_fanfare_to_floor(state: CombatState, floor_drop: int,
                          source: str) -> int:
    """The Hyperbeam settle (Track C.2, 2026-07-28): crash the meter, then
    dig the floor out from under it. Returns what the meter fell by.

    THE FLOOR MAY GO NEGATIVE, and that is RULED rather than tolerated. A
    negative floor is a hole the player climbs out of with activity: decay
    still clamps to it exactly as before, so a meter at -12 sits at -12 and
    every point of generation counts against the debt.

    READERS CLAMP. Every consumer of the meter -- the Salon Focus term, the
    bonus_formula riders, the fanfare_at_least predicates -- reads
    `max(0, fanfare)`, so a negative meter turns effects OFF rather than
    inverting them. That is a PROPOSED semantic, flagged at review: the
    harsher StS-style inversion (members ticking for negative numbers) is a
    one-line flip in `readable`, and negative member ticks chipping the stage
    would read as a bug rather than as a cost.

    The cap is deliberately NOT lowered. The floor falling is the price; the
    ceiling falling too would make the card quietly worse the second time it
    is played in a combat, which is a different card.
    """
    p = state.player
    if not p.fanfare_cap:
        return 0
    before = p.fanfare
    p.fanfare_floor -= floor_drop
    p.fanfare = max(p.fanfare_floor, min(p.fanfare, p.fanfare_floor))
    note_fanfare_change(state, before)
    state.emit("fanfare_crashed", amount=before - p.fanfare, source=source,
               floor=p.fanfare_floor, total=p.fanfare)
    return before - p.fanfare


def readable(player) -> int:
    """What a Fanfare READER sees: the meter, clamped at zero.

    The single chokepoint for the Track C.2 negative-floor semantics. Every
    reader goes through here so "effects shut off, they do not invert" is one
    fact in one place.

    RATIFIED at the R130 sitting (2026-08-07). The clamp shipped flagged for
    review with the harsher StS-style inversion named as a one-line flip
    here; the sitting took the clamp as written, so this is ruled semantics
    and no longer a placeholder. The argument that held: negative member
    ticks chipping her own stage would read as a bug, not as a cost.

    Deliberately takes a PLAYER rather than a CombatState: several readers
    (the pilot's valuation terms, the C# mirror's tests) hold a player and no
    state, and a signature that forced them to fabricate one would have
    guaranteed the clamp got skipped somewhere.
    """
    return max(0, player.fanfare)


def note_fanfare_read(state: CombatState, kind: str,
                      card: str | None = None) -> None:
    """Instrument for the gate that asks whether the stat is LIVE.

    Sampled where a card actually READS the meter, which is not the same
    place as the turn-start snapshot: the pool refills mid-turn and spills,
    so a turn-start sample can look healthy while every read still lands on
    a pinned meter. Pass 4 measured both and they disagreed by 25 points.

    Records BOTH pins. At-cap alone cannot see the floor-stacking failure
    mode, because a grant raises the cap alongside the floor -- so a meter
    pinned on its floor never reads at-cap, and a gate written only against
    at-cap would stay silent through exactly the risk it was written for.
    """
    p = state.player
    if not p.fanfare_cap:
        return
    state.emit("fanfare_read", kind=kind, card=card, total=p.fanfare,
               cap=p.fanfare_cap, floor=p.fanfare_floor,
               at_cap=p.fanfare >= p.fanfare_cap,
               at_floor=p.fanfare <= p.fanfare_floor)


def note_player_hp_loss(state: CombatState, n: int) -> None:
    """Fanfare hook for TRUE HP loss (enemy hits reaching HP, DoT,
    self-damage, Encore overdraw). Callers deduct HP themselves; this
    only records the flux."""
    if n <= 0:
        return
    state.hp_lost_this_turn += n
    state.hp_lost_since_last_turn += n
    state.player_damage_events += 1
    gain_fanfare(state, n * C.FANFARE_PER_HP_LOST, "hp_lost")
    # THE FURINA RESEARCH SLICE (`furina_tide`, sim only): HP lost prints
    # Fanfare 1:1 on that arm. A no-op for anyone else.
    from tier0.engine import furina_tide           # late: avoids the cycle
    furina_tide.on_hp_loss(state, n)
