// <auto-generated>
//     GENERATED by tools/gen_teyvat_events.py from
//     docs/current/dossiers/content/event-faces/overgrowth-mondstadt-2026-09-14.md
//     Do not edit by hand: `python tools/gen_teyvat_events.py --check`
//     fails on any drift, and the next run overwrites it.
// </auto-generated>

using KleeMod.Teyvat.Events.Mirrors;

namespace KleeMod.Teyvat.Events.Mondstadt;

/// <summary>
/// The Hunters' Totem Posts Near Wolvendom -- WoodCarvings, dressed for Mondstadt.
///
/// The Hunters' Totem Posts Near Wolvendom — Mondstadt / Adventurers' Guild hunters — DRAFTED
///
/// NOTHING MECHANICAL IS HERE AND THERE IS NOWHERE FOR IT TO BE. The
/// base event's clauses are in <see cref="WoodCarvingsMirror"/>, written
/// once and shared by every nation that dresses this event; this class
/// is a NAME. `ModelDb.GetEntry` slugifies it into
/// `HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM`, `EventModel.Title` and `InitialDescription`
/// derive from that, and `EventModel.OptionKey` slugifies
/// `GetType().Name` -- so every loc key the mirror asks for is already
/// this dressing's. The rows are in `TeyvatLoc.GeneratedEventRows`.
/// </summary>
public sealed class HuntersTotemPostsNearWolvendom : WoodCarvingsMirror
{
}
