// <auto-generated>
//     GENERATED by tools/gen_teyvat_events.py from
//     docs/current/dossiers/content/event-faces/overgrowth-mondstadt-2026-09-14.md
//     Do not edit by hand: `python tools/gen_teyvat_events.py --check`
//     fails on any drift, and the next run overwrites it.
// </auto-generated>

using KleeMod.Teyvat.Events.Mirrors;

namespace KleeMod.Teyvat.Events.Mondstadt;

/// <summary>
/// The Springvale Cheese Cellar -- RoomFullOfCheese, dressed for Mondstadt.
///
/// The Springvale Cheese Cellar — Mondstadt / Adventurers' Guild — literal — REUSED event-conversion-gallery.md § Room Full of Cheese, variant 1 (TOP) (line 751)
///
/// NOTHING MECHANICAL IS HERE AND THERE IS NOWHERE FOR IT TO BE. The
/// base event's clauses are in <see cref="RoomFullOfCheeseMirror"/>, written
/// once and shared by every nation that dresses this event; this class
/// is a NAME. `ModelDb.GetEntry` slugifies it into
/// `SPRINGVALE_CHEESE_CELLAR`, `EventModel.Title` and `InitialDescription`
/// derive from that, and `EventModel.OptionKey` slugifies
/// `GetType().Name` -- so every loc key the mirror asks for is already
/// this dressing's. The rows are in `TeyvatLoc.GeneratedEventRows`.
/// </summary>
public sealed class SpringvaleCheeseCellar : RoomFullOfCheeseMirror
{
}
