"""EB-17: the played-when-drawn / dead-in-hand / force-first-copy counters.

The requirement, verbatim from `archive/klee-survival-sprint-plan.md` §4
(retrieved at `762e94d^:docs/archive/klee-survival-sprint-plan.md`):

    Do not use raw pick rate as the redesign trigger. The current static
    drafter values only printed damage and Block, so draw, debuffs,
    generation, Bombs, and many engines are invisible.

    First add or run paired evidence for:

    - offered / picked / played-when-drawn;
    - conditional activation and dead-in-hand rate;
    - damage, Block, energy, and cards generated by source card;
    - force-first-copy paired winrate.

Re-owed as next-step 3 of the sprint report ("add played-when-drawn /
forced-copy telemetry for the two sim-blind companion interfaces") and filed
as `missed-requirements` §2.2, where it is a LIVE GATE: the report's own
sentence is that "the remaining bodyless draw/resource engines still require
played-when-drawn or deck-context scoring evidence before either the bot or
the cards are buffed."

Same fence as tracks D and H, and for the same reason: everything here is
log-side, every number REPORTS and none of them GRADES, and the fight must be
bit-identical with the counters in place. The engine gains one added key on
`draw`, two on `play`, and one new emit-only `dead_in_hand` row. Nothing else
moves.
"""

from __future__ import annotations

import random

from tier0 import constants as C
from tier0.engine import combat
from tier0.engine.state import Card, CombatState, Enemy, Player
from tier0.harness import metrics
from tier0.harness.runner import run_battery

from .conftest import make_enemy, make_state


def _card(cid, cost=0, damage=None, **kw):
    fx = [{"op": "damage", "amount": damage, "target": "enemy"}] \
        if damage is not None else []
    return Card(id=cid, name=cid.title(), cost=cost,
                type="attack" if damage is not None else "skill",
                effects=fx, **kw)


def _fight(deck, enemy_hp=200, plays=((),), seed=1):
    """Run one player turn per entry in `plays`, on a hand-built deck.

    `plays[t]` is the list of card ids the pilot plays on turn t+1, in order;
    anything not named is left in hand, which is what makes a dead-in-hand
    case constructible. The enemy blocks for 0 so no HP moves and nothing here
    can end the fight early by accident.

    The draw pile is used IN ORDER: this drives `_player_turn` directly rather
    than `run_fight`, so there is no opening shuffle and "the sixth card is
    never drawn" is a fact rather than a seed.
    """
    player = Player(hp=200, max_hp=200, draw_pile=list(deck))
    enemy = Enemy(hp=enemy_hp, max_hp=enemy_hp, name="wall",
                  intents=[{"kind": "block", "amount": 0}])
    state = CombatState(player=player, enemies=[enemy],
                        rng=random.Random(seed))
    wanted: list[str] = []

    def pilot(s):
        for cid in list(wanted):
            for c in s.player.hand:
                if c.id == cid and combat.card_playable(s, c):
                    wanted.remove(cid)
                    return c
        return None

    for turn_plays in plays:
        wanted[:] = list(turn_plays)
        combat._player_turn(state, pilot)
    return state


def _stats(state):
    return metrics.extract(state, state.player.max_hp)


# --- 0: the instrument does not move the fight ---------------------------

def test_the_counters_did_not_move_the_fight():
    """The load-bearing one, on track H's pattern. The four log additions are
    emits; the outcome figures stay a pure function of the seed."""
    one = run_battery("klee", "reaction_weighted", "punisher", "reaction",
                      25, 99)
    two = run_battery("klee", "reaction_weighted", "punisher", "reaction",
                      25, 99)
    assert [(s.won, s.turns, s.hp_end, s.total_damage_dealt, s.cards_played)
            for s in one] == \
           [(s.won, s.turns, s.hp_end, s.total_damage_dealt, s.cards_played)
            for s in two]


def test_the_three_counter_names_exist_on_the_record():
    """§2.2's evidence of absence was 'zero matches for played_when_drawn /
    dead_in_hand / force_first_copy'. Pin the three names, so the item cannot
    silently reopen by a rename."""
    s = metrics.FightStats(won=False, turns=0, hp_start=1, hp_end=1,
                           total_damage_dealt=0, damage_by_turn={},
                           energy_by_turn={}, total_block_gained=0,
                           damage_blocked=0, energy_spent=0,
                           cards_drawn_extra=0, energy_generated_extra=0,
                           healing=0, encore_absorbed=0,
                           debuff_stacks_applied=0, debuffed_intents=0,
                           aura_intents=0, total_intents=0, reactions=0,
                           reaction_damage=0, auras_wasted=0)
    assert s.played_when_drawn == {}
    assert s.dead_in_hand == {}
    assert s.force_first_copy == {}
    assert s.force_first_copy_drawn == {}


# --- 1: played-when-drawn ------------------------------------------------

def test_played_when_drawn_fires_on_a_card_played_the_turn_it_arrived():
    st = _fight([_card("poke", damage=3)], plays=[["poke"]])
    s = _stats(st)
    assert s.card_draws == {"poke": 1}
    assert s.card_plays == {"poke": 1}
    assert s.played_when_drawn == {"poke": 1}


def test_played_when_drawn_stays_zero_for_a_card_played_a_later_turn():
    """A Retained card survives the flush and is played on turn 2. It was
    drawn on turn 1, so it is a play and NOT a played-when-drawn -- which is
    the entire distinction a per-id tally over the event stream cannot make."""
    st = _fight([_card("slow_burn", damage=3, retain=True)],
                plays=[[], ["slow_burn"]])
    s = _stats(st)
    assert s.card_draws == {"slow_burn": 1}      # drawn once, turn 1
    assert s.card_plays == {"slow_burn": 1}      # played once, turn 2
    assert s.played_when_drawn == {}


def test_played_when_drawn_stays_zero_for_a_card_that_never_came_from_a_draw():
    """A kit Burst is granted to hand, never drawn. Playing it is a play with
    no draw behind it, and -1 is the honest draw turn -- it must never collide
    with a real turn number."""
    st = make_state(enemies=[make_enemy(hp=200)])
    st.turn = 3
    burst = _card("kit_burst", damage=5, tags=["burst"], kit_card=True)
    st.player.hand.append(burst)
    combat.play_card(st, burst)
    s = _stats(st)
    assert s.card_plays == {"kit_burst": 1}
    assert s.played_when_drawn == {}
    play = [e for e in st.log if e["event"] == "play"][0]
    assert play["drawn_turn"] == -1


# --- 2: dead-in-hand -----------------------------------------------------

def test_dead_in_hand_fires_on_a_card_the_flush_threw_away_unplayed():
    st = _fight([_card("dud", cost=9)], plays=[[]])
    s = _stats(st)
    assert s.card_draws == {"dud": 1}
    assert s.card_plays == {}
    assert s.dead_in_hand == {"dud": 1}
    row = [e for e in st.log if e["event"] == "dead_in_hand"]
    assert [(e["card"], e["reason"], e["drawn_turn"]) for e in row] == \
        [("dud", "flush", 1)]


def test_dead_in_hand_stays_zero_for_a_card_that_was_played():
    """The negative of the case above, one card apart: the same fight with
    the card playable and played."""
    st = _fight([_card("live", damage=3)], plays=[["live"]])
    s = _stats(st)
    assert s.dead_in_hand == {}
    assert not [e for e in st.log if e["event"] == "dead_in_hand"]


def test_dead_in_hand_counts_a_retained_card_only_once_the_combat_ends_on_it():
    """Retention is not death. A Retained dud survives two flushes without
    being counted, and is counted exactly once -- at fight end -- when the
    combat finishes with it still sitting in hand."""
    finisher = _card("finisher", damage=50)
    dud = _card("retained_dud", cost=9, retain=True)
    player = Player(hp=200, max_hp=200, draw_pile=[finisher, dud])
    enemy = Enemy(hp=5, max_hp=5, name="paper",
                  intents=[{"kind": "block", "amount": 0}])

    def pilot(s):
        for c in s.player.hand:
            if c.id == "finisher":
                return c
        return None

    st = combat.run_fight(player, [enemy], pilot, seed=1)
    s = _stats(st)
    assert st.player.hand and st.player.hand[0].id == "retained_dud"
    assert s.dead_in_hand == {"retained_dud": 1}
    assert [e["reason"] for e in st.log
            if e["event"] == "dead_in_hand"] == ["fight_end"]


def test_a_card_that_was_never_drawn_is_never_dead_in_hand():
    """A token put straight into hand and left there is not a DRAWN instance,
    so it is outside this counter's denominator (`card_draws`) and outside its
    numerator. Counting it would make the rate uninterpretable."""
    st = make_state(enemies=[make_enemy(hp=200)])
    st.player.hand.append(_card("token", cost=9))
    combat._player_turn(st, lambda s: None)
    s = _stats(st)
    assert "token" not in s.card_draws
    assert s.dead_in_hand == {}


# --- 3: force-first-copy -------------------------------------------------

def test_force_first_copy_fires_when_the_first_copy_drawn_is_played():
    st = _fight([_card("probe", damage=3), _card("probe", damage=3)],
                plays=[["probe"]])
    s = _stats(st)
    assert s.force_first_copy_drawn == {"probe": 1}
    assert s.force_first_copy == {"probe": 1}


def test_force_first_copy_stays_zero_when_only_a_later_copy_is_played():
    """Two copies in hand, and the SECOND one is the one that gets played.
    The first copy was drawn and did nothing, so the conversion is 0 out of a
    denominator of 1 -- the number the register's forced-copy arm is read
    against. A per-id tally would have scored this 1."""
    first, second = _card("probe", damage=3), _card("probe", damage=3)
    st = make_state(enemies=[make_enemy(hp=200)])
    st.turn = 1
    st.player.draw_pile = [first, second]
    st.draw(2)
    assert st.player.hand == [first, second]
    combat.play_card(st, second)
    s = _stats(st)
    assert s.card_draws == {"probe": 2}
    assert s.card_plays == {"probe": 1}
    assert s.force_first_copy_drawn == {"probe": 1}
    assert s.force_first_copy == {}


def test_force_first_copy_is_absent_when_the_copy_was_never_drawn():
    """Never drawn is not failed-to-convert. Absent, not zero: the deck held
    the card and the fight never saw it, which is a different finding."""
    st = _fight([_card("poke", damage=3)] * C.CARDS_DRAWN_PER_TURN
                + [_card("buried", cost=9)], plays=[["poke"]])
    s = _stats(st)
    assert "buried" not in s.card_draws
    assert "buried" not in s.force_first_copy_drawn
    assert "buried" not in s.force_first_copy


def test_the_first_copy_stays_the_first_copy_across_a_redraw():
    """The forced copy is a COPY, not a turn. Drawn, put back, drawn again and
    played, it is still the first copy that converted -- and its twin, drawn
    in between, is still not."""
    first, second = _card("probe", damage=3), _card("probe", damage=3)
    st = make_state(enemies=[make_enemy(hp=200)])
    st.turn = 1
    st.player.draw_pile = [first, second]
    st.draw(2)
    st.player.hand.remove(first)
    st.player.draw_pile.append(first)
    st.turn = 2
    st.draw(1)
    assert st.player.hand[-1] is first
    combat.play_card(st, first)
    s = _stats(st)
    assert s.card_draws == {"probe": 3}
    assert s.force_first_copy == {"probe": 1}
    assert s.played_when_drawn == {"probe": 1}      # drawn AND played on 2


# --- 4: invariants over a real battery -----------------------------------

KLEE = ("klee", "reaction_weighted", "punisher", "reaction")


def _battery(fights=30, seed=7):
    return run_battery(*KLEE, fights, seed)


def test_played_when_drawn_never_exceeds_plays():
    for s in _battery():
        for cid, n in s.played_when_drawn.items():
            assert n <= s.card_plays[cid], cid


def test_played_when_drawn_plus_dead_in_hand_never_exceeds_draws():
    """Each counted play and each counted death consumes one draw of that id,
    and a draw can be consumed once. They do NOT sum to the draws: a card
    Retained into a later turn, or pulled out of hand by a discard or exhaust
    op, is a third outcome and belongs to neither."""
    for s in _battery():
        for cid in set(s.played_when_drawn) | set(s.dead_in_hand):
            assert (s.played_when_drawn.get(cid, 0)
                    + s.dead_in_hand.get(cid, 0)) <= s.card_draws.get(cid, 0), cid


def test_the_first_copy_pair_is_a_zero_or_one_indicator_per_combat():
    for s in metrics.per_combat(_battery()):
        assert set(s.force_first_copy.values()) <= {1}
        assert set(s.force_first_copy_drawn.values()) <= {1}
        for cid in s.force_first_copy:
            assert s.force_first_copy_drawn.get(cid) == 1, cid


def test_cards_played_agrees_with_the_per_card_play_tally():
    for s in _battery():
        assert sum(s.card_plays.values()) == s.cards_played


# --- 5: the aggregate hook ------------------------------------------------

def test_card_flow_profile_pools_and_reports_no_verdict():
    stats = _battery()
    prof = metrics.card_flow_profile(stats)
    combats = metrics.per_combat(stats)
    assert prof["draws"] == sum(sum(s.card_draws.values()) for s in combats)
    assert prof["plays"] == sum(sum(s.card_plays.values()) for s in combats)
    assert prof["dead_in_hand"] == sum(sum(s.dead_in_hand.values())
                                       for s in combats)
    # No grade, no band, no pass/fail -- the track D/H fence, restated.
    for key in ("verdict", "grade", "ok", "healthy", "band", "target",
                "dead_card"):
        assert key not in prof


def test_card_flow_profile_is_empty_not_exploding_on_no_fights():
    assert metrics.card_flow_profile([]) == {}


def test_card_flow_profile_keeps_an_undefined_rate_out_of_the_numbers():
    """A card whose first copy was never drawn has no conversion rate, and
    the split winrates over an empty arm are None rather than 0.0. Printing
    0% for 'never happened' is how a report gets misread."""
    stats = _battery()
    prof = metrics.card_flow_profile(stats)
    for cid, row in prof["by_card"].items():
        if row["first_copy_drawn_combats"] == 0:
            assert row["force_first_copy_rate"] is None, cid
            assert row["winrate_first_copy_played"] is None, cid
            assert row["winrate_first_copy_dead"] is None, cid
        else:
            assert 0.0 <= row["force_first_copy_rate"] <= 1.0, cid


def test_card_flow_profile_denominates_over_combats():
    stats = _battery()
    prof = metrics.card_flow_profile(stats)
    assert prof["combats"] == len(metrics.per_combat(stats))
    for cid, row in prof["by_card"].items():
        assert row["draws_per_fight"] == row["draws"] / prof["combats"], cid


def test_the_winrate_split_covers_exactly_the_combats_that_drew_the_copy():
    """The forced-copy arm's read: every combat that DREW the first copy lands
    in one of the two winrate arms, and no combat that did not draw it lands
    in either."""
    stats = _battery()
    combats = metrics.per_combat(stats)
    prof = metrics.card_flow_profile(stats)
    for cid, row in prof["by_card"].items():
        drew = [s for s in combats if s.force_first_copy_drawn.get(cid)]
        assert len(drew) == row["first_copy_drawn_combats"], cid
        converted = [s for s in drew if s.force_first_copy.get(cid)]
        assert len(converted) == row["force_first_copy"], cid


def test_a_gauntlet_record_ors_the_first_copy_indicator_instead_of_summing():
    """O-1: a `gauntlet` is one record and two combats, each drawing its own
    deck. Summing the two 0/1 stage values would read as two conversions out
    of a denominator of one."""
    a = metrics.extract(_fight([_card("probe", damage=3)],
                               plays=[["probe"]]), 200)
    b = metrics.extract(_fight([_card("probe", damage=3)],
                               plays=[["probe"]]), 200)
    merged = metrics.merge_stages([a, b])
    assert merged.force_first_copy == {"probe": 1}
    assert merged.force_first_copy_drawn == {"probe": 1}
    assert merged.card_draws == {"probe": 2}        # counts DO sum
    assert merged.stages == [a, b]


# --- 6: the printed surface ----------------------------------------------

def test_print_card_flow_is_silent_on_an_empty_profile(capsys):
    from tier0.harness import report
    report.print_card_flow("nothing", {})
    assert capsys.readouterr().out == ""


def test_print_card_flow_prints_the_counters_and_no_verdict(capsys):
    from tier0.harness import report
    report.print_card_flow("punisher", metrics.card_flow_profile(_battery()))
    out = capsys.readouterr().out
    assert "card flow" in out
    assert "dead" in out and "pwd" in out and "first-copy" in out
    for word in ("VERDICT", "FAIL", "dead card", "redesign"):
        assert word not in out


def test_max_hand_size_is_not_silently_hiding_the_draw_denominator():
    """A guard on the fixtures above rather than on the instrument: `_fight`
    leans on every deck card reaching hand, which is only true below the hand
    cap."""
    assert C.CARDS_DRAWN_PER_TURN <= C.MAX_HAND_SIZE
