"""Gate 5: contact-sheet assembly is deterministic.

The claim under test, and the only one made anywhere:

    the same set of input PNGs, in any listing order, on the same machine,
    produces a byte-identical sheet and a byte-identical manifest.

No live captures are taken (the game is in use). The fixtures are generated by
tools/visual_qa/fixtures/make_capture_fixtures.py, which is itself asserted to
be deterministic below -- a determinism claim whose INPUTS drift is not a
determinism claim.
"""

from __future__ import annotations

import hashlib
import random
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.visual_qa import contact_sheet                   # noqa: E402
from tools.visual_qa.findings import ERROR                  # noqa: E402
from tools.visual_qa.fixtures.make_capture_fixtures import (  # noqa: E402
    SPECS, write_fixtures,
)

pytest.importorskip("PIL", reason="contact-sheet assembly decodes PNGs with Pillow")


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.fixture
def captures(tmp_path):
    directory = tmp_path / "captures"
    write_fixtures(directory)
    return directory


def test_fixture_generation_is_itself_deterministic(tmp_path):
    first = write_fixtures(tmp_path / "a")
    second = write_fixtures(tmp_path / "b")
    assert [p.name for p in first] == [p.name for p in second]
    assert [sha(p) for p in first] == [sha(p) for p in second]


def test_same_inputs_produce_a_byte_identical_sheet(captures, tmp_path):
    one = tmp_path / "one" / "sheet.png"
    two = tmp_path / "two" / "sheet.png"
    contact_sheet.write(
        contact_sheet.build(contact_sheet.iter_pngs(captures), captures), one)
    contact_sheet.write(
        contact_sheet.build(contact_sheet.iter_pngs(captures), captures), two)
    assert one.read_bytes() == two.read_bytes()
    assert (one.with_suffix(".png.manifest.txt").read_text(encoding="utf-8")
            == two.with_suffix(".png.manifest.txt").read_text(encoding="utf-8"))


def test_input_listing_order_cannot_reach_the_output(captures, tmp_path):
    """A directory walk's order is an accident; the sheet must not carry it."""
    ordered = contact_sheet.iter_pngs(captures)
    shuffled = list(ordered)
    random.Random(1234).shuffle(shuffled)
    assert shuffled != ordered

    a = contact_sheet.build(ordered, captures)
    b = contact_sheet.build(shuffled, captures)
    assert a.png == b.png
    assert a.manifest_text() == b.manifest_text()
    assert [c.name for c in a.cells] == [c.name for c in b.cells]


def test_the_png_carries_no_ancillary_chunks(captures):
    """No tEXt, tIME, pHYs, gAMA -- the four usual reasons two PNGs differ."""
    sheet = contact_sheet.build(contact_sheet.iter_pngs(captures), captures)
    body = sheet.png[len(contact_sheet.PNG_MAGIC):]
    tags = []
    index = 0
    while index < len(body):
        length = int.from_bytes(body[index:index + 4], "big")
        tags.append(body[index + 4:index + 8].decode("ascii"))
        index += 12 + length
    assert tags == ["IHDR", "IDAT", "IEND"], tags


def test_the_manifest_records_pixels_not_only_bytes(captures):
    """rgba_sha256 survives a zlib difference; png_sha256 does not, and says so."""
    sheet = contact_sheet.build(contact_sheet.iter_pngs(captures), captures)
    text = sheet.manifest_text()
    assert "rgba_sha256=" in text and "png_sha256=" in text
    assert text.endswith("\n")
    # every capture is billed by name and by source hash
    for name, _, _, _ in SPECS:
        assert name in text
    assert len(sheet.cells) == len(SPECS)


def test_geometry_is_what_it_says_it_is(captures):
    sheet = contact_sheet.build(
        contact_sheet.iter_pngs(captures), captures,
        columns=2, cell=64, padding=4)
    assert sheet.columns == 2
    assert sheet.rows == 3               # five captures over two columns
    assert sheet.width == 4 + 2 * (64 + 4)
    assert sheet.height == 4 + 3 * (64 + 4)


def test_an_empty_capture_directory_fails(tmp_path):
    out = tmp_path / "sheet.png"
    empty = tmp_path / "captures"
    empty.mkdir()
    report = contact_sheet.run(empty, out, tmp_path)
    assert "SH-EMPTY" in {f.rule for f in report.findings if f.severity == ERROR}
    assert not out.exists()


def test_a_webp_wearing_a_png_name_is_reported_not_decoded(captures, tmp_path):
    """build_pck.ps1:754-768 carries a re-encode block for exactly this."""
    (captures / "wiki_served.png").write_bytes(b"RIFF" + b"\x00" * 60)
    report = contact_sheet.run(captures, tmp_path / "sheet.png", tmp_path)
    assert "SH-NOT-PNG" in {f.rule for f in report.findings}
    # the rest of the sheet is still built, from the five real captures
    assert report.checked["cells"] == len(SPECS)


def test_run_writes_the_sheet_and_its_manifest(tmp_path, captures):
    out = tmp_path / "out" / "sheet.png"
    report = contact_sheet.run(captures, out, tmp_path)
    assert report.errors == [], report.render(verbose=True)
    assert out.is_file()
    assert out.with_suffix(".png.manifest.txt").is_file()
