"""EB-249: what the distinctness instrument reads, both halves.

(a) THE INPUT. `SHEETS` globbed `docs/*-cards.yaml` and then appended
`mondstadt-companions.yaml` and nothing else, so Fontaine's and Inazuma's
companion sheets were ABSENT from the instrument's input. That is a different
failure from the size exemption at `GATE_MIN_POOL`: an exempt pool is measured
and printed and skipped by the gate with its size named, and an absent one is
not there at all. Reading (a) alone as coverage is what the row warns about.

(b) THE TAXONOMY. The metric measures the DRAFTABLE UNIVERSAL pool -- how much
a player choosing among these cards is really choosing between. Personal rows
(a `personal_pool` field: Prune, who is Klee's) and `guest_star` rows (the
Fontaine cameos) are not in that pool, and counting them would put cards no
player can draft inside a ratio about drafting. Fontaine is the proof: three
of its nineteen rows are cameos.

Neither half bites the gate today -- all three sheets are under
`GATE_MIN_POOL` and are skipped by size, exactly as Mondstadt already was --
which is precisely why they are pinned here rather than left to be noticed
when a pool reaches 30.
"""

import os

import pytest

from tools import card_distinctness_report as cdr


COMPANION_SHEETS = ("mondstadt-companions.yaml", "fontaine-companions.yaml",
                    "inazuma-companions.yaml")


def _names(reports):
    return {r["pool"] for r in reports}


def _report(name):
    return next(r for r in cdr.build_reports() if r["pool"] == name)


def test_every_companion_sheet_is_in_the_instruments_input():
    """(a). Three nations have companion sheets; the instrument read one."""
    have = {os.path.basename(p) for p in cdr.SHEETS}
    assert set(COMPANION_SHEETS) <= have


def test_all_three_companion_pools_are_measured_and_named():
    names = _names(cdr.build_reports())
    assert {"mondstadt-companions", "fontaine-companions",
            "inazuma-companions"} <= names


def test_a_personal_row_is_not_in_the_universal_pool():
    """(b), Mondstadt's half. Prune is Klee's Personal Companion -- she
    carries `personal_pool: klee` and no other nation's draft can see her."""
    assert _report("mondstadt-companions")["cards"] == 16   # 17 rows - Prune


def test_guest_stars_are_not_in_the_universal_pool():
    """(b), Fontaine's half, and the loudest case: three of nineteen rows
    are temporary cameos generated by a Furina mechanism, never drafted."""
    assert _report("fontaine-companions")["cards"] == 16    # 19 rows - 3


def test_a_sheet_with_neither_is_read_whole():
    """The control. Inazuma carries no Personal and no cameo row, so the
    filter must take nothing off it -- a taxonomy filter that quietly
    narrowed an ordinary sheet would be a second defect."""
    assert _report("inazuma-companions")["cards"] == 15


def test_the_character_pools_are_untouched_by_the_filter():
    """The three ratified pools are the instrument's whole live reading and
    the debt list is keyed on them. No row on any of them carries either
    field, so every count must be exactly what it was."""
    counts = {r["pool"]: r["cards"] for r in cdr.build_reports()}
    assert counts["furina"] == 84
    assert counts["klee"] == 79
    assert counts["kokomi"] == 76


def test_the_added_sheets_are_skipped_by_size_and_say_so():
    """The gate's own output stays otherwise unchanged: the two new pools
    join Mondstadt in the SKIPPED line with their sizes printed, and they
    breach nothing -- which is the state the row describes and the state a
    future pool of 30 leaves."""
    reports = cdr.build_reports()
    breaches, skipped = cdr.gate_breaches(reports)
    skipped_pools = {s.split(" (")[0] for s in skipped}
    for pool in ("mondstadt-companions", "fontaine-companions",
                 "inazuma-companions"):
        assert pool in skipped_pools
    assert not [b for b in breaches if b[0].endswith("-companions")]


def test_the_ratified_debt_is_exactly_what_it_was():
    """The breaches this branch must not move: the curated debt on the two
    character sheets, and nothing else on a house pool."""
    breaches, _ = cdr.gate_breaches(cdr.build_reports())
    house = {(pool, metric) for pool, metric, _ in breaches
             if not pool.startswith("OFFICIAL:")}
    assert house == {("klee", "uniq"), ("kokomi", "uniq"),
                     ("kokomi", "maxclu")}
