// <auto-generated>
//     GENERATED by tools/gen_teyvat_creature_scenes.py from
//     docs/current/dossiers/content/enemy-dressings.tsv
//     Do not edit by hand: `python tools/gen_teyvat_creature_scenes.py --check`
//     fails on any drift, and the next run overwrites it.
// </auto-generated>

using System.Collections.Generic;

namespace KleeMod.Teyvat;

/// <summary>
/// THE DRESSED ENEMY BODIES, generated from the one table (`EB-811`).
///
/// A PICTURE AND A NAME ARE ONE ROW. `StillPortraits` is what
/// `Patches/MonsterVisualsPathPatch` swaps a `MonsterModel.VisualsPath` for,
/// and `MonsterNames` is what `Patches/MonsterNamePatch` and
/// `TeyvatLoc.Inject` turn into the dressed `monsters` loc rows. Both come out
/// of the same TSV line, so a body cannot reach the arena wearing its own
/// picture under the Spire's name, or the reverse -- which is exactly what
/// hand-maintaining two tables was going to cost.
///
/// 77 plate(s) in the table; 97 (face, Id.Entry) row(s) below.
/// A kept plate with no live row has a scene and a packaged texture but
/// nothing to key on -- an Ancient is an `AncientEventModel` and has no
/// `creature_visuals` scene at all, and a four-body elite is ONE `Id.Entry`,
/// so only one of its plates can draw. Today those are:
///   * chanca
///   * cryo_abyss_mage
///   * electro_abyss_mage
///   * hirayama
///   * liloupar
///   * pyro_abyss_mage
///
/// EVERY ROW IS INERT WITHOUT THE ARM. `TeyvatFrame.CurrentActEntry` returns
/// null when `Enabled` is false, both patches return early on null, and
/// `TeyvatLoc.Inject` merges nothing -- so a release package's creature
/// visuals and loc tables are byte-identical to the base game's.
/// </summary>
internal static class TeyvatGeneratedCreatures
{
    /// <summary>
    /// `(dressing, monster Id.Entry)` -> the pck scene that draws it.
    ///
    /// A row whose base enemy the face never rolls is INERT, not wrong: the
    /// lookup simply never fires. Act 1's two faces stand on two DIFFERENT
    /// base zones (Mondstadt on Overgrowth, Liyue on Underdocks), so a handful
    /// of act-1 rows are inert by construction; the table's `notes` column
    /// names each one.
    /// </summary>
    internal static readonly IReadOnlyDictionary<(string Dressing, string Entry), string> StillPortraits =
        new Dictionary<(string, string), string>
        {
            // MONDSTADT
            [(TeyvatFrame.Mondstadt, "BYGONE_EFFIGY")] =
                "res://teyvat/creature_visuals/ruin_guard.tscn",
            [(TeyvatFrame.Mondstadt, "BYRDONIS")] =
                "res://teyvat/creature_visuals/anemo_hilichurl_rogue.tscn",
            [(TeyvatFrame.Mondstadt, "FOGMOG")] =
                "res://teyvat/creature_visuals/anemo_samachurl.tscn",
            [(TeyvatFrame.Mondstadt, "INKLET")] =
                "res://teyvat/creature_visuals/hilichurl.tscn",
            [(TeyvatFrame.Mondstadt, "LAGAVULIN_MATRIARCH")] =
                "res://teyvat/creature_visuals/cryo_regisvine.tscn",
            [(TeyvatFrame.Mondstadt, "LEAF_SLIME_M")] =
                "res://teyvat/creature_visuals/dendro_slime.tscn",
            [(TeyvatFrame.Mondstadt, "LEAF_SLIME_S")] =
                "res://teyvat/creature_visuals/dendro_slime.tscn",
            [(TeyvatFrame.Mondstadt, "MAWLER")] =
                "res://teyvat/creature_visuals/rockfond_rifthound.tscn",
            [(TeyvatFrame.Mondstadt, "NIBBIT")] =
                "res://teyvat/creature_visuals/wooden_shield_hilichurl_guard.tscn",
            [(TeyvatFrame.Mondstadt, "PHANTASMAL_GARDENER")] =
                "res://teyvat/creature_visuals/hydro_abyss_mage.tscn",
            [(TeyvatFrame.Mondstadt, "SEWER_CLAM")] =
                "res://teyvat/creature_visuals/fatui_hydrogunner_legionnaire.tscn",
            [(TeyvatFrame.Mondstadt, "TWIG_SLIME_M")] =
                "res://teyvat/creature_visuals/cryo_slime.tscn",
            [(TeyvatFrame.Mondstadt, "TWIG_SLIME_S")] =
                "res://teyvat/creature_visuals/cryo_slime.tscn",
            [(TeyvatFrame.Mondstadt, "VANTOM")] =
                "res://teyvat/creature_visuals/boreas.tscn",
            // LIYUE
            [(TeyvatFrame.Liyue, "BYGONE_EFFIGY")] =
                "res://teyvat/creature_visuals/ruin_guard.tscn",
            [(TeyvatFrame.Liyue, "BYRDONIS")] =
                "res://teyvat/creature_visuals/treasure_hoarder_marksman.tscn",
            [(TeyvatFrame.Liyue, "FOGMOG")] =
                "res://teyvat/creature_visuals/anemo_samachurl.tscn",
            [(TeyvatFrame.Liyue, "INKLET")] =
                "res://teyvat/creature_visuals/treasure_hoarder_scout.tscn",
            [(TeyvatFrame.Liyue, "LAGAVULIN_MATRIARCH")] =
                "res://teyvat/creature_visuals/primo_geovishap.tscn",
            [(TeyvatFrame.Liyue, "LEAF_SLIME_M")] =
                "res://teyvat/creature_visuals/geo_slime.tscn",
            [(TeyvatFrame.Liyue, "LEAF_SLIME_S")] =
                "res://teyvat/creature_visuals/geo_slime.tscn",
            [(TeyvatFrame.Liyue, "MAWLER")] =
                "res://teyvat/creature_visuals/geovishap_hatchling.tscn",
            [(TeyvatFrame.Liyue, "NIBBIT")] =
                "res://teyvat/creature_visuals/treasure_hoarder_handyman.tscn",
            [(TeyvatFrame.Liyue, "PHANTASMAL_GARDENER")] =
                "res://teyvat/creature_visuals/hilichurl_fighter.tscn",
            [(TeyvatFrame.Liyue, "SEWER_CLAM")] =
                "res://teyvat/creature_visuals/large_geo_slime.tscn",
            [(TeyvatFrame.Liyue, "TWIG_SLIME_M")] =
                "res://teyvat/creature_visuals/hydro_slime.tscn",
            [(TeyvatFrame.Liyue, "TWIG_SLIME_S")] =
                "res://teyvat/creature_visuals/hydro_slime.tscn",
            [(TeyvatFrame.Liyue, "VANTOM")] =
                "res://teyvat/creature_visuals/kongamato.tscn",
            // NATLAN
            [(TeyvatFrame.Natlan, "BOWLBUG_ROCK")] =
                "res://teyvat/creature_visuals/tepetlisaurus_warrior_rockbreaker_blade.tscn",
            [(TeyvatFrame.Natlan, "BOWLBUG_SILK")] =
                "res://teyvat/creature_visuals/tepetlisaur_whelp.tscn",
            [(TeyvatFrame.Natlan, "CHOMPER")] =
                "res://teyvat/creature_visuals/koholasaurus.tscn",
            [(TeyvatFrame.Natlan, "CRUSHER")] =
                "res://teyvat/creature_visuals/magatsu_mitake_narukami_no_mikoto.tscn",
            [(TeyvatFrame.Natlan, "DECIMILLIPEDE_SEGMENT_BACK")] =
                "res://teyvat/creature_visuals/rock_shield_hilichurl_guard.tscn",
            [(TeyvatFrame.Natlan, "DECIMILLIPEDE_SEGMENT_FRONT")] =
                "res://teyvat/creature_visuals/rock_shield_hilichurl_guard.tscn",
            [(TeyvatFrame.Natlan, "DECIMILLIPEDE_SEGMENT_MIDDLE")] =
                "res://teyvat/creature_visuals/rock_shield_hilichurl_guard.tscn",
            [(TeyvatFrame.Natlan, "ENTOMANCER")] =
                "res://teyvat/creature_visuals/yumkasaurus_warrior_flowing_skyfire.tscn",
            [(TeyvatFrame.Natlan, "EXOSKELETON")] =
                "res://teyvat/creature_visuals/tepetlisaur_whelp.tscn",
            [(TeyvatFrame.Natlan, "HUNTER_KILLER")] =
                "res://teyvat/creature_visuals/yumkasaurus.tscn",
            [(TeyvatFrame.Natlan, "INFESTED_PRISM")] =
                "res://teyvat/creature_visuals/rock_cavernous_wayob_manifestation.tscn",
            [(TeyvatFrame.Natlan, "KNOWLEDGE_DEMON")] =
                "res://teyvat/creature_visuals/everlasting_lord_of_arcane_wisdom.tscn",
            [(TeyvatFrame.Natlan, "LOUSE_PROGENITOR")] =
                "res://teyvat/creature_visuals/tatankasaurus.tscn",
            [(TeyvatFrame.Natlan, "MYTE")] =
                "res://teyvat/creature_visuals/yumkasaur_whelp.tscn",
            [(TeyvatFrame.Natlan, "OVICOPTER")] =
                "res://teyvat/creature_visuals/iktomisaurus.tscn",
            [(TeyvatFrame.Natlan, "PARAFRIGHT")] =
                "res://teyvat/creature_visuals/hydro_samachurl.tscn",
            [(TeyvatFrame.Natlan, "ROCKET")] =
                "res://teyvat/creature_visuals/magatsu_mitake_narukami_no_mikoto.tscn",
            [(TeyvatFrame.Natlan, "THE_OBSCURA")] =
                "res://teyvat/creature_visuals/hydro_samachurl.tscn",
            [(TeyvatFrame.Natlan, "TOUGH_EGG")] =
                "res://teyvat/creature_visuals/iktomisaurus_chick.tscn",
            [(TeyvatFrame.Natlan, "TUNNELER")] =
                "res://teyvat/creature_visuals/tepetlisaurus.tscn",
            // INAZUMA
            [(TeyvatFrame.Inazuma, "BOWLBUG_ROCK")] =
                "res://teyvat/creature_visuals/nobushi_kikouban.tscn",
            [(TeyvatFrame.Inazuma, "BOWLBUG_SILK")] =
                "res://teyvat/creature_visuals/nobushi_kikouban.tscn",
            [(TeyvatFrame.Inazuma, "CHOMPER")] =
                "res://teyvat/creature_visuals/rockfond_rifthound.tscn",
            [(TeyvatFrame.Inazuma, "CRUSHER")] =
                "res://teyvat/creature_visuals/magatsu_mitake_narukami_no_mikoto.tscn",
            [(TeyvatFrame.Inazuma, "DECIMILLIPEDE_SEGMENT_BACK")] =
                "res://teyvat/creature_visuals/electro_specter.tscn",
            [(TeyvatFrame.Inazuma, "DECIMILLIPEDE_SEGMENT_FRONT")] =
                "res://teyvat/creature_visuals/electro_specter.tscn",
            [(TeyvatFrame.Inazuma, "DECIMILLIPEDE_SEGMENT_MIDDLE")] =
                "res://teyvat/creature_visuals/electro_specter.tscn",
            [(TeyvatFrame.Inazuma, "ENTOMANCER")] =
                "res://teyvat/creature_visuals/kairagi_fiery_might.tscn",
            [(TeyvatFrame.Inazuma, "EXOSKELETON")] =
                "res://teyvat/creature_visuals/thundercraven_rifthound_whelp.tscn",
            [(TeyvatFrame.Inazuma, "HUNTER_KILLER")] =
                "res://teyvat/creature_visuals/primordial_bathysmal_vishap.tscn",
            [(TeyvatFrame.Inazuma, "INFESTED_PRISM")] =
                "res://teyvat/creature_visuals/electro_specter.tscn",
            [(TeyvatFrame.Inazuma, "LOUSE_PROGENITOR")] =
                "res://teyvat/creature_visuals/wooden_shieldwall_mitachurl.tscn",
            [(TeyvatFrame.Inazuma, "MYTE")] =
                "res://teyvat/creature_visuals/dendro_samachurl.tscn",
            [(TeyvatFrame.Inazuma, "OVICOPTER")] =
                "res://teyvat/creature_visuals/fatui_cryo_cicin_mage.tscn",
            [(TeyvatFrame.Inazuma, "PARAFRIGHT")] =
                "res://teyvat/creature_visuals/hydro_samachurl.tscn",
            [(TeyvatFrame.Inazuma, "ROCKET")] =
                "res://teyvat/creature_visuals/magatsu_mitake_narukami_no_mikoto.tscn",
            [(TeyvatFrame.Inazuma, "THE_OBSCURA")] =
                "res://teyvat/creature_visuals/hydro_samachurl.tscn",
            [(TeyvatFrame.Inazuma, "TOUGH_EGG")] =
                "res://teyvat/creature_visuals/fatui_cryo_cicin_mage.tscn",
            [(TeyvatFrame.Inazuma, "TUNNELER")] =
                "res://teyvat/creature_visuals/thundercraven_rifthound.tscn",
            // FONTAINE
            [(TeyvatFrame.Fontaine, "AEONGLASS")] =
                "res://teyvat/creature_visuals/prototype_cal_breguet.tscn",
            [(TeyvatFrame.Fontaine, "AXEBOT")] =
                "res://teyvat/creature_visuals/assault_specialist_mek.tscn",
            [(TeyvatFrame.Fontaine, "CUBEX_CONSTRUCT")] =
                "res://teyvat/creature_visuals/overgrown_breacher_primus.tscn",
            [(TeyvatFrame.Fontaine, "DEVOTED_SCULPTOR")] =
                "res://teyvat/creature_visuals/geo_samachurl.tscn",
            [(TeyvatFrame.Fontaine, "FABRICATOR")] =
                "res://teyvat/creature_visuals/annihilation_specialist_mek.tscn",
            [(TeyvatFrame.Fontaine, "FLAIL_KNIGHT")] =
                "res://teyvat/creature_visuals/mirror_maiden.tscn",
            [(TeyvatFrame.Fontaine, "FROG_KNIGHT")] =
                "res://teyvat/creature_visuals/frostarm_lawachurl.tscn",
            [(TeyvatFrame.Fontaine, "LIVING_SHIELD")] =
                "res://teyvat/creature_visuals/construction_specialist_mek.tscn",
            [(TeyvatFrame.Fontaine, "MAGI_KNIGHT")] =
                "res://teyvat/creature_visuals/mirror_maiden.tscn",
            [(TeyvatFrame.Fontaine, "MECHA_KNIGHT")] =
                "res://teyvat/creature_visuals/shatterstone_breacher_primus.tscn",
            [(TeyvatFrame.Fontaine, "PUNCH_CONSTRUCT")] =
                "res://teyvat/creature_visuals/suppression_specialist_mek.tscn",
            [(TeyvatFrame.Fontaine, "SCROLL_OF_BITING")] =
                "res://teyvat/creature_visuals/hydro_specter.tscn",
            [(TeyvatFrame.Fontaine, "SOUL_NEXUS")] =
                "res://teyvat/creature_visuals/electro_regisvine.tscn",
            [(TeyvatFrame.Fontaine, "SPECTRAL_KNIGHT")] =
                "res://teyvat/creature_visuals/mirror_maiden.tscn",
            [(TeyvatFrame.Fontaine, "TEST_SUBJECT")] =
                "res://teyvat/creature_visuals/iniquitous_baptist.tscn",
            [(TeyvatFrame.Fontaine, "TURRET_OPERATOR")] =
                "res://teyvat/creature_visuals/area_alert_mek.tscn",
            // SUMERU
            [(TeyvatFrame.Sumeru, "AEONGLASS")] =
                "res://teyvat/creature_visuals/everlasting_lord_of_arcane_wisdom.tscn",
            [(TeyvatFrame.Sumeru, "DEVOTED_SCULPTOR")] =
                "res://teyvat/creature_visuals/eremite_scorching_loremaster.tscn",
            [(TeyvatFrame.Sumeru, "FABRICATOR")] =
                "res://teyvat/creature_visuals/golden_wolflord.tscn",
            [(TeyvatFrame.Sumeru, "FLAIL_KNIGHT")] =
                "res://teyvat/creature_visuals/eremite_sunfrost.tscn",
            [(TeyvatFrame.Sumeru, "FROG_KNIGHT")] =
                "res://teyvat/creature_visuals/eremite_stone_enchanter.tscn",
            [(TeyvatFrame.Sumeru, "GLOBE_HEAD")] =
                "res://teyvat/creature_visuals/eremite_daythunder.tscn",
            [(TeyvatFrame.Sumeru, "LIVING_SHIELD")] =
                "res://teyvat/creature_visuals/eremite_ravenbeak_halberdier.tscn",
            [(TeyvatFrame.Sumeru, "MAGI_KNIGHT")] =
                "res://teyvat/creature_visuals/eremite_sunfrost.tscn",
            [(TeyvatFrame.Sumeru, "MECHA_KNIGHT")] =
                "res://teyvat/creature_visuals/consecrated_red_vulture.tscn",
            [(TeyvatFrame.Sumeru, "SCROLL_OF_BITING")] =
                "res://teyvat/creature_visuals/eremite_linebreaker.tscn",
            [(TeyvatFrame.Sumeru, "SLIMED_BERSERKER")] =
                "res://teyvat/creature_visuals/consecrated_horned_crocodile.tscn",
            [(TeyvatFrame.Sumeru, "SPECTRAL_KNIGHT")] =
                "res://teyvat/creature_visuals/eremite_sunfrost.tscn",
            [(TeyvatFrame.Sumeru, "TEST_SUBJECT")] =
                "res://teyvat/creature_visuals/warden_of_oasis_prime.tscn",
            [(TeyvatFrame.Sumeru, "TURRET_OPERATOR")] =
                "res://teyvat/creature_visuals/eremite_crossbow.tscn",
        };

    /// <summary>
    /// `(dressing, monster loc key)` -> the dressed string. The key is what
    /// `MonsterModel.L10NMonsterLookup` is called with, which for a display
    /// name is `Id.Entry + ".name"`.
    /// </summary>
    internal static readonly IReadOnlyDictionary<(string Dressing, string Key), string> MonsterNames =
        new Dictionary<(string, string), string>
        {
            // MONDSTADT
            [(TeyvatFrame.Mondstadt, "BYGONE_EFFIGY.name")] =
                "Ruin Guard",
            [(TeyvatFrame.Mondstadt, "BYRDONIS.name")] =
                "Anemo Hilichurl Rogue",
            [(TeyvatFrame.Mondstadt, "FOGMOG.name")] =
                "Anemo Samachurl",
            [(TeyvatFrame.Mondstadt, "INKLET.name")] =
                "Hilichurl",
            [(TeyvatFrame.Mondstadt, "LAGAVULIN_MATRIARCH.name")] =
                "Cryo Regisvine",
            [(TeyvatFrame.Mondstadt, "LEAF_SLIME_M.name")] =
                "Dendro Slime",
            [(TeyvatFrame.Mondstadt, "LEAF_SLIME_S.name")] =
                "Dendro Slime",
            [(TeyvatFrame.Mondstadt, "MAWLER.name")] =
                "Rockfond Rifthound",
            [(TeyvatFrame.Mondstadt, "NIBBIT.name")] =
                "Wooden Shield Hilichurl Guard",
            [(TeyvatFrame.Mondstadt, "PHANTASMAL_GARDENER.name")] =
                "Hydro Abyss Mage",
            [(TeyvatFrame.Mondstadt, "SEWER_CLAM.name")] =
                "Fatui Hydrogunner Legionnaire",
            [(TeyvatFrame.Mondstadt, "TWIG_SLIME_M.name")] =
                "Cryo Slime",
            [(TeyvatFrame.Mondstadt, "TWIG_SLIME_S.name")] =
                "Cryo Slime",
            [(TeyvatFrame.Mondstadt, "VANTOM.name")] =
                "Andrius",
            // LIYUE
            [(TeyvatFrame.Liyue, "BYGONE_EFFIGY.name")] =
                "Ruin Guard",
            [(TeyvatFrame.Liyue, "BYRDONIS.name")] =
                "Treasure Hoarder Marksman",
            [(TeyvatFrame.Liyue, "FOGMOG.name")] =
                "Anemo Samachurl",
            [(TeyvatFrame.Liyue, "INKLET.name")] =
                "Treasure Hoarder Scout",
            [(TeyvatFrame.Liyue, "LAGAVULIN_MATRIARCH.name")] =
                "Primo Geovishap",
            [(TeyvatFrame.Liyue, "LEAF_SLIME_M.name")] =
                "Geo Slime",
            [(TeyvatFrame.Liyue, "LEAF_SLIME_S.name")] =
                "Geo Slime",
            [(TeyvatFrame.Liyue, "MAWLER.name")] =
                "Geovishap Hatchling",
            [(TeyvatFrame.Liyue, "NIBBIT.name")] =
                "Treasure Hoarder Handyman",
            [(TeyvatFrame.Liyue, "PHANTASMAL_GARDENER.name")] =
                "Hilichurl Fighter",
            [(TeyvatFrame.Liyue, "SEWER_CLAM.name")] =
                "Large Geo Slime",
            [(TeyvatFrame.Liyue, "TWIG_SLIME_M.name")] =
                "Hydro Slime",
            [(TeyvatFrame.Liyue, "TWIG_SLIME_S.name")] =
                "Hydro Slime",
            [(TeyvatFrame.Liyue, "VANTOM.name")] =
                "Kongamato",
            // NATLAN
            [(TeyvatFrame.Natlan, "BOWLBUG_ROCK.name")] =
                "Tepetlisaurus Warrior: Rockbreaker Blade",
            [(TeyvatFrame.Natlan, "BOWLBUG_SILK.name")] =
                "Tepetlisaur Whelp",
            [(TeyvatFrame.Natlan, "CHOMPER.name")] =
                "Koholasaurus",
            [(TeyvatFrame.Natlan, "CRUSHER.name")] =
                "Magatsu Mitake Narukami no Mikoto",
            [(TeyvatFrame.Natlan, "DECIMILLIPEDE_SEGMENT_BACK.name")] =
                "Rock Shield Hilichurl Guard",
            [(TeyvatFrame.Natlan, "DECIMILLIPEDE_SEGMENT_FRONT.name")] =
                "Rock Shield Hilichurl Guard",
            [(TeyvatFrame.Natlan, "DECIMILLIPEDE_SEGMENT_MIDDLE.name")] =
                "Rock Shield Hilichurl Guard",
            [(TeyvatFrame.Natlan, "ENTOMANCER.name")] =
                "Yumkasaurus Warrior: Flowing Skyfire",
            [(TeyvatFrame.Natlan, "EXOSKELETON.name")] =
                "Tepetlisaur Whelp",
            [(TeyvatFrame.Natlan, "HUNTER_KILLER.name")] =
                "Yumkasaurus",
            [(TeyvatFrame.Natlan, "INFESTED_PRISM.name")] =
                "Rock-Cavernous Wayob Manifestation",
            [(TeyvatFrame.Natlan, "KNOWLEDGE_DEMON.name")] =
                "Shouki no Kami",
            [(TeyvatFrame.Natlan, "LOUSE_PROGENITOR.name")] =
                "Tatankasaurus",
            [(TeyvatFrame.Natlan, "MYTE.name")] =
                "Yumkasaur Whelp",
            [(TeyvatFrame.Natlan, "OVICOPTER.name")] =
                "Iktomisaurus",
            [(TeyvatFrame.Natlan, "PARAFRIGHT.name")] =
                "Hydro Samachurl",
            [(TeyvatFrame.Natlan, "ROCKET.name")] =
                "Magatsu Mitake Narukami no Mikoto",
            [(TeyvatFrame.Natlan, "THE_OBSCURA.name")] =
                "Hydro Samachurl",
            [(TeyvatFrame.Natlan, "TOUGH_EGG.name")] =
                "Iktomisaurus Chick",
            [(TeyvatFrame.Natlan, "TUNNELER.name")] =
                "Tepetlisaurus",
            // INAZUMA
            [(TeyvatFrame.Inazuma, "BOWLBUG_ROCK.name")] =
                "Nobushi: Kikouban",
            [(TeyvatFrame.Inazuma, "BOWLBUG_SILK.name")] =
                "Nobushi: Kikouban",
            [(TeyvatFrame.Inazuma, "CHOMPER.name")] =
                "Rockfond Rifthound",
            [(TeyvatFrame.Inazuma, "CRUSHER.name")] =
                "Magatsu Mitake Narukami no Mikoto",
            [(TeyvatFrame.Inazuma, "DECIMILLIPEDE_SEGMENT_BACK.name")] =
                "Electro Specter",
            [(TeyvatFrame.Inazuma, "DECIMILLIPEDE_SEGMENT_FRONT.name")] =
                "Electro Specter",
            [(TeyvatFrame.Inazuma, "DECIMILLIPEDE_SEGMENT_MIDDLE.name")] =
                "Electro Specter",
            [(TeyvatFrame.Inazuma, "ENTOMANCER.name")] =
                "Kairagi: Fiery Might",
            [(TeyvatFrame.Inazuma, "EXOSKELETON.name")] =
                "Thundercraven Rifthound Whelp",
            [(TeyvatFrame.Inazuma, "HUNTER_KILLER.name")] =
                "Primordial Bathysmal Vishap",
            [(TeyvatFrame.Inazuma, "INFESTED_PRISM.name")] =
                "Electro Specter",
            [(TeyvatFrame.Inazuma, "LOUSE_PROGENITOR.name")] =
                "Wooden Shieldwall Mitachurl",
            [(TeyvatFrame.Inazuma, "MYTE.name")] =
                "Dendro Samachurl",
            [(TeyvatFrame.Inazuma, "OVICOPTER.name")] =
                "Fatui Cryo Cicin Mage",
            [(TeyvatFrame.Inazuma, "PARAFRIGHT.name")] =
                "Hydro Samachurl",
            [(TeyvatFrame.Inazuma, "ROCKET.name")] =
                "Magatsu Mitake Narukami no Mikoto",
            [(TeyvatFrame.Inazuma, "THE_OBSCURA.name")] =
                "Hydro Samachurl",
            [(TeyvatFrame.Inazuma, "TOUGH_EGG.name")] =
                "Fatui Cryo Cicin Mage",
            [(TeyvatFrame.Inazuma, "TUNNELER.name")] =
                "Thundercraven Rifthound",
            // FONTAINE
            [(TeyvatFrame.Fontaine, "AEONGLASS.name")] =
                "Prototype: Cal. Breguet",
            [(TeyvatFrame.Fontaine, "AXEBOT.name")] =
                "Assault Specialist Mek",
            [(TeyvatFrame.Fontaine, "CUBEX_CONSTRUCT.name")] =
                "Overgrown Breacher Primus",
            [(TeyvatFrame.Fontaine, "DEVOTED_SCULPTOR.name")] =
                "Geo Samachurl",
            [(TeyvatFrame.Fontaine, "FABRICATOR.name")] =
                "Annihilation Specialist Mek",
            [(TeyvatFrame.Fontaine, "FLAIL_KNIGHT.name")] =
                "Mirror Maiden",
            [(TeyvatFrame.Fontaine, "FROG_KNIGHT.name")] =
                "Frostarm Lawachurl",
            [(TeyvatFrame.Fontaine, "LIVING_SHIELD.name")] =
                "Construction Specialist Mek",
            [(TeyvatFrame.Fontaine, "MAGI_KNIGHT.name")] =
                "Mirror Maiden",
            [(TeyvatFrame.Fontaine, "MECHA_KNIGHT.name")] =
                "Large Shatterstone Breacher Primus",
            [(TeyvatFrame.Fontaine, "PUNCH_CONSTRUCT.name")] =
                "Suppression Specialist Mek",
            [(TeyvatFrame.Fontaine, "SCROLL_OF_BITING.name")] =
                "Hydro Specter",
            [(TeyvatFrame.Fontaine, "SOUL_NEXUS.name")] =
                "Electro Regisvine",
            [(TeyvatFrame.Fontaine, "SPECTRAL_KNIGHT.name")] =
                "Mirror Maiden",
            [(TeyvatFrame.Fontaine, "TEST_SUBJECT.name")] =
                "Iniquitous Baptist",
            [(TeyvatFrame.Fontaine, "TURRET_OPERATOR.name")] =
                "Area Alert Mek",
            // SUMERU
            [(TeyvatFrame.Sumeru, "AEONGLASS.name")] =
                "Shouki no Kami",
            [(TeyvatFrame.Sumeru, "DEVOTED_SCULPTOR.name")] =
                "Eremite Scorching Loremaster",
            [(TeyvatFrame.Sumeru, "FABRICATOR.name")] =
                "Golden Wolflord",
            [(TeyvatFrame.Sumeru, "FLAIL_KNIGHT.name")] =
                "Eremite Sunfrost",
            [(TeyvatFrame.Sumeru, "FROG_KNIGHT.name")] =
                "Eremite Stone Enchanter",
            [(TeyvatFrame.Sumeru, "GLOBE_HEAD.name")] =
                "Eremite Daythunder",
            [(TeyvatFrame.Sumeru, "LIVING_SHIELD.name")] =
                "Eremite Ravenbeak Halberdier",
            [(TeyvatFrame.Sumeru, "MAGI_KNIGHT.name")] =
                "Eremite Sunfrost",
            [(TeyvatFrame.Sumeru, "MECHA_KNIGHT.name")] =
                "Consecrated Red Vulture",
            [(TeyvatFrame.Sumeru, "SCROLL_OF_BITING.name")] =
                "Eremite Linebreaker",
            [(TeyvatFrame.Sumeru, "SLIMED_BERSERKER.name")] =
                "Consecrated Horned Crocodile",
            [(TeyvatFrame.Sumeru, "SPECTRAL_KNIGHT.name")] =
                "Eremite Sunfrost",
            [(TeyvatFrame.Sumeru, "TEST_SUBJECT.name")] =
                "Apep's Guardian",
            [(TeyvatFrame.Sumeru, "TURRET_OPERATOR.name")] =
                "Eremite Crossbow",
        };
}
