// <auto-generated>
//     GENERATED by tools/gen_teyvat_events.py from
//     docs/current/dossiers/content/event-faces/*.md
//     Do not edit by hand: `python tools/gen_teyvat_events.py --check`
//     fails on any drift, and the next run overwrites it.
// </auto-generated>

using System;
using System.Collections.Generic;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Events;

namespace KleeMod.Teyvat;

/// <summary>
/// THE DRESSED EVENTS' LOC ROWS, generated from the curated faces.
///
/// EVERY KEY IS THIS ARM'S OWN. A `LocTable.MergeWith` is GLOBAL and
/// overwrites, so a row whose key drifted onto a base event's family
/// would silently rewrite the shipped game's text -- and the `events`
/// table has no dressed-key trick to fall back on the way the monster
/// names do. Every key below is prefixed with a DRESSED `Id.Entry`,
/// which no base event has, and a pin asserts it.
///
/// AN OPTION KEY IS A PREFIX, NOT A STRING (EB-765). `EventOption`'s
/// constructor reads `GetOptionTitle(key)` and `GetOptionDescription(key)`
/// -- `key + ".title"` and `key + ".description"` -- and `GetIfExists`
/// answers NULL for an absent key, which `AddLocVars` then dereferences.
/// The generator writes both rows for every option, always.
/// </summary>
internal static partial class TeyvatLoc
{
    internal static readonly IReadOnlyDictionary<string, string> GeneratedEventRows =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // UnmarkedCrates (Mondstadt / ThisOrThat)
            ["UNMARKED_CRATES.title"] =
                "The Unmarked Crates",
            ["UNMARKED_CRATES.pages.INITIAL.description"] =
                "Two unlabeled crates sit on the Guild's back counter in Mondstadt, "
                + "hauled down from a wrecked supply cart in the Stormbearer "
                + "Mountains. Katheryne explains that the Guild cannot appraise cargo "
                + "it never logged, so the finder may claim exactly one. Whichever "
                + "you take, the other is sealed and sent to the vault unopened.",
            ["UNMARKED_CRATES.pages.INITIAL.options.PLAIN.title"] =
                "Pry the Iron-Banded Crate",
            ["UNMARKED_CRATES.pages.INITIAL.options.PLAIN.description"] =
                "The lid gives all at once and a rusted spring-catch snaps across "
                + "your knuckles. Beneath the straw: a commission purse nobody ever "
                + "collected. Lose 6 HP. Gain 57 Mora (Gold).",
            ["UNMARKED_CRATES.pages.INITIAL.options.ORNATE.title"] =
                "Take the Rattling Crate",
            ["UNMARKED_CRATES.pages.INITIAL.options.ORNATE.description"] =
                "Inside, wrapped in oilcloth, is a piece of adventuring gear worth "
                + "far more than the paperwork on it — and badly enough balanced that "
                + "you keep catching your own boot on it. Add Clumsy (curse) to your "
                + "Deck. Obtain a random Relic.",
            ["UNMARKED_CRATES.pages.PLAIN.description"] =
                "The lid gives all at once and a rusted spring-catch snaps across "
                + "your knuckles. Beneath the straw: a commission purse nobody ever "
                + "collected. Lose 6 HP. Gain 57 Mora (Gold).",
            ["UNMARKED_CRATES.pages.ORNATE.description"] =
                "Inside, wrapped in oilcloth, is a piece of adventuring gear worth "
                + "far more than the paperwork on it — and badly enough balanced that "
                + "you keep catching your own boot on it. Add Clumsy (curse) to your "
                + "Deck. Obtain a random Relic.",
            // SpringvaleCheeseCellar (Mondstadt / RoomFullOfCheese)
            ["SPRINGVALE_CHEESE_CELLAR.title"] =
                "The Springvale Cheese Cellar",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.description"] =
                "A collapsed stair below Springvale opens onto a dairy cellar the "
                + "Guild's commission board never got around to delisting. Wheels of "
                + "Mondstadt cheese sit rack on rack, gold-rinded and humming with "
                + "age, and the slip in your hand says only: inventory it. Behind the "
                + "furthest rack, something older than the racks is sweating brine.",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.options.GORGE.title"] =
                "Taste the Racks",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.options.GORGE.description"] =
                "Choose 2 of 8 random Common cards to add to your Deck. The eight "
                + "wheels offered are never duplicates.",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.options.SEARCH.title"] =
                "Haul Out the Back Wall",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.options.SEARCH.description"] =
                "Lose 14 HP to strained shoulders and spore-thick air. Obtain The "
                + "Anointed Wheel (The Chosen Cheese): at the end of combat, gain 1 "
                + "Max HP.",
            ["SPRINGVALE_CHEESE_CELLAR.pages.GORGE.selectionScreenPrompt"] =
                "Taste the Racks",
            ["SPRINGVALE_CHEESE_CELLAR.pages.GORGE.description"] =
                "Choose 2 of 8 random Common cards to add to your Deck. The eight "
                + "wheels offered are never duplicates.",
            ["SPRINGVALE_CHEESE_CELLAR.pages.SEARCH.description"] =
                "Lose 14 HP to strained shoulders and spore-thick air. Obtain The "
                + "Anointed Wheel (The Chosen Cheese): at the end of combat, gain 1 "
                + "Max HP.",
            ["SPRINGVALE_CHEESE_CELLAR.loss"] =
                "{character} was buried under the back wall of the "
                + "[gold]{event}[/gold].",
            // GuildsStandingCommissionAtCapeOath (Mondstadt / TheLegendsWereTrue)
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.title"] =
                "The Guild's Standing Commission at Cape Oath",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.description"] =
                "The Adventurers' Guild desk has kept a commission open for years "
                + "on the old sailor's tale of treasure under Cape Oath, and every "
                + "posting-board veteran assumes it's a joke played on new recruits. "
                + "A weathered chart in the receptionist's drawer says otherwise — "
                + "the coastline in it matches nothing on the current map. She offers "
                + "you the chart itself, no questions asked, or a faster way out if "
                + "the cliffs get the better of you.",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.options.NAB_THE_MAP.title"] =
                "Nab the Map",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.options.NAB_THE_MAP.description"] =
                "Receive the Spoils Map.",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.options.SLOWLY_FIND_AN_EXIT.title"] =
                "Slowly Find an Exit",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.options.SLOWLY_FIND_AN_EXIT.description"] =
                "Lose 8 HP. Procure 1 random Potion.",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.NAB_THE_MAP.description"] =
                "Receive the Spoils Map.",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.SLOWLY_FIND_AN_EXIT.description"] =
                "Lose 8 HP. Procure 1 random Potion.",
            // QingceLarder (Liyue / RoomFullOfCheese)
            ["QINGCE_LARDER.title"] =
                "The Qingce Larder",
            ["QINGCE_LARDER.pages.INITIAL.description"] =
                "A collapsed terrace wall below Qingce Village opens onto a "
                + "root-cellar the Feiyun Commerce Guild never finished inventorying "
                + "before the harvest season turned it over to the village instead. "
                + "Jars of pickled radish and aged tofu line the shelves, each one "
                + "labeled in a farmer's careful hand. Behind the last rack, "
                + "something has been fermenting far longer than the others, and it "
                + "smells like it knows you're there.",
            ["QINGCE_LARDER.pages.INITIAL.options.GORGE.title"] =
                "Gorge",
            ["QINGCE_LARDER.pages.INITIAL.options.GORGE.description"] =
                "Choose 2 of 8 random Common cards to add to your Deck. The eight "
                + "jars offered are never duplicates.",
            ["QINGCE_LARDER.pages.INITIAL.options.SEARCH.title"] =
                "Search",
            ["QINGCE_LARDER.pages.INITIAL.options.SEARCH.description"] =
                "Lose 14 HP. Obtain The Chosen Cheese (relic): at the end of "
                + "combat, gain 1 Max HP.",
            ["QINGCE_LARDER.pages.GORGE.selectionScreenPrompt"] =
                "Gorge",
            ["QINGCE_LARDER.pages.GORGE.description"] =
                "Choose 2 of 8 random Common cards to add to your Deck. The eight "
                + "jars offered are never duplicates.",
            ["QINGCE_LARDER.pages.SEARCH.description"] =
                "Lose 14 HP. Obtain The Chosen Cheese (relic): at the end of "
                + "combat, gain 1 Max HP.",
            // TalesOfGuyunWereTrue (Liyue / TheLegendsWereTrue)
            ["TALES_OF_GUYUN_WERE_TRUE.title"] =
                "The Tales of Guyun Were True",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.description"] =
                "The drowned hall under Guyun Stone Forest was supposed to be a "
                + "fisherman's tall tale, but the tide is out and the doorway is real "
                + "stone. Treasure Hoarders reached it first and left in a hurry: "
                + "overturned crates, a snuffed lantern, a lacquered chart pinned to "
                + "the wall with a knife. Your Guild commission said survey only. The "
                + "passage behind you is already taking water.",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title"] =
                "Nab the Chart",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.description"] =
                "Receive the Hoarders' spoils chart (Spoils Map).",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.options.SLOWLY_FIND_AN_EXIT.title"] =
                "Feel Your Way Out Slowly",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.options.SLOWLY_FIND_AN_EXIT.description"] =
                "Lose 8 HP scraping through the flooded crawlway. Procure 1 random "
                + "Potion from a cracked Hoarder crate.",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.NAB_THE_MAP.description"] =
                "Receive the Hoarders' spoils chart (Spoils Map).",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.SLOWLY_FIND_AN_EXIT.description"] =
                "Lose 8 HP scraping through the flooded crawlway. Procure 1 random "
                + "Potion from a cracked Hoarder crate.",
            // UnclaimedCratesAtFeiyunSlope (Liyue / ThisOrThat)
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.title"] =
                "The Unclaimed Crates at Feiyun Slope",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.description"] =
                "Two unlabeled crates sit on the Feiyun Slope loading dock, hauled "
                + "off a cargo junk whose manifest never named them. A dockhand "
                + "explains the Guild cannot log cargo it never contracted for, so "
                + "the finder may claim exactly one. Whichever you take, the other is "
                + "sealed and sent up to Liyue Harbor's lost-property office "
                + "unopened, per the standing charter — no argument entered into the "
                + "ledger either way.",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.options.PLAIN.title"] =
                "This",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.options.PLAIN.description"] =
                "Lose 6 HP. Gain 57 Gold.",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.options.ORNATE.title"] =
                "That",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.options.ORNATE.description"] =
                "Add Clumsy (curse) to your Deck. Obtain a random Relic.",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.PLAIN.description"] =
                "Lose 6 HP. Gain 57 Gold.",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.ORNATE.description"] =
                "Add Clumsy (curse) to your Deck. Obtain a random Relic.",
        };
}

/// <summary>
/// THE GENERATED TABLES the arm's two readers consult: the shape a
/// dressed event's mirror has, and the substitution the `PullNextEvent`
/// postfix makes. Both are generated from the same face files and the
/// same base-event index as the classes and the rows above, so the
/// three cannot disagree about what a dressing contains.
/// </summary>
internal static class TeyvatGeneratedEvents
{
    /// <summary>What a dressed event's mirror asks the loc table for:
    /// the option key names, in the base event's order, and the other
    /// page keys. Read by the headless pins, which check the key set
    /// against the merged rows without constructing a model.</summary>
    internal sealed record EventShape(
        string BaseEntry,
        string Mirror,
        IReadOnlyList<string> OptionKeys,
        IReadOnlyList<string> PageKeys,
        bool HasLossRow);

    /// <summary>Dressed event type -> its shape.</summary>
    internal static readonly IReadOnlyDictionary<Type, EventShape> Shapes =
        new Dictionary<Type, EventShape>
        {
            [typeof(Events.Mondstadt.UnmarkedCrates)] = new EventShape(
                "UNMARKED_CRATES", "ThisOrThatMirror",
                new[] { "PLAIN", "ORNATE" },
                new[] { "pages.PLAIN.description", "pages.ORNATE.description" },
                false),
            [typeof(Events.Mondstadt.SpringvaleCheeseCellar)] = new EventShape(
                "SPRINGVALE_CHEESE_CELLAR", "RoomFullOfCheeseMirror",
                new[] { "GORGE", "SEARCH" },
                new[] { "pages.GORGE.selectionScreenPrompt", "pages.GORGE.description", "pages.SEARCH.description" },
                true),
            [typeof(Events.Mondstadt.GuildsStandingCommissionAtCapeOath)] = new EventShape(
                "GUILDS_STANDING_COMMISSION_AT_CAPE_OATH", "TheLegendsWereTrueMirror",
                new[] { "NAB_THE_MAP", "SLOWLY_FIND_AN_EXIT" },
                new[] { "pages.NAB_THE_MAP.description", "pages.SLOWLY_FIND_AN_EXIT.description" },
                false),
            [typeof(Events.Liyue.QingceLarder)] = new EventShape(
                "QINGCE_LARDER", "RoomFullOfCheeseMirror",
                new[] { "GORGE", "SEARCH" },
                new[] { "pages.GORGE.selectionScreenPrompt", "pages.GORGE.description", "pages.SEARCH.description" },
                false),
            [typeof(Events.Liyue.TalesOfGuyunWereTrue)] = new EventShape(
                "TALES_OF_GUYUN_WERE_TRUE", "TheLegendsWereTrueMirror",
                new[] { "NAB_THE_MAP", "SLOWLY_FIND_AN_EXIT" },
                new[] { "pages.NAB_THE_MAP.description", "pages.SLOWLY_FIND_AN_EXIT.description" },
                false),
            [typeof(Events.Liyue.UnclaimedCratesAtFeiyunSlope)] = new EventShape(
                "UNCLAIMED_CRATES_AT_FEIYUN_SLOPE", "ThisOrThatMirror",
                new[] { "PLAIN", "ORNATE" },
                new[] { "pages.PLAIN.description", "pages.ORNATE.description" },
                false),
        };

    /// <summary>(dressing act entry, base event type) -> the dressed
    /// model that stands in for it at pull time. Consumed by
    /// `Patches/PullNextEventPatch`; see that file for why the
    /// substitution happens downstream of the shuffle.</summary>
    internal static readonly IReadOnlyDictionary<(string Dressing, Type BaseEvent), Func<EventModel>> Substitutions =
        new Dictionary<(string, Type), Func<EventModel>>
        {
            [(TeyvatFrame.Mondstadt, typeof(ThisOrThat))] =
                () => ModelDb.Event<Events.Mondstadt.UnmarkedCrates>(),
            [(TeyvatFrame.Mondstadt, typeof(RoomFullOfCheese))] =
                () => ModelDb.Event<Events.Mondstadt.SpringvaleCheeseCellar>(),
            [(TeyvatFrame.Mondstadt, typeof(TheLegendsWereTrue))] =
                () => ModelDb.Event<Events.Mondstadt.GuildsStandingCommissionAtCapeOath>(),
            [(TeyvatFrame.Liyue, typeof(RoomFullOfCheese))] =
                () => ModelDb.Event<Events.Liyue.QingceLarder>(),
            [(TeyvatFrame.Liyue, typeof(TheLegendsWereTrue))] =
                () => ModelDb.Event<Events.Liyue.TalesOfGuyunWereTrue>(),
            [(TeyvatFrame.Liyue, typeof(ThisOrThat))] =
                () => ModelDb.Event<Events.Liyue.UnclaimedCratesAtFeiyunSlope>(),
        };

    /// <summary>
    /// A dressed event's `Id.Entry` -> the image the default event layout
    /// draws for it until one of its own is supplied (EB-764).
    ///
    /// `EventModel.InitialPortraitPath` is `ImageHelper.GetImagePath(
    /// "events/" + Id.Entry.ToLowerInvariant() + ".png")` -- DERIVED from
    /// the id, `private`, and not virtual -- so a dressed event asks the
    /// pack for a path nothing produces and `NEventLayout.InitializeVisuals`
    /// threw `AssetLoadException` before the page was drawn. The value is the
    /// BASE event's own image, which is the same borrowing
    /// `TeyvatFrame.AssetAlias` makes for a dressing's backgrounds, and it
    /// retires the same way: `Patches/EventPortraitPatch` asks
    /// `ResourceLoader.Exists` of the DRESSED path first, so a real portrait
    /// dropped at `events/&lt;dressed entry&gt;.png` wins with no code change.
    ///
    /// GENERATED, so a dressed event cannot exist without a portrait row --
    /// which is exactly the shape EB-764 was.
    /// </summary>
    internal static readonly IReadOnlyDictionary<string, string> Portraits =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["UNMARKED_CRATES"] =
                "res://images/events/this_or_that.png",
            ["SPRINGVALE_CHEESE_CELLAR"] =
                "res://images/events/room_full_of_cheese.png",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH"] =
                "res://images/events/the_legends_were_true.png",
            ["QINGCE_LARDER"] =
                "res://images/events/room_full_of_cheese.png",
            ["TALES_OF_GUYUN_WERE_TRUE"] =
                "res://images/events/the_legends_were_true.png",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE"] =
                "res://images/events/this_or_that.png",
        };
}
