// <auto-generated>
//     GENERATED by tools/gen_teyvat_ancients.py from
//     docs/current/dossiers/content/ancient-faces.tsv
//     Do not edit by hand: `python tools/gen_teyvat_ancients.py --check`
//     fails on any drift, and the next run overwrites it.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Events;

namespace KleeMod.Teyvat.Ancients
{

    /// <summary>
    /// THE DRESSED ANCIENTS -- one body per (Ancient, face), R275.
    ///
    /// EACH ONE IS A NAME AND A BASE AND NOTHING ELSE, and that is the whole
    /// design. `MegaCrit.Sts2.Core.Models.Events`'s eight Ancients are the
    /// only unsealed events in the assembly,
    /// `AncientEventModel.DefineDialogues` and `AllPossibleOptions` are
    /// inherited untouched, and every string and every asset path the engine
    /// builds for an Ancient is derived from `Id.Entry` -- which
    /// `ModelDb.GetEntry` takes from THIS class's name. So the subclass
    /// re-keys the title, the epithet and all twenty-odd dialogue lines for
    /// free, and re-keys not one mechanic.
    /// </summary>
    internal static class TeyvatDressedAncientsDoc { }

    /// <summary>Alice -- the Fontaine face's Darv. Entry <c>ALICE_FONTAINE</c>.</summary>
    public sealed class AliceFontaine : Darv { }

    /// <summary>Alice -- the Inazuma face's Darv. Entry <c>ALICE_INAZUMA</c>.</summary>
    public sealed class AliceInazuma : Darv { }

    /// <summary>Alice -- the Natlan face's Darv. Entry <c>ALICE_NATLAN</c>.</summary>
    public sealed class AliceNatlan : Darv { }

    /// <summary>Alice -- the Sumeru face's Darv. Entry <c>ALICE_SUMERU</c>.</summary>
    public sealed class AliceSumeru : Darv { }

    /// <summary>Moon Carver -- the Liyue face's Neow. Entry <c>MOON_CARVER_LIYUE</c>.</summary>
    public sealed class MoonCarverLiyue : Neow { }

    /// <summary>Dvalin -- the Mondstadt face's Neow. Entry <c>DVALIN_MONDSTADT</c>.</summary>
    public sealed class DvalinMondstadt : Neow { }

    /// <summary>Egeria -- the Fontaine face's Nonupeipe. Entry <c>EGERIA_FONTAINE</c>.</summary>
    public sealed class EgeriaFontaine : Nonupeipe { }

    /// <summary>Greater Lord Rukkhadevata -- the Sumeru face's Nonupeipe. Entry <c>GREATER_LORD_RUKKHADEVATA_SUMERU</c>.</summary>
    public sealed class GreaterLordRukkhadevataSumeru : Nonupeipe { }

    /// <summary>the Sacred Sakura -- the Inazuma face's Orobas. Entry <c>THE_SACRED_SAKURA_INAZUMA</c>.</summary>
    public sealed class TheSacredSakuraInazuma : Orobas { }

    /// <summary>Xbalanque -- the Natlan face's Orobas. Entry <c>XBALANQUE_NATLAN</c>.</summary>
    public sealed class XbalanqueNatlan : Orobas { }

    /// <summary>Orobashi -- the Inazuma face's Pael. Entry <c>OROBASHI_INAZUMA</c>.</summary>
    public sealed class OrobashiInazuma : Pael { }

    /// <summary>Och-Kan -- the Natlan face's Pael. Entry <c>OCH_KAN_NATLAN</c>.</summary>
    public sealed class OchKanNatlan : Pael { }

    /// <summary>Elynas -- the Fontaine face's Tanx. Entry <c>ELYNAS_FONTAINE</c>.</summary>
    public sealed class ElynasFontaine : Tanx { }

    /// <summary>Apep -- the Sumeru face's Tanx. Entry <c>APEP_SUMERU</c>.</summary>
    public sealed class ApepSumeru : Tanx { }

    /// <summary>Ioroi -- the Inazuma face's Tezcatara. Entry <c>IOROI_INAZUMA</c>.</summary>
    public sealed class IoroiInazuma : Tezcatara { }

    /// <summary>Tezcatara -- the Natlan face's Tezcatara. Entry <c>TEZCATARA_NATLAN</c>.</summary>
    public sealed class TezcataraNatlan : Tezcatara { }

    /// <summary>Remus -- the Fontaine face's Vakuu. Entry <c>REMUS_FONTAINE</c>.</summary>
    public sealed class RemusFontaine : Vakuu { }

    /// <summary>King Deshret -- the Sumeru face's Vakuu. Entry <c>KING_DESHRET_SUMERU</c>.</summary>
    public sealed class KingDeshretSumeru : Vakuu { }

}


namespace KleeMod.Teyvat
{
    /// <summary>
    /// THE DRESSED ANCIENTS' TABLES -- what the face acts, the two patches and
    /// `TeyvatAncients.RowsFor` read. Pure data over TYPES and STRINGS, so the
    /// headless suite can exercise every one of them without a `ModelDb`.
    /// </summary>
    public static class TeyvatGeneratedAncients
    {
        /// <summary>
        /// THE FACES' OWN FLAT LOC ROWS, under the DRESSED `Id.Entry`, which no
        /// base Ancient has -- so a `LocTable.MergeWith`, which is global and
        /// overwrites, cannot reach the shipped game's text. A pin asserts it.
        ///
        /// NO OPTION ROW IS EVER IN HERE. An Ancient's boons are
        /// `RelicOption&lt;T&gt;()` and `EventOption.FromRelic` is
        /// `GetOptionTitle(key) ?? relic.Title`, so an absent row falls through
        /// to the relic's own; the generator has no path that writes one.
        /// </summary>
        public static readonly IReadOnlyDictionary<string, string> Rows =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["ALICE_FONTAINE.title"] =
                    "Alice",
                ["ALICE_FONTAINE.epithet"] =
                    "Author of the Teyvat Travel Guide",
                ["ALICE_INAZUMA.title"] =
                    "Alice",
                ["ALICE_INAZUMA.epithet"] =
                    "Author of the Teyvat Travel Guide",
                ["ALICE_NATLAN.title"] =
                    "Alice",
                ["ALICE_NATLAN.epithet"] =
                    "Author of the Teyvat Travel Guide",
                ["ALICE_SUMERU.title"] =
                    "Alice",
                ["ALICE_SUMERU.epithet"] =
                    "Author of the Teyvat Travel Guide",
                ["MOON_CARVER_LIYUE.title"] =
                    "Moon Carver",
                ["MOON_CARVER_LIYUE.epithet"] =
                    "Adeptus of Mt. Aocang",
                ["DVALIN_MONDSTADT.title"] =
                    "Dvalin",
                ["DVALIN_MONDSTADT.epithet"] =
                    "Dragon of the East",
                ["EGERIA_FONTAINE.title"] =
                    "Egeria",
                ["EGERIA_FONTAINE.epithet"] =
                    "The First Hydro Archon",
                ["GREATER_LORD_RUKKHADEVATA_SUMERU.title"] =
                    "Greater Lord Rukkhadevata",
                ["GREATER_LORD_RUKKHADEVATA_SUMERU.epithet"] =
                    "Dendro Archon of Old",
                ["THE_SACRED_SAKURA_INAZUMA.title"] =
                    "the Sacred Sakura",
                ["THE_SACRED_SAKURA_INAZUMA.epithet"] =
                    "Guardian Tree of Narukami",
                ["XBALANQUE_NATLAN.title"] =
                    "Xbalanque",
                ["XBALANQUE_NATLAN.epithet"] =
                    "First of the Pyro Archons",
                ["OROBASHI_INAZUMA.title"] =
                    "Orobashi",
                ["OROBASHI_INAZUMA.epithet"] =
                    "Serpent God of Watatsumi",
                ["OCH_KAN_NATLAN.title"] =
                    "Och-Kan",
                ["OCH_KAN_NATLAN.epithet"] =
                    "The Dragonlord",
                ["ELYNAS_FONTAINE.title"] =
                    "Elynas",
                ["ELYNAS_FONTAINE.epithet"] =
                    "The Sleeping Giant",
                ["APEP_SUMERU.title"] =
                    "Apep",
                ["APEP_SUMERU.epithet"] =
                    "Dendro Dragon of the Desert",
                ["IOROI_INAZUMA.title"] =
                    "Ioroi",
                ["IOROI_INAZUMA.epithet"] =
                    "Tanuki Chief of Chinju Forest",
                ["TEZCATARA_NATLAN.title"] =
                    "Tezcatara",
                ["TEZCATARA_NATLAN.epithet"] =
                    "A Wayob of the Night Kingdom",
                ["REMUS_FONTAINE.title"] =
                    "Remus",
                ["REMUS_FONTAINE.epithet"] =
                    "King of Remuria",
                ["KING_DESHRET_SUMERU.title"] =
                    "King Deshret",
                ["KING_DESHRET_SUMERU.epithet"] =
                    "Lord of the Red Sands",
            };

        /// <summary>
        /// ONE DRESSED DIALOGUE LINE, BY COORDINATE -- the one place this
        /// surface is not a dictionary.
        ///
        /// A dialogue line's key carries an `r` suffix when the dialogue is in
        /// the repeating pool (`AncientDialogue.PopulateLines` derives
        /// `IsRepeating` from the key's presence), and whether a given base
        /// dialogue is repeating is a fact about the shipped loc PACK, not
        /// about any C# this repo can read. So a dressed line is carried as
        /// its coordinates and `TeyvatAncients.RowsFor` resolves the suffix
        /// against the live table at merge time. Empty today, by R275: the
        /// words are a second bill.
        /// </summary>
        public readonly record struct AncientLine(
            string DressedEntry,
            string CharEntry,
            int DialogueIndex,
            int LineIndex,
            bool AncientSpeaks,
            string Text);

        /// <inheritdoc cref="AncientLine"/>
        public static readonly IReadOnlyList<AncientLine> Lines =
            new List<AncientLine>
            {
                new AncientLine("ALICE_FONTAINE", "firstVisitEver", 0, 0, true, "Oh, a climber! Let me find my notes. I have been meaning to add a chapter on this place, and you look like the kind of footnote that survives."),
                new AncientLine("ALICE_FONTAINE", "ANY", 0, 0, true, "If you meet a small girl with a backpack full of bombs, tell her Mother says to do her homework. Now, what does the Travel Guide recommend for someone in your position?"),
                new AncientLine("ALICE_FONTAINE", "ANY", 1, 0, true, "The Fontaine chapter is mostly notes on the courthouse, which I recommend viewing from outside. Choose from the parts that got me arrested."),
                new AncientLine("ALICE_INAZUMA", "firstVisitEver", 0, 0, true, "Oh, a climber! Let me find my notes. I have been meaning to add a chapter on this place, and you look like the kind of footnote that survives."),
                new AncientLine("ALICE_INAZUMA", "ANY", 0, 0, true, "If you meet a small girl with a backpack full of bombs, tell her Mother says to do her homework. Now, what does the Travel Guide recommend for someone in your position?"),
                new AncientLine("ALICE_INAZUMA", "ANY", 1, 0, true, "I was banned from Inazuma once. Twice, actually. The chapter is excellent regardless. Pick a page."),
                new AncientLine("ALICE_NATLAN", "firstVisitEver", 0, 0, true, "Oh, a climber! Let me find my notes. I have been meaning to add a chapter on this place, and you look like the kind of footnote that survives."),
                new AncientLine("ALICE_NATLAN", "ANY", 0, 0, true, "If you meet a small girl with a backpack full of bombs, tell her Mother says to do her homework. Now, what does the Travel Guide recommend for someone in your position?"),
                new AncientLine("ALICE_NATLAN", "ANY", 1, 0, true, "The Natlan chapter took three rewrites and one volcano. Take something from it; the volcano cannot have been for nothing."),
                new AncientLine("ALICE_SUMERU", "firstVisitEver", 0, 0, true, "Oh, a climber! Let me find my notes. I have been meaning to add a chapter on this place, and you look like the kind of footnote that survives."),
                new AncientLine("ALICE_SUMERU", "ANY", 0, 0, true, "If you meet a small girl with a backpack full of bombs, tell her Mother says to do her homework. Now, what does the Travel Guide recommend for someone in your position?"),
                new AncientLine("ALICE_SUMERU", "ANY", 1, 0, true, "The Akademiya banned the Travel Guide, which doubled its sales. Here is a page they especially hated."),
                new AncientLine("MOON_CARVER_LIYUE", "firstVisitEver", 0, 0, true, "Hm. A mortal at the foot of the mountain, and the tea not yet cool. Very well. Choose your provision."),
                new AncientLine("MOON_CARVER_LIYUE", "ANY", 0, 0, true, "The adepti keep a contract with Liyue, and I keep mine with any who climb. Choose, then."),
                new AncientLine("MOON_CARVER_LIYUE", "ANY", 1, 0, true, "Mt. Aocang has watched a thousand ascents. Most were foolish. Some were not. Which are you?"),
                new AncientLine("MOON_CARVER_LIYUE", "ANY", 2, 0, true, "Do not thank me. A gift given at the foot of a climb is only the mountain's toll paid forward."),
                new AncientLine("MOON_CARVER_LIYUE", "ANY", 3, 0, true, "I have sat still for centuries and learned little. Perhaps motion teaches better. Go and see."),
                new AncientLine("MOON_CARVER_LIYUE", "ANY", 4, 0, true, "Rex Lapis is gone, and still the contracts hold. Here is mine: one gift, then the road."),
                new AncientLine("DVALIN_MONDSTADT", "firstVisitEver", 0, 0, true, "You carry the scent of the wind that woke me. Take what a wounded sky can spare, and go."),
                new AncientLine("DVALIN_MONDSTADT", "ANY", 0, 0, true, "The storm has passed over Mondstadt, and I remain. Choose, traveler, before the wind changes."),
                new AncientLine("DVALIN_MONDSTADT", "ANY", 1, 0, true, "Once I feared every hand that reached for me. Reach anyway. The choice is yours to make."),
                new AncientLine("DVALIN_MONDSTADT", "ANY", 2, 0, true, "The Spire is not the sky, but it climbs the same way. Take your first breath of it here."),
                new AncientLine("DVALIN_MONDSTADT", "ANY", 3, 0, true, "I have lain beneath Stormterror's Lair long enough to know a beginning when it walks in."),
                new AncientLine("DVALIN_MONDSTADT", "ANY", 4, 0, true, "A dragon's gift is a small wind at your back. It is all I have, and it is enough."),
                new AncientLine("EGERIA_FONTAINE", "firstVisitEver", 0, 0, true, "Every river in Fontaine began as a gift I was not permitted to give. I give it anyway. Take your share."),
                new AncientLine("EGERIA_FONTAINE", "ANY", 0, 0, true, "Abundance was my sin and my reason. Let some of it fall on you before the judgment falls on me."),
                new AncientLine("EGERIA_FONTAINE", "ANY", 1, 0, true, "My Melusines were born from a giant's tears. From what shall your fortune be born? Choose."),
                new AncientLine("GREATER_LORD_RUKKHADEVATA_SUMERU", "firstVisitEver", 0, 0, true, "The forest remembers what the city forgot. Come. What grows here grows for everyone who climbs."),
                new AncientLine("GREATER_LORD_RUKKHADEVATA_SUMERU", "ANY", 0, 0, true, "Wisdom is not withheld, only offered to those who arrive. You have arrived. Take what the branches carry."),
                new AncientLine("GREATER_LORD_RUKKHADEVATA_SUMERU", "ANY", 1, 0, true, "I gave away everything, even my name, so the forest might keep growing. One more gift will not hurt."),
                new AncientLine("THE_SACRED_SAKURA_INAZUMA", "firstVisitEver", 0, 0, true, "The petals fall and I remain. Lay your burden at my roots; what you hold will leave stronger than it came."),
                new AncientLine("THE_SACRED_SAKURA_INAZUMA", "ANY", 0, 0, true, "The shrine is quiet tonight. Set down what you carry, and let the roots refine it."),
                new AncientLine("THE_SACRED_SAKURA_INAZUMA", "ANY", 1, 0, true, "A blade is polished a thousand times before it is trusted. Your thousand times begin here."),
                new AncientLine("XBALANQUE_NATLAN", "firstVisitEver", 0, 0, true, "The flame does not care what you were. It cares what you become. Show me what you carry, and I will make it burn hotter."),
                new AncientLine("XBALANQUE_NATLAN", "ANY", 0, 0, true, "A warrior who stops sharpening is already dead. Give me your blade."),
                new AncientLine("XBALANQUE_NATLAN", "ANY", 1, 0, true, "Natlan was not built by the strong. It was built by those who kept fighting after strength ran out."),
                new AncientLine("OROBASHI_INAZUMA", "firstVisitEver", 0, 0, true, "I chose my ending long ago, beneath Yashiori. Whatever remains of me is yours, if you can carry it."),
                new AncientLine("OROBASHI_INAZUMA", "ANY", 0, 0, true, "The Tatarigami whisper that a god should keep what is his. I never listened. Take what you need."),
                new AncientLine("OROBASHI_INAZUMA", "ANY", 1, 0, true, "Watatsumi still eats because I stopped breathing. Let a little of that bargain feed you as well."),
                new AncientLine("OCH_KAN_NATLAN", "firstVisitEver", 0, 0, true, "The Night Kingdom is claiming me, piece by piece. Before it takes the last, let me give some of it to you."),
                new AncientLine("OCH_KAN_NATLAN", "ANY", 0, 0, true, "A dragon does not die all at once. Take a piece of me, then, and make it count."),
                new AncientLine("OCH_KAN_NATLAN", "ANY", 1, 0, true, "My scales bought Natlan its dawn. One more will buy you yours."),
                new AncientLine("ELYNAS_FONTAINE", "firstVisitEver", 0, 0, true, "I dreamed of the sea before Fontaine had a name. Come, little one. The dreaming body has strength to spare."),
                new AncientLine("ELYNAS_FONTAINE", "ANY", 0, 0, true, "The Melusines grew from my wounds. So can you. Take from me, and be whole."),
                new AncientLine("ELYNAS_FONTAINE", "ANY", 1, 0, true, "They tell me I fell from the sky. I only remember the ground, and the small ones who tended it. Let me tend you."),
                new AncientLine("APEP_SUMERU", "firstVisitEver", 0, 0, true, "The sands have swallowed kingdoms, and I have swallowed the sands. What is one more mortal, taken in and returned stronger?"),
                new AncientLine("APEP_SUMERU", "ANY", 0, 0, true, "Enter, mortal. Nothing that passes through me leaves unchanged."),
                new AncientLine("APEP_SUMERU", "ANY", 1, 0, true, "Deshret tried to build a paradise on my back. You want only a boon. That much I can grant."),
                new AncientLine("IOROI_INAZUMA", "firstVisitEver", 0, 0, true, "Ha! A guest who did not get lost in my forest. That deserves a drink. Or a meal. Or both. Pick."),
                new AncientLine("IOROI_INAZUMA", "ANY", 0, 0, true, "The kitsune host with ceremony. We tanuki host with sake. Choose whichever you find on the table."),
                new AncientLine("IOROI_INAZUMA", "ANY", 1, 0, true, "Nothing in Chinju Forest is what it seems, except the food. The food is real. Eat."),
                new AncientLine("TEZCATARA_NATLAN", "firstVisitEver", 0, 0, true, "Sit. Eat. The Night Kingdom has long tables and few guests, and you look like one who forgets to rest."),
                new AncientLine("TEZCATARA_NATLAN", "ANY", 0, 0, true, "Hospitality is the oldest law of the tribes. Take a seat by the fire, and take something for the road."),
                new AncientLine("TEZCATARA_NATLAN", "ANY", 1, 0, true, "The living pass through the Night Kingdom too quickly to taste anything. You will not make that mistake."),
                new AncientLine("REMUS_FONTAINE", "firstVisitEver", 0, 0, true, "Every gift I gave Remuria carried a debt. None of them refused. Will you?"),
                new AncientLine("REMUS_FONTAINE", "ANY", 0, 0, true, "Power arrives with its price already written. Read the terms, then sign."),
                new AncientLine("REMUS_FONTAINE", "ANY", 1, 0, true, "I raised a golden city on borrowed harmony, and the sea collected. Choose carefully what you borrow."),
                new AncientLine("REMUS_FONTAINE", "ANY", 2, 0, true, "The symphony was worth the drowning. I still believe that. Perhaps you will believe it too."),
                new AncientLine("KING_DESHRET_SUMERU", "firstVisitEver", 0, 0, true, "I sought forbidden knowledge and paid for it with my kingdom. Take a smaller lesson. It still costs."),
                new AncientLine("KING_DESHRET_SUMERU", "ANY", 0, 0, true, "The desert keeps every bargain. So do I. Choose what you will give up."),
                new AncientLine("KING_DESHRET_SUMERU", "ANY", 1, 0, true, "Gurabad, Ay-Khanoum, Sabzeruz. Names of things I bought too dearly. Buy something smaller from me."),
                new AncientLine("KING_DESHRET_SUMERU", "ANY", 2, 0, true, "Knowledge is never free. The Eremites learned that from my sands. You will learn it here."),
            };

        /// <summary>Dressed `Id.Entry` -> the base Ancient's `Id.Entry`. The
        /// picture patch's fall-back table and the loc ALIAS pass both read
        /// this, so a dressed body cannot exist in one and not the other.
        /// </summary>
        public static readonly IReadOnlyDictionary<string, string> BaseEntries =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["ALICE_FONTAINE"] = "DARV",
                ["ALICE_INAZUMA"] = "DARV",
                ["ALICE_NATLAN"] = "DARV",
                ["ALICE_SUMERU"] = "DARV",
                ["MOON_CARVER_LIYUE"] = "NEOW",
                ["DVALIN_MONDSTADT"] = "NEOW",
                ["EGERIA_FONTAINE"] = "NONUPEIPE",
                ["GREATER_LORD_RUKKHADEVATA_SUMERU"] = "NONUPEIPE",
                ["THE_SACRED_SAKURA_INAZUMA"] = "OROBAS",
                ["XBALANQUE_NATLAN"] = "OROBAS",
                ["OROBASHI_INAZUMA"] = "PAEL",
                ["OCH_KAN_NATLAN"] = "PAEL",
                ["ELYNAS_FONTAINE"] = "TANX",
                ["APEP_SUMERU"] = "TANX",
                ["IOROI_INAZUMA"] = "TEZCATARA",
                ["TEZCATARA_NATLAN"] = "TEZCATARA",
                ["REMUS_FONTAINE"] = "VAKUU",
                ["KING_DESHRET_SUMERU"] = "VAKUU",
            };

        /// <summary>
        /// (face, base Ancient type) -> the dressed instance. `Dress` below is
        /// the only reader; it is a table rather than a switch so a pin can
        /// count it.
        /// </summary>
        public static readonly
            IReadOnlyDictionary<(string Face, Type BaseAncient),
                                Func<AncientEventModel>> Dressings =
            new Dictionary<(string, Type), Func<AncientEventModel>>
            {
                [("FONTAINE", typeof(Darv))] =
                    () => ModelDb.AncientEvent<Ancients.AliceFontaine>(),
                [("INAZUMA", typeof(Darv))] =
                    () => ModelDb.AncientEvent<Ancients.AliceInazuma>(),
                [("NATLAN", typeof(Darv))] =
                    () => ModelDb.AncientEvent<Ancients.AliceNatlan>(),
                [("SUMERU", typeof(Darv))] =
                    () => ModelDb.AncientEvent<Ancients.AliceSumeru>(),
                [("LIYUE", typeof(Neow))] =
                    () => ModelDb.AncientEvent<Ancients.MoonCarverLiyue>(),
                [("MONDSTADT", typeof(Neow))] =
                    () => ModelDb.AncientEvent<Ancients.DvalinMondstadt>(),
                [("FONTAINE", typeof(Nonupeipe))] =
                    () => ModelDb.AncientEvent<Ancients.EgeriaFontaine>(),
                [("SUMERU", typeof(Nonupeipe))] =
                    () => ModelDb.AncientEvent<Ancients.GreaterLordRukkhadevataSumeru>(),
                [("INAZUMA", typeof(Orobas))] =
                    () => ModelDb.AncientEvent<Ancients.TheSacredSakuraInazuma>(),
                [("NATLAN", typeof(Orobas))] =
                    () => ModelDb.AncientEvent<Ancients.XbalanqueNatlan>(),
                [("INAZUMA", typeof(Pael))] =
                    () => ModelDb.AncientEvent<Ancients.OrobashiInazuma>(),
                [("NATLAN", typeof(Pael))] =
                    () => ModelDb.AncientEvent<Ancients.OchKanNatlan>(),
                [("FONTAINE", typeof(Tanx))] =
                    () => ModelDb.AncientEvent<Ancients.ElynasFontaine>(),
                [("SUMERU", typeof(Tanx))] =
                    () => ModelDb.AncientEvent<Ancients.ApepSumeru>(),
                [("INAZUMA", typeof(Tezcatara))] =
                    () => ModelDb.AncientEvent<Ancients.IoroiInazuma>(),
                [("NATLAN", typeof(Tezcatara))] =
                    () => ModelDb.AncientEvent<Ancients.TezcataraNatlan>(),
                [("FONTAINE", typeof(Vakuu))] =
                    () => ModelDb.AncientEvent<Ancients.RemusFontaine>(),
                [("SUMERU", typeof(Vakuu))] =
                    () => ModelDb.AncientEvent<Ancients.KingDeshretSumeru>(),
            };

        /// <summary>
        /// face -> every dressed entry that face can show, the act's own pool
        /// and the shared Ancients together. The pins read this; nothing at
        /// runtime does.
        /// </summary>
        public static readonly IReadOnlyDictionary<string, IReadOnlyList<string>>
            FacePools = new Dictionary<string, IReadOnlyList<string>>(
                StringComparer.Ordinal)
            {
                ["MONDSTADT"] = new[] { "DVALIN_MONDSTADT" },
                ["LIYUE"] = new[] { "MOON_CARVER_LIYUE" },
                ["NATLAN"] = new[] { "ALICE_NATLAN", "XBALANQUE_NATLAN", "OCH_KAN_NATLAN", "TEZCATARA_NATLAN" },
                ["INAZUMA"] = new[] { "ALICE_INAZUMA", "THE_SACRED_SAKURA_INAZUMA", "OROBASHI_INAZUMA", "IOROI_INAZUMA" },
                ["FONTAINE"] = new[] { "ALICE_FONTAINE", "EGERIA_FONTAINE", "ELYNAS_FONTAINE", "REMUS_FONTAINE" },
                ["SUMERU"] = new[] { "ALICE_SUMERU", "GREATER_LORD_RUKKHADEVATA_SUMERU", "APEP_SUMERU", "KING_DESHRET_SUMERU" },
            };

        /// <summary>
        /// THE ONE RUNTIME READER. Every base Ancient in `source` is swapped
        /// for this face's dressed body; one with no dressing is passed
        /// through unchanged.
        ///
        /// IT MAPS, IT DOES NOT FILTER, and that is the whole safety argument
        /// for the pools. A face act answers `AllAncients` and
        /// `GetUnlockedAncients` by handing the BASE act's own answer through
        /// here, so the length is equal by construction, the order is the base
        /// act's order, and every epoch filter the base act applies
        /// (`Hive.GetUnlockedAncients` removes Orobas behind `OrobasEpoch`)
        /// still applies -- the dressing is downstream of it. The same call
        /// serves `SetSharedAncientSubset`, which is how Darv becomes Alice
        /// without touching `ModelDb.AllSharedAncients` or the up-front rng
        /// draws `RunManager.GenerateRooms` spends dealing him out.
        ///
        /// WITH THE ARM OFF IT IS THE IDENTITY. An undressed run reaches
        /// exactly the objects it reached before.
        /// </summary>
        public static IEnumerable<AncientEventModel> Dress(
            string face, IEnumerable<AncientEventModel> source)
        {
            if (!TeyvatFrame.Enabled || source == null)
            {
                return source;
            }

            return source.Select(a =>
                a != null
                && Dressings.TryGetValue((face, a.GetType()), out var make)
                    ? make()
                    : a);
        }
    }
}
