// <auto-generated>
//     GENERATED by tools/gen_teyvat_events.py from
//     docs/current/dossiers/content/event-faces/*.md
//     Do not edit by hand: `python tools/gen_teyvat_events.py --check`
//     fails on any drift, and the next run overwrites it.
// </auto-generated>

using System;
using System.Collections.Generic;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Events;

namespace KleeMod.Teyvat;

/// <summary>
/// THE DRESSED EVENTS' LOC ROWS, generated from the curated faces.
///
/// EVERY KEY IS THIS ARM'S OWN. A `LocTable.MergeWith` is GLOBAL and
/// overwrites, so a row whose key drifted onto a base event's family
/// would silently rewrite the shipped game's text -- and the `events`
/// table has no dressed-key trick to fall back on the way the monster
/// names do. Every key below is prefixed with a DRESSED `Id.Entry`,
/// which no base event has, and a pin asserts it.
///
/// AN OPTION KEY IS A PREFIX, NOT A STRING (EB-765). `EventOption`'s
/// constructor reads `GetOptionTitle(key)` and `GetOptionDescription(key)`
/// -- `key + ".title"` and `key + ".description"` -- and `GetIfExists`
/// answers NULL for an absent key, which `AddLocVars` then dereferences.
/// The generator writes both rows for every option, always.
/// </summary>
internal static partial class TeyvatLoc
{
    internal static readonly IReadOnlyDictionary<string, string> GeneratedEventRows =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // GuildDesksReturnedCopy (Mondstadt / SelfHelpBook)
            ["GUILD_DESKS_RETURNED_COPY.title"] =
                "The Guild Desk's Returned Copy",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.description"] =
                "At the Adventurers' Guild desk in Mondstadt City, a dog-eared "
                + "self-improvement pamphlet has cycled through the returns bin for "
                + "three seasons running, its spine held together with "
                + "commission-board tape. The receptionist has annotated every margin "
                + "in a hand you recognize as Katheryne's, complete with a delisting "
                + "notice for the chapter on grappling technique. She slides it "
                + "across the counter without looking up. \"Read what applies. Return "
                + "what doesn't.\"",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_THE_BACK.title"] =
                "Read the Back",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_THE_BACK.description"] =
                "Choose an Attack to Enchant with Sharp 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_PASSAGE.title"] =
                "Read a Random Passage",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_PASSAGE.description"] =
                "Choose a Skill to Enchant with Nimble 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_ENTIRE_BOOK.title"] =
                "Read the Entire Book",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_ENTIRE_BOOK.description"] =
                "Choose a Power to Enchant with Swift 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.NO_OPTIONS.title"] =
                "Move On",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.NO_OPTIONS.description"] =
                "Nothing happens.",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_THE_BACK_LOCKED.title"] =
                "Read the Back",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_THE_BACK_LOCKED.description"] =
                "Choose an Attack to Enchant with Sharp 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_PASSAGE_LOCKED.title"] =
                "Read a Random Passage",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_PASSAGE_LOCKED.description"] =
                "Choose a Skill to Enchant with Nimble 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_ENTIRE_BOOK_LOCKED.title"] =
                "Read the Entire Book",
            ["GUILD_DESKS_RETURNED_COPY.pages.INITIAL.options.READ_ENTIRE_BOOK_LOCKED.description"] =
                "Choose a Power to Enchant with Swift 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.READ_THE_BACK.description"] =
                "Choose an Attack to Enchant with Sharp 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.READ_PASSAGE.description"] =
                "Choose a Skill to Enchant with Nimble 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.READ_ENTIRE_BOOK.description"] =
                "Choose a Power to Enchant with Swift 2.",
            ["GUILD_DESKS_RETURNED_COPY.pages.NO_OPTIONS.description"] =
                "Nothing happens.",
            // CutRopeBridgeAboveCiderLake (Mondstadt / SlipperyBridge)
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.title"] =
                "The Cut Rope Bridge Above Cider Lake",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.INITIAL.description"] =
                "The rope bridge below Springvale sways badly enough that a Knights "
                + "of Favonius patrol has roped off both ends and posted a warning "
                + "plank. The duty Knight says regulation calls for a full unload "
                + "before crossing — courtesy says she'll let you pick what goes over "
                + "the rail first. Below, Cider Lake is a long way down, and she is "
                + "not in a hurry.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.INITIAL.options.OVERCOME.title"] =
                "Overcome",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.INITIAL.options.OVERCOME.description"] =
                "The specific card named is removed from your deck.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.INITIAL.options.HOLD_ON_0.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.INITIAL.options.HOLD_ON_0.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_0.options.HOLD_ON_1.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_0.options.HOLD_ON_1.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_1.options.HOLD_ON_2.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_1.options.HOLD_ON_2.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_2.options.HOLD_ON_3.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_2.options.HOLD_ON_3.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_3.options.HOLD_ON_4.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_3.options.HOLD_ON_4.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_4.options.HOLD_ON_5.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_4.options.HOLD_ON_5.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_5.options.HOLD_ON_6.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_5.options.HOLD_ON_6.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_6.options.HOLD_ON_LOOP.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_6.options.HOLD_ON_LOOP.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_LOOP.options.HOLD_ON_LOOP.title"] =
                "Hold On",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_LOOP.options.HOLD_ON_LOOP.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.OVERCOME.description"] =
                "The specific card named is removed from your deck.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_0.description"] =
                "Lose 3 HP. The card in the above option is randomized.",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_1.description"] =
                "",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_2.description"] =
                "",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_3.description"] =
                "",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_4.description"] =
                "",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_5.description"] =
                "",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_6.description"] =
                "",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE.pages.HOLD_ON_LOOP.description"] =
                "",
            // UnmarkedCrates (Mondstadt / ThisOrThat)
            ["UNMARKED_CRATES.title"] =
                "The Unmarked Crates",
            ["UNMARKED_CRATES.pages.INITIAL.description"] =
                "Two unlabeled crates sit on the Guild's back counter in Mondstadt, "
                + "hauled down from a wrecked supply cart in the Stormbearer "
                + "Mountains. Katheryne explains that the Guild cannot appraise cargo "
                + "it never logged, so the finder may claim exactly one. Whichever "
                + "you take, the other is sealed and sent to the vault unopened.",
            ["UNMARKED_CRATES.pages.INITIAL.options.PLAIN.title"] =
                "Pry the Iron-Banded Crate",
            ["UNMARKED_CRATES.pages.INITIAL.options.PLAIN.description"] =
                "The lid gives all at once and a rusted spring-catch snaps across "
                + "your knuckles. Beneath the straw: a commission purse nobody ever "
                + "collected. Lose 6 HP. Gain 57 Mora (Gold).",
            ["UNMARKED_CRATES.pages.INITIAL.options.ORNATE.title"] =
                "Take the Rattling Crate",
            ["UNMARKED_CRATES.pages.INITIAL.options.ORNATE.description"] =
                "Inside, wrapped in oilcloth, is a piece of adventuring gear worth "
                + "far more than the paperwork on it — and badly enough balanced that "
                + "you keep catching your own boot on it. Add Clumsy (curse) to your "
                + "Deck. Obtain a random Relic.",
            ["UNMARKED_CRATES.pages.PLAIN.description"] =
                "The lid gives all at once and a rusted spring-catch snaps across "
                + "your knuckles. Beneath the straw: a commission purse nobody ever "
                + "collected. Lose 6 HP. Gain 57 Mora (Gold).",
            ["UNMARKED_CRATES.pages.ORNATE.description"] =
                "Inside, wrapped in oilcloth, is a piece of adventuring gear worth "
                + "far more than the paperwork on it — and badly enough balanced that "
                + "you keep catching your own boot on it. Add Clumsy (curse) to your "
                + "Deck. Obtain a random Relic.",
            // WanderingCask (Mondstadt / AromaOfChaos)
            ["WANDERING_CASK.title"] =
                "The Wandering Cask",
            ["WANDERING_CASK.pages.INITIAL.description"] =
                "In the cellars beneath Dawn Winery, a Knights of Favonius "
                + "quartermaster shows you a cask mislabeled two harvests ago. "
                + "Whatever grew inside is no longer Dandelion Wine; the vintner is "
                + "delighted, and the Knight very much is not. \"Broach it and see "
                + "what it became,\" the vintner offers. The quartermaster taps the "
                + "ledger instead: \"Or we do it properly, to the notes as written.\"",
            ["WANDERING_CASK.pages.INITIAL.options.LET_GO.title"] =
                "Broach the Wild Cask",
            ["WANDERING_CASK.pages.INITIAL.options.LET_GO.description"] =
                "Transform a card in your Deck.",
            ["WANDERING_CASK.pages.INITIAL.options.MAINTAIN_CONTROL.title"] =
                "Follow the Vintner's Notes",
            ["WANDERING_CASK.pages.INITIAL.options.MAINTAIN_CONTROL.description"] =
                "Upgrade a card in your Deck.",
            ["WANDERING_CASK.pages.LET_GO.description"] =
                "Transform a card in your Deck.",
            ["WANDERING_CASK.pages.MAINTAIN_CONTROL.description"] =
                "Upgrade a card in your Deck.",
            // StormTouchedShardAtStormterrorsLair (Mondstadt / BrainLeech)
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.title"] =
                "The Storm-Touched Shard at Stormterror's Lair",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.pages.INITIAL.description"] =
                "At the scarred rim of Stormterror's Lair, a shard of black "
                + "wind-crystal is still humming with borrowed memory. Before the "
                + "Knights' scouting patrol can rope it off, it fastens itself "
                + "against your ear and starts reciting something that isn't quite "
                + "draconic and isn't quite language. The duty Knight logs the "
                + "incident and does not offer to help. \"Regulations say I note the "
                + "time. Courtesy says I warn you it bites on the way out.\"",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.pages.INITIAL.options.SHARE_KNOWLEDGE.title"] =
                "Share Knowledge",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.pages.INITIAL.options.SHARE_KNOWLEDGE.description"] =
                "Stand still and let the lesson finish. Choose 1 of 5 random cards "
                + "to add to your deck.",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.pages.INITIAL.options.RIP.title"] =
                "Rip the Leech Off",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.pages.INITIAL.options.RIP.description"] =
                "You tear it free with a strip of ear. Lose 5 HP. Gain a Colorless "
                + "2 card reward — two loose companion (Colorless) cards salvaged "
                + "from what it was still transmitting.",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.pages.RIP.description"] =
                "You tear it free with a strip of ear. Lose 5 HP. Gain a Colorless "
                + "2 card reward — two loose companion (Colorless) cards salvaged "
                + "from what it was still transmitting.",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.pages.SHARE_KNOWLEDGE.selectionScreenPrompt"] =
                "Share Knowledge",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR.pages.SHARE_KNOWLEDGE.description"] =
                "Stand still and let the lesson finish. Choose 1 of 5 random cards "
                + "to add to your deck.",
            // WindfalconsRoost (Mondstadt / ByrdonisNest)
            ["WINDFALCONS_ROOST.title"] =
                "The Windfalcon's Roost",
            ["WINDFALCONS_ROOST.pages.INITIAL.description"] =
                "Stormbearer Point, where the wind never quite sets down. A Guild "
                + "scout walks you up a shale ledge to a nest of driftwood and torn "
                + "sailcloth — a Falcon of the West's, by the span of it — and inside "
                + "sits one pale egg as tall as your knee. The mother is out over "
                + "Falcon Coast, circling wide. You have roughly as long as it takes "
                + "her to turn.",
            ["WINDFALCONS_ROOST.pages.INITIAL.options.EAT.title"] =
                "Crack It Over the Fire",
            ["WINDFALCONS_ROOST.pages.INITIAL.options.EAT.description"] =
                "Gain 7 Max HP.",
            ["WINDFALCONS_ROOST.pages.INITIAL.options.TAKE.title"] =
                "Bundle It Into Your Pack",
            ["WINDFALCONS_ROOST.pages.INITIAL.options.TAKE.description"] =
                "Add Windfalcon Egg (Byrdonis Egg) to deck.",
            ["WINDFALCONS_ROOST.pages.EAT.description"] =
                "Gain 7 Max HP.",
            ["WINDFALCONS_ROOST.pages.TAKE.description"] =
                "Add Windfalcon Egg (Byrdonis Egg) to deck.",
            // BrambleLineBelowWolvendom (Mondstadt / DenseVegetation)
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.title"] =
                "The Bramble Line Below Wolvendom",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.INITIAL.description"] =
                "The Knights' patrol trail past Wolvendom has gone to bramble since "
                + "the wolves reclaimed the ridge, and the duty Knight will not swear "
                + "to what is on the other side. She offers two regulations: push "
                + "through at your own risk, or make camp and let her post a watch — "
                + "though something is already moving in the wet undergrowth nearby.",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.INITIAL.options.TRUDGE_ON.title"] =
                "Trudge On",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.INITIAL.options.TRUDGE_ON.description"] =
                "One of the following is randomly offered: a bramble stand snaps "
                + "back and takes something with it (Remove a card from your Deck. "
                + "Lose 11 HP); or you turn up a lost courier's satchel, still sealed "
                + "(Gain 64 Gold (Mora). Lose 8 HP).",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.INITIAL.options.REST.title"] =
                "Rest",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.INITIAL.options.REST.description"] =
                "Make camp in the lee of the ridge. Heal HP (rest site amount). The "
                + "wet undergrowth begins to move — Fight 4 Bramble Wrigglers "
                + "(Wrigglers).",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.REST.options.FIGHT.title"] =
                "Rest",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.REST.options.FIGHT.description"] =
                "Make camp in the lee of the ridge. Heal HP (rest site amount). The "
                + "wet undergrowth begins to move — Fight 4 Bramble Wrigglers "
                + "(Wrigglers).",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.TRUDGE_ON.description"] =
                "One of the following is randomly offered: a bramble stand snaps "
                + "back and takes something with it (Remove a card from your Deck. "
                + "Lose 11 HP); or you turn up a lost courier's satchel, still sealed "
                + "(Gain 64 Gold (Mora). Lose 8 HP).",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM.pages.REST.description"] =
                "Make camp in the lee of the ridge. Heal HP (rest site amount). The "
                + "wet undergrowth begins to move — Fight 4 Bramble Wrigglers "
                + "(Wrigglers).",
            // GuildCommissionAtStarsnatchCliff (Mondstadt / JungleMazeAdventure)
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF.title"] =
                "The Guild Commission at Starsnatch Cliff",
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF.pages.INITIAL.description"] =
                "The Adventurers' Guild desk has posted the same commission twice: "
                + "a switchback maze of scree and old stonework under Starsnatch "
                + "Cliff, where the paths are said to rearrange after every storm. A "
                + "pair of Guild regulars drinking at the Angel's Share offer to walk "
                + "it with you and split whatever turns up; the board pays better for "
                + "whoever signs alone.",
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF.pages.INITIAL.options.SOLO_QUEST.title"] =
                "Solo Quest",
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF.pages.INITIAL.options.SOLO_QUEST.description"] =
                "Gain 135-165 Mora (Gold). Lose 18 HP.",
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF.pages.INITIAL.options.JOIN_FORCES.title"] =
                "Join Forces",
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF.pages.INITIAL.options.JOIN_FORCES.description"] =
                "Gain 35-65 Mora (Gold).",
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF.pages.SOLO_QUEST.description"] =
                "Gain 135-165 Mora (Gold). Lose 18 HP.",
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF.pages.JOIN_FORCES.description"] =
                "Gain 35-65 Mora (Gold).",
            // SingingGrowthUnderWolvendom (Mondstadt / LuminousChoir)
            ["SINGING_GROWTH_UNDER_WOLVENDOM.title"] =
                "The Singing Growth Under Wolvendom",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.INITIAL.description"] =
                "On the wooded slope beneath Wolvendom, a ring of pale fungus has "
                + "fused into a single body the size of a cart, and it is singing — "
                + "many small voices braided into one chord. A Knights of Favonius "
                + "outrider says a courier's satchel went into the growth two winters "
                + "back, and that whatever's left of it is still in there, glowing "
                + "faintly under the bark.",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.INITIAL.options.REACH_INTO_THE_FLESH.title"] =
                "Reach into the Flesh",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.INITIAL.options.REACH_INTO_THE_FLESH.description"] =
                "You push your arm through the warm pulp until your fingers close "
                + "on something buried. Remove 2 cards from Deck. Add Spore Mind "
                + "(curse) to Deck.",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.INITIAL.options.OFFER_TRIBUTE.title"] =
                "Offer Tribute",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.INITIAL.options.OFFER_TRIBUTE.description"] =
                "Pay 99-149 Mora (Gold). Obtain a random Relic.",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.INITIAL.options.OFFER_TRIBUTE_LOCKED.title"] =
                "Offer Tribute",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.INITIAL.options.OFFER_TRIBUTE_LOCKED.description"] =
                "Pay 99-149 Mora (Gold). Obtain a random Relic.",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.REACH_INTO_THE_FLESH.description"] =
                "You push your arm through the warm pulp until your fingers close "
                + "on something buried. Remove 2 cards from Deck. Add Spore Mind "
                + "(curse) to Deck.",
            ["SINGING_GROWTH_UNDER_WOLVENDOM.pages.OFFER_TRIBUTE.description"] =
                "Pay 99-149 Mora (Gold). Obtain a random Relic.",
            // WolfRingAboveWindrise (Mondstadt / MorphicGrove)
            ["WOLF_RING_ABOVE_WINDRISE.title"] =
                "The Wolf-Ring Above Windrise",
            ["WOLF_RING_ABOVE_WINDRISE.pages.INITIAL.description"] =
                "A perfect ring of pines stands above Windrise where no windmill "
                + "was ever built, and Adventurers' Guild hunters camped nearby swear "
                + "the ring moves half a pace every full moon. One hunter, well into "
                + "her cups from the Angel's Share, waves you toward the center and "
                + "says the ring pays generously for company — and asks nothing at "
                + "all of anyone who just keeps walking.",
            ["WOLF_RING_ABOVE_WINDRISE.pages.INITIAL.options.GROUP.title"] =
                "Group",
            ["WOLF_RING_ABOVE_WINDRISE.pages.INITIAL.options.GROUP.description"] =
                "You empty your purse into the grass and let the ring do as it "
                + "likes. Lose ALL of your Gold (Mora). Transform 2 cards.",
            ["WOLF_RING_ABOVE_WINDRISE.pages.INITIAL.options.LONER.title"] =
                "Loner",
            ["WOLF_RING_ABOVE_WINDRISE.pages.INITIAL.options.LONER.description"] =
                "You walk on toward Windrise and let the quiet do its own work. "
                + "Gain 5 Max HP.",
            ["WOLF_RING_ABOVE_WINDRISE.pages.LONER.description"] =
                "You walk on toward Windrise and let the quiet do its own work. "
                + "Gain 5 Max HP.",
            ["WOLF_RING_ABOVE_WINDRISE.pages.GROUP.description"] =
                "You empty your purse into the grass and let the ring do as it "
                + "likes. Lose ALL of your Gold (Mora). Transform 2 cards.",
            // SpringvaleCheeseCellar (Mondstadt / RoomFullOfCheese)
            ["SPRINGVALE_CHEESE_CELLAR.title"] =
                "The Springvale Cheese Cellar",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.description"] =
                "A collapsed stair below Springvale opens onto a dairy cellar the "
                + "Guild's commission board never got around to delisting. Wheels of "
                + "Mondstadt cheese sit rack on rack, gold-rinded and humming with "
                + "age, and the slip in your hand says only: inventory it. Behind the "
                + "furthest rack, something older than the racks is sweating brine.",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.options.GORGE.title"] =
                "Taste the Racks",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.options.GORGE.description"] =
                "Choose 2 of 8 random Common cards to add to your Deck. The eight "
                + "wheels offered are never duplicates.",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.options.SEARCH.title"] =
                "Haul Out the Back Wall",
            ["SPRINGVALE_CHEESE_CELLAR.pages.INITIAL.options.SEARCH.description"] =
                "Lose 14 HP to strained shoulders and spore-thick air. Obtain The "
                + "Anointed Wheel (The Chosen Cheese): at the end of combat, gain 1 "
                + "Max HP.",
            ["SPRINGVALE_CHEESE_CELLAR.pages.GORGE.selectionScreenPrompt"] =
                "Taste the Racks",
            ["SPRINGVALE_CHEESE_CELLAR.pages.GORGE.description"] =
                "Choose 2 of 8 random Common cards to add to your Deck. The eight "
                + "wheels offered are never duplicates.",
            ["SPRINGVALE_CHEESE_CELLAR.pages.SEARCH.description"] =
                "Lose 14 HP to strained shoulders and spore-thick air. Obtain The "
                + "Anointed Wheel (The Chosen Cheese): at the end of combat, gain 1 "
                + "Max HP.",
            ["SPRINGVALE_CHEESE_CELLAR.loss"] =
                "{character} was buried under the back wall of the "
                + "[gold]{event}[/gold].",
            // CliffsideSeedNearCapeOath (Mondstadt / SapphireSeed)
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH.title"] =
                "The Cliffside Seed Near Cape Oath",
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH.pages.INITIAL.description"] =
                "On the sea-cliffs above Cape Oath, a Knights of Favonius botanist "
                + "has found a single seed the color of deep water, wedged in a crack "
                + "the wind can't reach. She has half a mind to grind it for the "
                + "infirmary and half a mind to see what it grows into — regulations "
                + "don't cover either, she admits, so the choice is yours to make and "
                + "hers to write up afterward.",
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH.pages.INITIAL.options.EAT.title"] =
                "Consume",
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH.pages.INITIAL.options.EAT.description"] =
                "Heal 9 HP. Upgrade a card in your Deck.",
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH.pages.INITIAL.options.PLANT.title"] =
                "Plant and Nourish",
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH.pages.INITIAL.options.PLANT.description"] =
                "Enchant a card with Sown.",
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH.pages.EAT.description"] =
                "Heal 9 HP. Upgrade a card in your Deck.",
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH.pages.PLANT.description"] =
                "Enchant a card with Sown.",
            // AngelsSharesTastingFlight (Mondstadt / TeaMaster)
            ["ANGELS_SHARES_TASTING_FLIGHT.title"] =
                "The Angel's Share's Tasting Flight",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.description"] =
                "The Angel's Share keeps a back-room tasting flight nobody orders "
                + "unless Charles vouches for them personally. Three cups sit on the "
                + "bar: a bone-pale tea that sharpens a duelist's opening stance, a "
                + "bitter ember-red brew that a Knight swears kept her arm strong "
                + "through five straight bouts, and a free cup Charles pours with a "
                + "warning look that you should probably heed.",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.BONE_TEA.title"] =
                "Bone Tea",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.BONE_TEA.description"] =
                "Pay 50 Gold (Mora). At the start of the next combat, Upgrade your "
                + "starting hand.",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.EMBER_TEA.title"] =
                "Ember Tea",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.EMBER_TEA.description"] =
                "Pay 150 Gold (Mora). At the start of the next 5 combats, gain 2 "
                + "Strength.",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.TEA_OF_DISCOURTESY.title"] =
                "Tea of Discourtesy",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.TEA_OF_DISCOURTESY.description"] =
                "At the start of the next combat, shuffle 2 Dazed into your Draw "
                + "Pile.",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.BONE_TEA_LOCKED.title"] =
                "Bone Tea",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.BONE_TEA_LOCKED.description"] =
                "Pay 50 Gold (Mora). At the start of the next combat, Upgrade your "
                + "starting hand.",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.EMBER_TEA_LOCKED.title"] =
                "Ember Tea",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.INITIAL.options.EMBER_TEA_LOCKED.description"] =
                "Pay 150 Gold (Mora). At the start of the next 5 combats, gain 2 "
                + "Strength.",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.DONE.description"] =
                "Pay 50 Gold (Mora). At the start of the next combat, Upgrade your "
                + "starting hand.",
            ["ANGELS_SHARES_TASTING_FLIGHT.pages.TEA_OF_DISCOURTESY.description"] =
                "At the start of the next combat, shuffle 2 Dazed into your Draw "
                + "Pile.",
            // GuildsStandingCommissionAtCapeOath (Mondstadt / TheLegendsWereTrue)
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.title"] =
                "The Guild's Standing Commission at Cape Oath",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.description"] =
                "The Adventurers' Guild desk has kept a commission open for years "
                + "on the old sailor's tale of treasure under Cape Oath, and every "
                + "posting-board veteran assumes it's a joke played on new recruits. "
                + "A weathered chart in the receptionist's drawer says otherwise — "
                + "the coastline in it matches nothing on the current map. She offers "
                + "you the chart itself, no questions asked, or a faster way out if "
                + "the cliffs get the better of you.",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.options.NAB_THE_MAP.title"] =
                "Nab the Map",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.options.NAB_THE_MAP.description"] =
                "Receive the Spoils Map.",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.options.SLOWLY_FIND_AN_EXIT.title"] =
                "Slowly Find an Exit",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.INITIAL.options.SLOWLY_FIND_AN_EXIT.description"] =
                "Lose 8 HP. Procure 1 random Potion.",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.NAB_THE_MAP.description"] =
                "Receive the Spoils Map.",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH.pages.SLOWLY_FIND_AN_EXIT.description"] =
                "Lose 8 HP. Procure 1 random Potion.",
            // HauntedCampsiteBelowDragonspine (Mondstadt / UnrestSite)
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE.title"] =
                "The Haunted Campsite Below Dragonspine",
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE.pages.INITIAL.description"] =
                "A ring of scorched stones at Dragonspine's foot looks like a rest "
                + "site from a distance, but the Knights of Favonius have posted it "
                + "as unfit for overnight use — regulation says why, in three dense "
                + "paragraphs about what campers here report seeing. You can make "
                + "camp anyway and take your chances with the dreams, or dig out the "
                + "roots that seem to be causing the trouble and see what comes "
                + "loose.",
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE.pages.INITIAL.options.REST.title"] =
                "Rest Anyways",
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE.pages.INITIAL.options.REST.description"] =
                "Heal to full HP. Receive Poor Sleep (curse).",
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE.pages.INITIAL.options.KILL.title"] =
                "Kill the Trees",
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE.pages.INITIAL.options.KILL.description"] =
                "Lose 8 Max HP. Obtain a random Relic.",
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE.pages.REST.description"] =
                "Heal to full HP. Receive Poor Sleep (curse).",
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE.pages.KILL.description"] =
                "Lose 8 Max HP. Obtain a random Relic.",
            // SpringvaleFont (Mondstadt / Wellspring)
            ["SPRINGVALE_FONT.title"] =
                "The Springvale Font",
            ["SPRINGVALE_FONT.pages.INITIAL.description"] =
                "Above Springvale, past the last hound, a spring feeds Cider Lake "
                + "straight out of the rock. A Knight of Favonius on well-duty is "
                + "scrubbing her tabard in it and does not stop to salute you. "
                + "\"Sister Victoria says it's Barbatos's water, so it hears "
                + "confession whether you offer one or not. I'd bottle it and keep "
                + "your mouth shut.\"",
            ["SPRINGVALE_FONT.pages.INITIAL.options.BOTTLE.title"] =
                "Bottle It",
            ["SPRINGVALE_FONT.pages.INITIAL.options.BOTTLE.description"] =
                "You fill a flask from the head of the spring while the current is "
                + "still bright. Procure 1 random Potion.",
            ["SPRINGVALE_FONT.pages.INITIAL.options.BATHE.title"] =
                "Bathe",
            ["SPRINGVALE_FONT.pages.INITIAL.options.BATHE.description"] =
                "You wade in and the cold pulls one old reflex right out of your "
                + "hands — Remove 1 card from Deck. You climb out clean, and spend "
                + "the rest of the walk to Mondstadt turning over exactly why that "
                + "one, and who it belonged to before you. Add 1 Guilty (curse) to "
                + "Deck.",
            ["SPRINGVALE_FONT.pages.BOTTLE.description"] =
                "You fill a flask from the head of the spring while the current is "
                + "still bright. Procure 1 random Potion.",
            ["SPRINGVALE_FONT.pages.BATHE.description"] =
                "You wade in and the cold pulls one old reflex right out of your "
                + "hands — Remove 1 card from Deck. You climb out clean, and spend "
                + "the rest of the walk to Mondstadt turning over exactly why that "
                + "one, and who it belonged to before you. Add 1 Guilty (curse) to "
                + "Deck.",
            // MosiMosiAtStormbearerPoint (Mondstadt / WhisperingHollow)
            ["MOSI_MOSI_AT_STORMBEARER_POINT.title"] =
                "Mosi Mosi at Stormbearer Point",
            ["MOSI_MOSI_AT_STORMBEARER_POINT.pages.INITIAL.description"] =
                "Wind off Stormbearer Point has scoured a hilichurl camp down to "
                + "stakes, a cauldron, and one enormous mask. A Guild scout chalked "
                + "the rock nearby: NON-HOSTILE, DO NOT PROVOKE, THEY TRADE. The "
                + "shaman stirs something violently blue, taps the cauldron twice, "
                + "then taps its own chest — two prices, your pick.",
            ["MOSI_MOSI_AT_STORMBEARER_POINT.pages.INITIAL.options.GOLD.title"] =
                "Barter for the Brew",
            ["MOSI_MOSI_AT_STORMBEARER_POINT.pages.INITIAL.options.GOLD.description"] =
                "Lose 50 Mora. Procure 2 random Potions.",
            ["MOSI_MOSI_AT_STORMBEARER_POINT.pages.INITIAL.options.HUG.title"] =
                "Kneel for the Shaman's Mark",
            ["MOSI_MOSI_AT_STORMBEARER_POINT.pages.INITIAL.options.HUG.description"] =
                "Lose 9 HP. Choose a card to Transform.",
            ["MOSI_MOSI_AT_STORMBEARER_POINT.pages.GOLD.description"] =
                "Lose 50 Mora. Procure 2 random Potions.",
            ["MOSI_MOSI_AT_STORMBEARER_POINT.pages.HUG.description"] =
                "Lose 9 HP. Choose a card to Transform.",
            // HuntersTotemPostsNearWolvendom (Mondstadt / WoodCarvings)
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.title"] =
                "The Hunters' Totem Posts Near Wolvendom",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.description"] =
                "Adventurers' Guild hunters camped at the edge of Wolvendom have "
                + "carved three totem posts from windfall wood — a diving falcon, a "
                + "coiled serpent, and a squat, armored shape nobody can agree on. A "
                + "hunter says each post remembers what it was carved to be, and "
                + "offers to work the same trick into a beginner's starting gear, if "
                + "you can spare one to the fire.",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.options.BIRD.title"] =
                "Bird",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.options.BIRD.description"] =
                "Choose 1 starter card to Transform into Peck.",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.options.SNAKE.title"] =
                "Snake",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.options.SNAKE.description"] =
                "Enchant 1 card with Slither. (Locked if no cards can be enchanted "
                + "with Slither)",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.options.TORUS.title"] =
                "Torus",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.options.TORUS.description"] =
                "Choose 1 starter card to Transform into Toric Toughness.",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.options.SNAKE_LOCKED.title"] =
                "Snake",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.INITIAL.options.SNAKE_LOCKED.description"] =
                "Enchant 1 card with Slither. (Locked if no cards can be enchanted "
                + "with Slither)",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.BIRD.description"] =
                "Choose 1 starter card to Transform into Peck.",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.SNAKE.description"] =
                "Enchant 1 card with Slither. (Locked if no cards can be enchanted "
                + "with Slither)",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM.pages.TORUS.description"] =
                "Choose 1 starter card to Transform into Toric Toughness.",
            // ContractRecitingGrowth (Liyue / BrainLeech)
            ["CONTRACT_RECITING_GROWTH.title"] =
                "The Contract-Reciting Growth",
            ["CONTRACT_RECITING_GROWTH.pages.INITIAL.description"] =
                "At the Chasm's mouth, a Qixing survey crew has roped off a "
                + "ley-line growth that fastened onto a miner before anyone could "
                + "stop it. It hasn't let go, and it hasn't stopped reciting — old "
                + "adeptal covenants, none of them Liyue law anymore, all of it "
                + "delivered in a bored monotone against your ear the moment you get "
                + "close. A diviner offers you the standing choice she's already "
                + "offered three others today, terms unchanged: sit still and learn, "
                + "or tear it off and take what it was holding.",
            ["CONTRACT_RECITING_GROWTH.pages.INITIAL.options.SHARE_KNOWLEDGE.title"] =
                "Share Knowledge",
            ["CONTRACT_RECITING_GROWTH.pages.INITIAL.options.SHARE_KNOWLEDGE.description"] =
                "Choose 1 of 5 random cards to add to your deck.",
            ["CONTRACT_RECITING_GROWTH.pages.INITIAL.options.RIP.title"] =
                "Rip the Leech Off",
            ["CONTRACT_RECITING_GROWTH.pages.INITIAL.options.RIP.description"] =
                "Lose 5 HP. Gain a Colorless 2 card reward.",
            ["CONTRACT_RECITING_GROWTH.pages.RIP.description"] =
                "Lose 5 HP. Gain a Colorless 2 card reward.",
            ["CONTRACT_RECITING_GROWTH.pages.SHARE_KNOWLEDGE.selectionScreenPrompt"] =
                "Share Knowledge",
            ["CONTRACT_RECITING_GROWTH.pages.SHARE_KNOWLEDGE.description"] =
                "Choose 1 of 5 random cards to add to your deck.",
            // QingceLarder (Liyue / RoomFullOfCheese)
            ["QINGCE_LARDER.title"] =
                "The Qingce Larder",
            ["QINGCE_LARDER.pages.INITIAL.description"] =
                "A collapsed terrace wall below Qingce Village opens onto a "
                + "root-cellar the Feiyun Commerce Guild never finished inventorying "
                + "before the harvest season turned it over to the village instead. "
                + "Jars of pickled radish and aged tofu line the shelves, each one "
                + "labeled in a farmer's careful hand. Behind the last rack, "
                + "something has been fermenting far longer than the others, and it "
                + "smells like it knows you're there.",
            ["QINGCE_LARDER.pages.INITIAL.options.GORGE.title"] =
                "Gorge",
            ["QINGCE_LARDER.pages.INITIAL.options.GORGE.description"] =
                "Choose 2 of 8 random Common cards to add to your Deck. The eight "
                + "jars offered are never duplicates.",
            ["QINGCE_LARDER.pages.INITIAL.options.SEARCH.title"] =
                "Search",
            ["QINGCE_LARDER.pages.INITIAL.options.SEARCH.description"] =
                "Lose 14 HP. Obtain The Chosen Cheese (relic): at the end of "
                + "combat, gain 1 Max HP.",
            ["QINGCE_LARDER.pages.GORGE.selectionScreenPrompt"] =
                "Gorge",
            ["QINGCE_LARDER.pages.GORGE.description"] =
                "Choose 2 of 8 random Common cards to add to your Deck. The eight "
                + "jars offered are never duplicates.",
            ["QINGCE_LARDER.pages.SEARCH.description"] =
                "Lose 14 HP. Obtain The Chosen Cheese (relic): at the end of "
                + "combat, gain 1 Max HP.",
            // SteeperAtHeyu (Liyue / TeaMaster)
            ["STEEPER_AT_HEYU.title"] =
                "The Steeper at Heyu",
            ["STEEPER_AT_HEYU.pages.INITIAL.description"] =
                "Heyu Tea House keeps a back room where the kettle is never quite "
                + "allowed to cool. The master there does not ask your name, only "
                + "your intent, then sets three cups on a Cor Lapis tray without "
                + "waiting for an answer. Payment, she mentions, is customary before "
                + "the first sip — this being Liyue, and a contract being a contract.",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.BONE_TEA.title"] =
                "Bone-Ash Oolong",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.BONE_TEA.description"] =
                "Pay 50 Mora. At the start of the next combat, Upgrade your "
                + "starting hand.",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.EMBER_TEA.title"] =
                "Cinnabar Ember Tea",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.EMBER_TEA.description"] =
                "Pay 150 Mora. At the start of the next 5 combats, gain 2 Strength.",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.TEA_OF_DISCOURTESY.title"] =
                "Tea of Discourtesy",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.TEA_OF_DISCOURTESY.description"] =
                "Take the free cup — yesterday's leaves, poured without ceremony "
                + "and drunk the same way. At the start of the next combat, shuffle 2 "
                + "Dazed into your Draw Pile.",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.BONE_TEA_LOCKED.title"] =
                "Bone-Ash Oolong",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.BONE_TEA_LOCKED.description"] =
                "Pay 50 Mora. At the start of the next combat, Upgrade your "
                + "starting hand.",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.EMBER_TEA_LOCKED.title"] =
                "Cinnabar Ember Tea",
            ["STEEPER_AT_HEYU.pages.INITIAL.options.EMBER_TEA_LOCKED.description"] =
                "Pay 150 Mora. At the start of the next 5 combats, gain 2 Strength.",
            ["STEEPER_AT_HEYU.pages.DONE.description"] =
                "Pay 50 Mora. At the start of the next combat, Upgrade your "
                + "starting hand.",
            ["STEEPER_AT_HEYU.pages.TEA_OF_DISCOURTESY.description"] =
                "Take the free cup — yesterday's leaves, poured without ceremony "
                + "and drunk the same way. At the start of the next combat, shuffle 2 "
                + "Dazed into your Draw Pile.",
            // TalesOfGuyunWereTrue (Liyue / TheLegendsWereTrue)
            ["TALES_OF_GUYUN_WERE_TRUE.title"] =
                "The Tales of Guyun Were True",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.description"] =
                "The drowned hall under Guyun Stone Forest was supposed to be a "
                + "fisherman's tall tale, but the tide is out and the doorway is real "
                + "stone. Treasure Hoarders reached it first and left in a hurry: "
                + "overturned crates, a snuffed lantern, a lacquered chart pinned to "
                + "the wall with a knife. Your Guild commission said survey only. The "
                + "passage behind you is already taking water.",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title"] =
                "Nab the Chart",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.description"] =
                "Receive the Hoarders' spoils chart (Spoils Map).",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.options.SLOWLY_FIND_AN_EXIT.title"] =
                "Feel Your Way Out Slowly",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.INITIAL.options.SLOWLY_FIND_AN_EXIT.description"] =
                "Lose 8 HP scraping through the flooded crawlway. Procure 1 random "
                + "Potion from a cracked Hoarder crate.",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.NAB_THE_MAP.description"] =
                "Receive the Hoarders' spoils chart (Spoils Map).",
            ["TALES_OF_GUYUN_WERE_TRUE.pages.SLOWLY_FIND_AN_EXIT.description"] =
                "Lose 8 HP scraping through the flooded crawlway. Procure 1 random "
                + "Potion from a cracked Hoarder crate.",
            // SixContractsToABetterYou (Liyue / SelfHelpBook)
            ["SIX_CONTRACTS_TO_ABETTER_YOU.title"] =
                "Six Contracts to a Better You",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.description"] =
                "A Feiyun pamphleteer has set up a folding stall on the Harbor "
                + "steps selling a slim, badly bound book that promises to sharpen, "
                + "steady, or quicken whatever you already carry — no refunds, terms "
                + "printed small on the back cover. \"Read whichever chapter applies "
                + "to your kit,\" she says, sliding it across, \"there's nothing in "
                + "here for a hand with nothing in it.\" If none of the three "
                + "chapters have anything to grip onto, she simply takes the book "
                + "back and waves you on.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_THE_BACK.title"] =
                "Read the Back",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_THE_BACK.description"] =
                "Choose an Attack to Enchant with Sharp 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_PASSAGE.title"] =
                "Read a Random Passage",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_PASSAGE.description"] =
                "Choose a Skill to Enchant with Nimble 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_ENTIRE_BOOK.title"] =
                "Read the Entire Book",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_ENTIRE_BOOK.description"] =
                "Choose a Power to Enchant with Swift 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.NO_OPTIONS.title"] =
                "Move On",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.NO_OPTIONS.description"] =
                "Nothing happens.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_THE_BACK_LOCKED.title"] =
                "Read the Back",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_THE_BACK_LOCKED.description"] =
                "Choose an Attack to Enchant with Sharp 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_PASSAGE_LOCKED.title"] =
                "Read a Random Passage",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_PASSAGE_LOCKED.description"] =
                "Choose a Skill to Enchant with Nimble 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_ENTIRE_BOOK_LOCKED.title"] =
                "Read the Entire Book",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.INITIAL.options.READ_ENTIRE_BOOK_LOCKED.description"] =
                "Choose a Power to Enchant with Swift 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.READ_THE_BACK.description"] =
                "Choose an Attack to Enchant with Sharp 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.READ_PASSAGE.description"] =
                "Choose a Skill to Enchant with Nimble 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.READ_ENTIRE_BOOK.description"] =
                "Choose a Power to Enchant with Swift 2.",
            ["SIX_CONTRACTS_TO_ABETTER_YOU.pages.NO_OPTIONS.description"] =
                "Nothing happens.",
            // RopeBridgeBelowDunyuRuins (Liyue / SlipperyBridge)
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.title"] =
                "The Rope Bridge Below Dunyu Ruins",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.INITIAL.description"] =
                "Rain has been falling on the upper Chasm since dawn, and the old "
                + "rope bridge toward the Dunyu Ruins sways black and slick with it. "
                + "Katheryne's commission notes said to travel light; you did not. "
                + "Halfway across a plank drops away, and your overloaded pack swings "
                + "out over nothing but mist.",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.INITIAL.options.OVERCOME.title"] =
                "Let It Fall",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.INITIAL.options.OVERCOME.description"] =
                "[Specific card] is removed from your deck.",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.INITIAL.options.HOLD_ON_0.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.INITIAL.options.HOLD_ON_0.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_0.options.HOLD_ON_1.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_0.options.HOLD_ON_1.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_1.options.HOLD_ON_2.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_1.options.HOLD_ON_2.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_2.options.HOLD_ON_3.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_2.options.HOLD_ON_3.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_3.options.HOLD_ON_4.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_3.options.HOLD_ON_4.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_4.options.HOLD_ON_5.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_4.options.HOLD_ON_5.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_5.options.HOLD_ON_6.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_5.options.HOLD_ON_6.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_6.options.HOLD_ON_LOOP.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_6.options.HOLD_ON_LOOP.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_LOOP.options.HOLD_ON_LOOP.title"] =
                "Hold On",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_LOOP.options.HOLD_ON_LOOP.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.OVERCOME.description"] =
                "[Specific card] is removed from your deck.",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_0.description"] =
                "Lose 3 HP as the wet rope scours your palms. The thing about to "
                + "slip is randomized — some other piece of your kit takes its place "
                + "at the knot. Each time you clamp down again, the strain costs 1 "
                + "more HP than the last, and the bridge keeps offering you the same "
                + "two choices until you finally let something fall. The knot never "
                + "picks the same thing twice while anything else remains, and never "
                + "anything lashed down for good (Eternal).",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_1.description"] =
                "",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_2.description"] =
                "",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_3.description"] =
                "",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_4.description"] =
                "",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_5.description"] =
                "",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_6.description"] =
                "",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS.pages.HOLD_ON_LOOP.description"] =
                "",
            // UnclaimedCratesAtFeiyunSlope (Liyue / ThisOrThat)
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.title"] =
                "The Unclaimed Crates at Feiyun Slope",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.description"] =
                "Two unlabeled crates sit on the Feiyun Slope loading dock, hauled "
                + "off a cargo junk whose manifest never named them. A dockhand "
                + "explains the Guild cannot log cargo it never contracted for, so "
                + "the finder may claim exactly one. Whichever you take, the other is "
                + "sealed and sent up to Liyue Harbor's lost-property office "
                + "unopened, per the standing charter — no argument entered into the "
                + "ledger either way.",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.options.PLAIN.title"] =
                "This",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.options.PLAIN.description"] =
                "Lose 6 HP. Gain 57 Gold.",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.options.ORNATE.title"] =
                "That",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.INITIAL.options.ORNATE.description"] =
                "Add Clumsy (curse) to your Deck. Obtain a random Relic.",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.PLAIN.description"] =
                "Lose 6 HP. Gain 57 Gold.",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE.pages.ORNATE.description"] =
                "Add Clumsy (curse) to your Deck. Obtain a random Relic.",
        };
}

/// <summary>
/// THE GENERATED TABLES the arm's two readers consult: the shape a
/// dressed event's mirror has, and the substitution the `PullNextEvent`
/// postfix makes. Both are generated from the same face files and the
/// same base-event index as the classes and the rows above, so the
/// three cannot disagree about what a dressing contains.
/// </summary>
internal static class TeyvatGeneratedEvents
{
    /// <summary>What a dressed event's mirror asks the loc table for:
    /// the INITIAL option key names, in the base event's order; the
    /// other page keys; and `ExtraOptionKeys`, the option keys that
    /// are not on the INITIAL page or have no face line of their own
    /// -- a `_LOCKED` twin, or an option a later page offers. An
    /// extra key is a full suffix under the entry and is a PREFIX
    /// like any option key: `.title` and `.description` both. Read
    /// by the headless pins, which check the key set against the
    /// merged rows without constructing a model.</summary>
    internal sealed record EventShape(
        string BaseEntry,
        string Mirror,
        IReadOnlyList<string> OptionKeys,
        IReadOnlyList<string> PageKeys,
        IReadOnlyList<string> ExtraOptionKeys,
        bool HasLossRow);

    /// <summary>Dressed event type -> its shape.</summary>
    internal static readonly IReadOnlyDictionary<Type, EventShape> Shapes =
        new Dictionary<Type, EventShape>
        {
            [typeof(Events.Mondstadt.GuildDesksReturnedCopy)] = new EventShape(
                "GUILD_DESKS_RETURNED_COPY", "SelfHelpBookMirror",
                new[] { "READ_THE_BACK", "READ_PASSAGE", "READ_ENTIRE_BOOK", "NO_OPTIONS" },
                new[] { "pages.READ_THE_BACK.description", "pages.READ_PASSAGE.description", "pages.READ_ENTIRE_BOOK.description", "pages.NO_OPTIONS.description" },
                new[] { "pages.INITIAL.options.READ_THE_BACK_LOCKED", "pages.INITIAL.options.READ_PASSAGE_LOCKED", "pages.INITIAL.options.READ_ENTIRE_BOOK_LOCKED" },
                false),
            [typeof(Events.Mondstadt.CutRopeBridgeAboveCiderLake)] = new EventShape(
                "CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE", "SlipperyBridgeMirror",
                new[] { "OVERCOME", "HOLD_ON_0" },
                new[] { "pages.OVERCOME.description", "pages.HOLD_ON_0.description", "pages.HOLD_ON_1.description", "pages.HOLD_ON_2.description", "pages.HOLD_ON_3.description", "pages.HOLD_ON_4.description", "pages.HOLD_ON_5.description", "pages.HOLD_ON_6.description", "pages.HOLD_ON_LOOP.description" },
                new[] { "pages.HOLD_ON_0.options.HOLD_ON_1", "pages.HOLD_ON_1.options.HOLD_ON_2", "pages.HOLD_ON_2.options.HOLD_ON_3", "pages.HOLD_ON_3.options.HOLD_ON_4", "pages.HOLD_ON_4.options.HOLD_ON_5", "pages.HOLD_ON_5.options.HOLD_ON_6", "pages.HOLD_ON_6.options.HOLD_ON_LOOP", "pages.HOLD_ON_LOOP.options.HOLD_ON_LOOP" },
                false),
            [typeof(Events.Mondstadt.UnmarkedCrates)] = new EventShape(
                "UNMARKED_CRATES", "ThisOrThatMirror",
                new[] { "PLAIN", "ORNATE" },
                new[] { "pages.PLAIN.description", "pages.ORNATE.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.WanderingCask)] = new EventShape(
                "WANDERING_CASK", "AromaOfChaosMirror",
                new[] { "LET_GO", "MAINTAIN_CONTROL" },
                new[] { "pages.LET_GO.description", "pages.MAINTAIN_CONTROL.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.StormTouchedShardAtStormterrorsLair)] = new EventShape(
                "STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR", "BrainLeechMirror",
                new[] { "SHARE_KNOWLEDGE", "RIP" },
                new[] { "pages.RIP.description", "pages.SHARE_KNOWLEDGE.selectionScreenPrompt", "pages.SHARE_KNOWLEDGE.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.WindfalconsRoost)] = new EventShape(
                "WINDFALCONS_ROOST", "ByrdonisNestMirror",
                new[] { "EAT", "TAKE" },
                new[] { "pages.EAT.description", "pages.TAKE.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.BrambleLineBelowWolvendom)] = new EventShape(
                "BRAMBLE_LINE_BELOW_WOLVENDOM", "DenseVegetationMirror",
                new[] { "TRUDGE_ON", "REST" },
                new[] { "pages.TRUDGE_ON.description", "pages.REST.description" },
                new[] { "pages.REST.options.FIGHT" },
                false),
            [typeof(Events.Mondstadt.GuildCommissionAtStarsnatchCliff)] = new EventShape(
                "GUILD_COMMISSION_AT_STARSNATCH_CLIFF", "JungleMazeAdventureMirror",
                new[] { "SOLO_QUEST", "JOIN_FORCES" },
                new[] { "pages.SOLO_QUEST.description", "pages.JOIN_FORCES.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.SingingGrowthUnderWolvendom)] = new EventShape(
                "SINGING_GROWTH_UNDER_WOLVENDOM", "LuminousChoirMirror",
                new[] { "REACH_INTO_THE_FLESH", "OFFER_TRIBUTE" },
                new[] { "pages.REACH_INTO_THE_FLESH.description", "pages.OFFER_TRIBUTE.description" },
                new[] { "pages.INITIAL.options.OFFER_TRIBUTE_LOCKED" },
                false),
            [typeof(Events.Mondstadt.WolfRingAboveWindrise)] = new EventShape(
                "WOLF_RING_ABOVE_WINDRISE", "MorphicGroveMirror",
                new[] { "GROUP", "LONER" },
                new[] { "pages.LONER.description", "pages.GROUP.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.SpringvaleCheeseCellar)] = new EventShape(
                "SPRINGVALE_CHEESE_CELLAR", "RoomFullOfCheeseMirror",
                new[] { "GORGE", "SEARCH" },
                new[] { "pages.GORGE.selectionScreenPrompt", "pages.GORGE.description", "pages.SEARCH.description" },
                Array.Empty<string>(),
                true),
            [typeof(Events.Mondstadt.CliffsideSeedNearCapeOath)] = new EventShape(
                "CLIFFSIDE_SEED_NEAR_CAPE_OATH", "SapphireSeedMirror",
                new[] { "EAT", "PLANT" },
                new[] { "pages.EAT.description", "pages.PLANT.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.AngelsSharesTastingFlight)] = new EventShape(
                "ANGELS_SHARES_TASTING_FLIGHT", "TeaMasterMirror",
                new[] { "BONE_TEA", "EMBER_TEA", "TEA_OF_DISCOURTESY" },
                new[] { "pages.DONE.description", "pages.TEA_OF_DISCOURTESY.description" },
                new[] { "pages.INITIAL.options.BONE_TEA_LOCKED", "pages.INITIAL.options.EMBER_TEA_LOCKED" },
                false),
            [typeof(Events.Mondstadt.GuildsStandingCommissionAtCapeOath)] = new EventShape(
                "GUILDS_STANDING_COMMISSION_AT_CAPE_OATH", "TheLegendsWereTrueMirror",
                new[] { "NAB_THE_MAP", "SLOWLY_FIND_AN_EXIT" },
                new[] { "pages.NAB_THE_MAP.description", "pages.SLOWLY_FIND_AN_EXIT.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.HauntedCampsiteBelowDragonspine)] = new EventShape(
                "HAUNTED_CAMPSITE_BELOW_DRAGONSPINE", "UnrestSiteMirror",
                new[] { "REST", "KILL" },
                new[] { "pages.REST.description", "pages.KILL.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.SpringvaleFont)] = new EventShape(
                "SPRINGVALE_FONT", "WellspringMirror",
                new[] { "BOTTLE", "BATHE" },
                new[] { "pages.BOTTLE.description", "pages.BATHE.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.MosiMosiAtStormbearerPoint)] = new EventShape(
                "MOSI_MOSI_AT_STORMBEARER_POINT", "WhisperingHollowMirror",
                new[] { "GOLD", "HUG" },
                new[] { "pages.GOLD.description", "pages.HUG.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Mondstadt.HuntersTotemPostsNearWolvendom)] = new EventShape(
                "HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM", "WoodCarvingsMirror",
                new[] { "BIRD", "SNAKE", "TORUS" },
                new[] { "pages.BIRD.description", "pages.SNAKE.description", "pages.TORUS.description" },
                new[] { "pages.INITIAL.options.SNAKE_LOCKED" },
                false),
            [typeof(Events.Liyue.ContractRecitingGrowth)] = new EventShape(
                "CONTRACT_RECITING_GROWTH", "BrainLeechMirror",
                new[] { "SHARE_KNOWLEDGE", "RIP" },
                new[] { "pages.RIP.description", "pages.SHARE_KNOWLEDGE.selectionScreenPrompt", "pages.SHARE_KNOWLEDGE.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Liyue.QingceLarder)] = new EventShape(
                "QINGCE_LARDER", "RoomFullOfCheeseMirror",
                new[] { "GORGE", "SEARCH" },
                new[] { "pages.GORGE.selectionScreenPrompt", "pages.GORGE.description", "pages.SEARCH.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Liyue.SteeperAtHeyu)] = new EventShape(
                "STEEPER_AT_HEYU", "TeaMasterMirror",
                new[] { "BONE_TEA", "EMBER_TEA", "TEA_OF_DISCOURTESY" },
                new[] { "pages.DONE.description", "pages.TEA_OF_DISCOURTESY.description" },
                new[] { "pages.INITIAL.options.BONE_TEA_LOCKED", "pages.INITIAL.options.EMBER_TEA_LOCKED" },
                false),
            [typeof(Events.Liyue.TalesOfGuyunWereTrue)] = new EventShape(
                "TALES_OF_GUYUN_WERE_TRUE", "TheLegendsWereTrueMirror",
                new[] { "NAB_THE_MAP", "SLOWLY_FIND_AN_EXIT" },
                new[] { "pages.NAB_THE_MAP.description", "pages.SLOWLY_FIND_AN_EXIT.description" },
                Array.Empty<string>(),
                false),
            [typeof(Events.Liyue.SixContractsToABetterYou)] = new EventShape(
                "SIX_CONTRACTS_TO_ABETTER_YOU", "SelfHelpBookMirror",
                new[] { "READ_THE_BACK", "READ_PASSAGE", "READ_ENTIRE_BOOK", "NO_OPTIONS" },
                new[] { "pages.READ_THE_BACK.description", "pages.READ_PASSAGE.description", "pages.READ_ENTIRE_BOOK.description", "pages.NO_OPTIONS.description" },
                new[] { "pages.INITIAL.options.READ_THE_BACK_LOCKED", "pages.INITIAL.options.READ_PASSAGE_LOCKED", "pages.INITIAL.options.READ_ENTIRE_BOOK_LOCKED" },
                false),
            [typeof(Events.Liyue.RopeBridgeBelowDunyuRuins)] = new EventShape(
                "ROPE_BRIDGE_BELOW_DUNYU_RUINS", "SlipperyBridgeMirror",
                new[] { "OVERCOME", "HOLD_ON_0" },
                new[] { "pages.OVERCOME.description", "pages.HOLD_ON_0.description", "pages.HOLD_ON_1.description", "pages.HOLD_ON_2.description", "pages.HOLD_ON_3.description", "pages.HOLD_ON_4.description", "pages.HOLD_ON_5.description", "pages.HOLD_ON_6.description", "pages.HOLD_ON_LOOP.description" },
                new[] { "pages.HOLD_ON_0.options.HOLD_ON_1", "pages.HOLD_ON_1.options.HOLD_ON_2", "pages.HOLD_ON_2.options.HOLD_ON_3", "pages.HOLD_ON_3.options.HOLD_ON_4", "pages.HOLD_ON_4.options.HOLD_ON_5", "pages.HOLD_ON_5.options.HOLD_ON_6", "pages.HOLD_ON_6.options.HOLD_ON_LOOP", "pages.HOLD_ON_LOOP.options.HOLD_ON_LOOP" },
                false),
            [typeof(Events.Liyue.UnclaimedCratesAtFeiyunSlope)] = new EventShape(
                "UNCLAIMED_CRATES_AT_FEIYUN_SLOPE", "ThisOrThatMirror",
                new[] { "PLAIN", "ORNATE" },
                new[] { "pages.PLAIN.description", "pages.ORNATE.description" },
                Array.Empty<string>(),
                false),
        };

    /// <summary>(dressing act entry, base event type) -> the dressed
    /// model that stands in for it at pull time. Consumed by
    /// `Patches/PullNextEventPatch`; see that file for why the
    /// substitution happens downstream of the shuffle.</summary>
    internal static readonly IReadOnlyDictionary<(string Dressing, Type BaseEvent), Func<EventModel>> Substitutions =
        new Dictionary<(string, Type), Func<EventModel>>
        {
            [(TeyvatFrame.Mondstadt, typeof(SelfHelpBook))] =
                () => ModelDb.Event<Events.Mondstadt.GuildDesksReturnedCopy>(),
            [(TeyvatFrame.Mondstadt, typeof(SlipperyBridge))] =
                () => ModelDb.Event<Events.Mondstadt.CutRopeBridgeAboveCiderLake>(),
            [(TeyvatFrame.Mondstadt, typeof(ThisOrThat))] =
                () => ModelDb.Event<Events.Mondstadt.UnmarkedCrates>(),
            [(TeyvatFrame.Mondstadt, typeof(AromaOfChaos))] =
                () => ModelDb.Event<Events.Mondstadt.WanderingCask>(),
            [(TeyvatFrame.Mondstadt, typeof(BrainLeech))] =
                () => ModelDb.Event<Events.Mondstadt.StormTouchedShardAtStormterrorsLair>(),
            [(TeyvatFrame.Mondstadt, typeof(ByrdonisNest))] =
                () => ModelDb.Event<Events.Mondstadt.WindfalconsRoost>(),
            [(TeyvatFrame.Mondstadt, typeof(DenseVegetation))] =
                () => ModelDb.Event<Events.Mondstadt.BrambleLineBelowWolvendom>(),
            [(TeyvatFrame.Mondstadt, typeof(JungleMazeAdventure))] =
                () => ModelDb.Event<Events.Mondstadt.GuildCommissionAtStarsnatchCliff>(),
            [(TeyvatFrame.Mondstadt, typeof(LuminousChoir))] =
                () => ModelDb.Event<Events.Mondstadt.SingingGrowthUnderWolvendom>(),
            [(TeyvatFrame.Mondstadt, typeof(MorphicGrove))] =
                () => ModelDb.Event<Events.Mondstadt.WolfRingAboveWindrise>(),
            [(TeyvatFrame.Mondstadt, typeof(RoomFullOfCheese))] =
                () => ModelDb.Event<Events.Mondstadt.SpringvaleCheeseCellar>(),
            [(TeyvatFrame.Mondstadt, typeof(SapphireSeed))] =
                () => ModelDb.Event<Events.Mondstadt.CliffsideSeedNearCapeOath>(),
            [(TeyvatFrame.Mondstadt, typeof(TeaMaster))] =
                () => ModelDb.Event<Events.Mondstadt.AngelsSharesTastingFlight>(),
            [(TeyvatFrame.Mondstadt, typeof(TheLegendsWereTrue))] =
                () => ModelDb.Event<Events.Mondstadt.GuildsStandingCommissionAtCapeOath>(),
            [(TeyvatFrame.Mondstadt, typeof(UnrestSite))] =
                () => ModelDb.Event<Events.Mondstadt.HauntedCampsiteBelowDragonspine>(),
            [(TeyvatFrame.Mondstadt, typeof(Wellspring))] =
                () => ModelDb.Event<Events.Mondstadt.SpringvaleFont>(),
            [(TeyvatFrame.Mondstadt, typeof(WhisperingHollow))] =
                () => ModelDb.Event<Events.Mondstadt.MosiMosiAtStormbearerPoint>(),
            [(TeyvatFrame.Mondstadt, typeof(WoodCarvings))] =
                () => ModelDb.Event<Events.Mondstadt.HuntersTotemPostsNearWolvendom>(),
            [(TeyvatFrame.Liyue, typeof(BrainLeech))] =
                () => ModelDb.Event<Events.Liyue.ContractRecitingGrowth>(),
            [(TeyvatFrame.Liyue, typeof(RoomFullOfCheese))] =
                () => ModelDb.Event<Events.Liyue.QingceLarder>(),
            [(TeyvatFrame.Liyue, typeof(TeaMaster))] =
                () => ModelDb.Event<Events.Liyue.SteeperAtHeyu>(),
            [(TeyvatFrame.Liyue, typeof(TheLegendsWereTrue))] =
                () => ModelDb.Event<Events.Liyue.TalesOfGuyunWereTrue>(),
            [(TeyvatFrame.Liyue, typeof(SelfHelpBook))] =
                () => ModelDb.Event<Events.Liyue.SixContractsToABetterYou>(),
            [(TeyvatFrame.Liyue, typeof(SlipperyBridge))] =
                () => ModelDb.Event<Events.Liyue.RopeBridgeBelowDunyuRuins>(),
            [(TeyvatFrame.Liyue, typeof(ThisOrThat))] =
                () => ModelDb.Event<Events.Liyue.UnclaimedCratesAtFeiyunSlope>(),
        };

    /// <summary>
    /// A dressed event's `Id.Entry` -> the image the default event layout
    /// draws for it until one of its own is supplied (EB-764).
    ///
    /// `EventModel.InitialPortraitPath` is `ImageHelper.GetImagePath(
    /// "events/" + Id.Entry.ToLowerInvariant() + ".png")` -- DERIVED from
    /// the id, `private`, and not virtual -- so a dressed event asks the
    /// pack for a path nothing produces and `NEventLayout.InitializeVisuals`
    /// threw `AssetLoadException` before the page was drawn. The value is the
    /// BASE event's own image, which is the same borrowing
    /// `TeyvatFrame.AssetAlias` makes for a dressing's backgrounds, and it
    /// retires the same way: `Patches/EventPortraitPatch` asks
    /// `ResourceLoader.Exists` of the DRESSED path first, so a real portrait
    /// dropped at `events/&lt;dressed entry&gt;.png` wins with no code change.
    ///
    /// GENERATED, so a dressed event cannot exist without a portrait row --
    /// which is exactly the shape EB-764 was.
    /// </summary>
    internal static readonly IReadOnlyDictionary<string, string> Portraits =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["GUILD_DESKS_RETURNED_COPY"] =
                "res://images/events/self_help_book.png",
            ["CUT_ROPE_BRIDGE_ABOVE_CIDER_LAKE"] =
                "res://images/events/slippery_bridge.png",
            ["UNMARKED_CRATES"] =
                "res://images/events/this_or_that.png",
            ["WANDERING_CASK"] =
                "res://images/events/aroma_of_chaos.png",
            ["STORM_TOUCHED_SHARD_AT_STORMTERRORS_LAIR"] =
                "res://images/events/brain_leech.png",
            ["WINDFALCONS_ROOST"] =
                "res://images/events/byrdonis_nest.png",
            ["BRAMBLE_LINE_BELOW_WOLVENDOM"] =
                "res://images/events/dense_vegetation.png",
            ["GUILD_COMMISSION_AT_STARSNATCH_CLIFF"] =
                "res://images/events/jungle_maze_adventure.png",
            ["SINGING_GROWTH_UNDER_WOLVENDOM"] =
                "res://images/events/luminous_choir.png",
            ["WOLF_RING_ABOVE_WINDRISE"] =
                "res://images/events/morphic_grove.png",
            ["SPRINGVALE_CHEESE_CELLAR"] =
                "res://images/events/room_full_of_cheese.png",
            ["CLIFFSIDE_SEED_NEAR_CAPE_OATH"] =
                "res://images/events/sapphire_seed.png",
            ["ANGELS_SHARES_TASTING_FLIGHT"] =
                "res://images/events/tea_master.png",
            ["GUILDS_STANDING_COMMISSION_AT_CAPE_OATH"] =
                "res://images/events/the_legends_were_true.png",
            ["HAUNTED_CAMPSITE_BELOW_DRAGONSPINE"] =
                "res://images/events/unrest_site.png",
            ["SPRINGVALE_FONT"] =
                "res://images/events/wellspring.png",
            ["MOSI_MOSI_AT_STORMBEARER_POINT"] =
                "res://images/events/whispering_hollow.png",
            ["HUNTERS_TOTEM_POSTS_NEAR_WOLVENDOM"] =
                "res://images/events/wood_carvings.png",
            ["CONTRACT_RECITING_GROWTH"] =
                "res://images/events/brain_leech.png",
            ["QINGCE_LARDER"] =
                "res://images/events/room_full_of_cheese.png",
            ["STEEPER_AT_HEYU"] =
                "res://images/events/tea_master.png",
            ["TALES_OF_GUYUN_WERE_TRUE"] =
                "res://images/events/the_legends_were_true.png",
            ["SIX_CONTRACTS_TO_ABETTER_YOU"] =
                "res://images/events/self_help_book.png",
            ["ROPE_BRIDGE_BELOW_DUNYU_RUINS"] =
                "res://images/events/slippery_bridge.png",
            ["UNCLAIMED_CRATES_AT_FEIYUN_SLOPE"] =
                "res://images/events/this_or_that.png",
        };
}
