// <auto-generated>
//     GENERATED by tools/gen_teyvat_events.py from
//     docs/current/dossiers/content/event-faces/glory-sumeru-2026-09-14.md
//     Do not edit by hand: `python tools/gen_teyvat_events.py --check`
//     fails on any drift, and the next run overwrites it.
// </auto-generated>

using KleeMod.Teyvat.Events.Mirrors;

namespace KleeMod.Teyvat.Events.Sumeru;

/// <summary>
/// Hollow of the Struck Name -- GraveOfTheForgotten, dressed for Sumeru.
///
/// Hollow of the Struck Name — Sumeru / Forest Rangers, against the Akademiya — quiet, accusatory — REUSED `event-conversion-gallery.md` § Grave of the Forgotten, variant 3
///
/// NOTHING MECHANICAL IS HERE AND THERE IS NOWHERE FOR IT TO BE. The
/// base event's clauses are in <see cref="GraveOfTheForgottenMirror"/>, written
/// once and shared by every nation that dresses this event; this class
/// is a NAME. `ModelDb.GetEntry` slugifies it into
/// `HOLLOW_OF_THE_STRUCK_NAME`, `EventModel.Title` and `InitialDescription`
/// derive from that, and `EventModel.OptionKey` slugifies
/// `GetType().Name` -- so every loc key the mirror asks for is already
/// this dressing's. The rows are in `TeyvatLoc.GeneratedEventRows`.
/// </summary>
public sealed class HollowOfTheStruckName : GraveOfTheForgottenMirror
{
}
