"""Build the loader-shaped real_ironclad artifacts from local inputs.

This is the last-mile step the loader docstring names
(extract_base_game_pool.py -> build_ironclad_sheet.py). A faithful loader entry
needs THREE local files, and the card/character pair does not drop out of the
extractor ready to use:

  game_ref/ironclad_pool.yaml       -- a SINGLE-document merged card list
  game_ref/ironclad-upgrades.yaml   -- one applicable upgrade per pool card
  game_ref/char_real_ironclad.yaml  -- the character entry (hp, deck, relics)

Inputs (all LOCAL / gitignored in game_ref/, never committed -- base-game
reference material):

  ironclad-cards.yaml        extractor output; TWO docs (doc 1 = the 35 cards
                             the JSON extractor can express, doc 2 = excluded:).
  ironclad_pool_pass*.yaml   ordered, hand-authored tier0-DSL translation
                             layers for cards the strict structural extractor
                             deliberately holds back. These are NOT
                             tool-regenerable: each pass records reviewed
                             design judgment, while numeric values and upgrade
                             deltas still come from the local DLL.
  ironclad_char_facts.yaml   the character facts (id/name/hp/starting_deck/
                             relic_hooks), decompiled from the Ironclad model.

`ironclad-upgrades.yaml` is generated by extract_base_game_pool.py from the
DLL: extractor rows carry their own effect provenance, and the local pass
rows supply provenance for their otherwise-mechanical OnUpgrade recovery.

Only THIS TOOL is committed; every data input stays in game_ref/.

Guarantees (the review findings this closes):
  * FAIL CLOSED. If a required supplement or the char facts are missing, the build
    ERRORS before writing anything -- it never overwrites a full reference
    with a 35-card stub.
  * NO SILENT DRIFT. doc 1 and the supplement must be disjoint; any shared id
    is an error (if the extractor starts expressing a card, its stale hand-
    recovered twin must be pruned from the supplement, not silently win).
    Duplicate ids within either input are errors too.
  * HONEST VERIFY. --verify checks the on-disk pool for duplicate ids and
    compares against the rebuild as an ORDERED list (not just id-keyed dicts),
    so ordering and duplication differences surface rather than hide.

Usage (from repo root):
  python -m tools.build_ironclad_sheet --split    # recover one missing layer/facts
  python -m tools.build_ironclad_sheet            # rebuild pool (+ char if missing)
  python -m tools.build_ironclad_sheet --verify   # validate current artifacts
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
GAME_REF = REPO / "game_ref"
EXTRACTOR_SHEET = GAME_REF / "ironclad-cards.yaml"    # 2-doc; we read doc 1
SUPPLEMENTS = (
    GAME_REF / "ironclad_pool_pass4.yaml",       # 22 reviewed cards
    GAME_REF / "ironclad_pool_pass5.yaml",       # engine-ready expansion
    GAME_REF / "ironclad_pool_pass6.yaml",       # bounded history/formulas
)
CHAR_FACTS = GAME_REF / "ironclad_char_facts.yaml"    # local, gitignored
POOL = GAME_REF / "ironclad_pool.yaml"                # loader input
UPGRADES = GAME_REF / "ironclad-upgrades.yaml"        # loader input
CHAR_OUT = GAME_REF / "char_real_ironclad.yaml"       # loader input

CHAR_FIELDS = ("id", "name", "hp", "starting_deck", "relic_hooks")

POOL_HEADER = """\
# MACHINE-GENERATED by tools/build_ironclad_sheet.py -- do not hand-edit.
# loader.EXTERNAL_CARD_SHEETS reads this as a single-document card list.
# LOCAL inputs (game_ref/, gitignored): ironclad-cards.yaml document 1
# (extractor) + the ordered ironclad_pool_pass*.yaml review layers.
# Rebuild:  python -m tools.build_ironclad_sheet
"""

SUPPLEMENT_HEADER = """\
# LOCAL ARTIFACT -- game_ref/ is gitignored. Reviewed Tier-0 translations
# absent from ironclad-cards.yaml document 1. Every supplement must stay
# disjoint from document 1 and every other layer. Merged into
# ironclad_pool.yaml by build_ironclad_sheet.py.
"""

CHAR_FACTS_HEADER = """\
# LOCAL ARTIFACT -- game_ref/ is gitignored. Decompiled Ironclad character
# facts (ilspycmd -t MegaCrit.Sts2.Core.Models.Characters.Ironclad): StartingHp,
# StartingDeck, StartingRelics=>BurningBlood (=> heal_after_won_fight). The
# loader-required fields only; build_ironclad_sheet.py emits char_real_ironclad.
"""

CHAR_OUT_HEADER = """\
# MACHINE-GENERATED by tools/build_ironclad_sheet.py from local
# game_ref/ironclad_char_facts.yaml -- loader-shaped stub. The design rulings
# for real_ironclad (why packages/constraints/bands are deliberately absent)
# live in the hand-authored artifact / design notes, not in this generated
# file. LOCAL: never copy into docs/ or tier0/content/.
"""


def _fail(msg: str) -> "None":
    sys.exit(f"build_ironclad_sheet: {msg}")


def _rel(p: Path) -> str:
    return str(p.relative_to(REPO))


def _dup_ids(cards: list[dict]) -> list[str]:
    seen: set[str] = set()
    dupes: list[str] = []
    for c in cards:
        cid = c["id"]
        if cid in seen and cid not in dupes:
            dupes.append(cid)
        seen.add(cid)
    return sorted(dupes)


def _doc1_cards() -> list[dict]:
    if not EXTRACTOR_SHEET.exists():
        _fail(f"missing {_rel(EXTRACTOR_SHEET)} -- run extract_base_game_pool.py "
              "first (needs the local sts2.dll).")
    docs = list(yaml.safe_load_all(EXTRACTOR_SHEET.read_text()))
    if not docs or not isinstance(docs[0], list):
        _fail(f"{EXTRACTOR_SHEET.name}: document 1 is not a card list.")
    return docs[0]


def _dump(obj, header: str, path: Path) -> None:
    body = yaml.safe_dump(obj, sort_keys=False, default_flow_style=False,
                          allow_unicode=True, width=100)
    path.write_text(header + body)


# --- validation shared by build and verify ------------------------------

def _validated_pool_cards() -> list[dict]:
    """doc1 + required supplement layers, validated and sorted by id."""
    doc1 = _doc1_cards()
    d_dup = _dup_ids(doc1)
    if d_dup:
        _fail(f"duplicate ids in extractor doc 1: {d_dup}")
    merged = list(doc1)
    seen = {c["id"]: EXTRACTOR_SHEET.name for c in doc1}
    for path in SUPPLEMENTS:
        if not path.exists():
            _fail(f"missing {_rel(path)} -- refusing to write a partial pool. "
                  "Restore the reviewed local layer; --split can recover it "
                  "only when an existing pool makes its boundary unambiguous.")
        rows = yaml.safe_load(path.read_text()) or []
        if not isinstance(rows, list) or not rows:
            _fail(f"{path.name} is not a non-empty card list.")
        dupes = _dup_ids(rows)
        if dupes:
            _fail(f"duplicate ids in {path.name}: {dupes}")
        overlap = sorted(c["id"] for c in rows if c["id"] in seen)
        if overlap:
            owners = {cid: seen[cid] for cid in overlap}
            _fail(f"{path.name} overlaps earlier layers on {owners} -- stale "
                  "copies must be removed from the later supplement.")
        merged.extend(rows)
        seen.update({c["id"]: path.name for c in rows})
    return sorted(merged, key=lambda c: c["id"])


def _char_facts() -> dict:
    if not CHAR_FACTS.exists():
        _fail(f"missing {_rel(CHAR_FACTS)} -- cannot build the character entry. "
              "Recover it with --split from an existing char_real_ironclad.yaml.")
    facts = yaml.safe_load(CHAR_FACTS.read_text()) or {}
    missing = [k for k in CHAR_FIELDS if k not in facts]
    if missing:
        _fail(f"{CHAR_FACTS.name} missing required fields {missing}.")
    if not facts["starting_deck"]:
        _fail(f"{CHAR_FACTS.name}: starting_deck is empty.")
    return facts


def _validated_upgrades(cards: list[dict]) -> dict[str, dict]:
    """Require complete, applicable upgrade coverage for the merged pool."""
    if not UPGRADES.exists():
        _fail(f"missing {_rel(UPGRADES)} -- rerun extract_base_game_pool.py "
              "with --emit-sheet after restoring every supplement layer.")
    deltas = yaml.safe_load(UPGRADES.read_text()) or {}
    if not isinstance(deltas, dict):
        _fail(f"{UPGRADES.name} is not an id-to-delta mapping.")
    pool_ids = {card["id"] for card in cards}
    upgrade_ids = set(deltas)
    missing = sorted(pool_ids - upgrade_ids)
    extra = sorted(upgrade_ids - pool_ids)
    if missing:
        _fail(f"{UPGRADES.name} missing upgrades for {missing}.")
    if extra:
        _fail(f"{UPGRADES.name} has upgrades outside the pool: {extra}.")
    unexpressible = {}
    for cid, delta in deltas.items():
        if not isinstance(delta, dict):
            unexpressible[cid] = ["delta is not a mapping"]
        elif "_unexpressible" in delta:
            unexpressible[cid] = delta["_unexpressible"]
    if unexpressible:
        _fail(f"{UPGRADES.name} has unexpressible deltas: {unexpressible}.")
    empty = sorted(cid for cid, delta in deltas.items() if not delta)
    if empty:
        _fail(f"{UPGRADES.name} has empty upgrade deltas for {empty}.")
    return deltas


# --- commands -----------------------------------------------------------

def do_split() -> None:
    doc1_ids = {c["id"] for c in _doc1_cards()}
    if POOL.exists():
        pool = yaml.safe_load(POOL.read_text()) or []
        missing = [path for path in SUPPLEMENTS if not path.exists()]
        if len(missing) > 1:
            _fail("multiple supplement layers are missing; the merged pool "
                  "does not preserve pass boundaries, so --split refuses to "
                  "guess. Restore at least all but one reviewed layer.")
        if missing:
            known = set(doc1_ids)
            for path in SUPPLEMENTS:
                if path.exists():
                    known.update(c["id"] for c in
                                 (yaml.safe_load(path.read_text()) or []))
            recovered = sorted((c for c in pool if c["id"] not in known),
                               key=lambda c: c["id"])
            if not recovered:
                _fail(f"cannot recover {missing[0].name}: the existing pool "
                      "contains no cards outside the known layers.")
            _dump(recovered, SUPPLEMENT_HEADER, missing[0])
            print(f"wrote {_rel(missing[0])}: {len(recovered)} recovered cards.")
        else:
            print("all supplement layers already exist; kept them unchanged.")
    else:
        print(f"no {POOL.name}; skipped supplement bootstrap.", file=sys.stderr)
    if CHAR_OUT.exists():
        cur = yaml.safe_load(CHAR_OUT.read_text()) or {}
        facts = {k: cur[k] for k in CHAR_FIELDS if k in cur}
        miss = [k for k in CHAR_FIELDS if k not in facts]
        if miss:
            _fail(f"{CHAR_OUT.name} missing {miss}; cannot bootstrap facts.")
        _dump(facts, CHAR_FACTS_HEADER, CHAR_FACTS)
        print(f"wrote {_rel(CHAR_FACTS)}: character facts "
              f"({facts['hp']} hp, {len(facts['starting_deck'])}-card deck).")
    else:
        print(f"no {CHAR_OUT.name}; skipped char-facts bootstrap.",
              file=sys.stderr)


def do_build() -> None:
    cards = _validated_pool_cards()          # fails closed before any write
    _validated_upgrades(cards)               # 57/57 or no loader artifacts
    facts = _char_facts()                    # fails closed before any write
    _dump(cards, POOL_HEADER, POOL)
    print(f"wrote {_rel(POOL)}: {len(cards)} cards.")
    if CHAR_OUT.exists():
        print(f"kept {_rel(CHAR_OUT)} (hand-authored; not overwritten).")
    else:
        entry = {k: facts[k] for k in CHAR_FIELDS}
        _dump(entry, CHAR_OUT_HEADER, CHAR_OUT)
        print(f"wrote {_rel(CHAR_OUT)}: bootstrapped from char facts.")


def do_verify() -> None:
    if not POOL.exists():
        _fail(f"--verify needs an existing {_rel(POOL)}.")
    current = yaml.safe_load(POOL.read_text()) or []
    cur_dup = _dup_ids(current)
    if cur_dup:
        _fail(f"{POOL.name} has duplicate ids: {cur_dup}")
    rebuilt = _validated_pool_cards()        # validates inputs too
    deltas = _validated_upgrades(rebuilt)
    ok = True
    if [c["id"] for c in current] != [c["id"] for c in rebuilt]:
        ok = False
        cur_ids, new_ids = {c["id"] for c in current}, {c["id"] for c in rebuilt}
        if cur_ids - new_ids:
            print(f"  in pool, not in rebuild: {sorted(cur_ids - new_ids)}")
        if new_ids - cur_ids:
            print(f"  in rebuild, not in pool: {sorted(new_ids - cur_ids)}")
        if cur_ids == new_ids:
            print("  same id set but DIFFERENT ORDER (pool is not sorted by id)")
    else:
        diff = [a["id"] for a, b in zip(current, rebuilt) if a != b]
        if diff:
            ok = False
            print(f"  cards differ in fields: {diff}")
    if not CHAR_OUT.exists():
        ok = False
        print(f"  missing {_rel(CHAR_OUT)} -- real_ironclad cannot instantiate.")
    else:
        cur = yaml.safe_load(CHAR_OUT.read_text()) or {}
        miss = [k for k in CHAR_FIELDS if k not in cur]
        if miss:
            ok = False
            print(f"  {CHAR_OUT.name} missing loader fields {miss}.")
    if ok:
        print(f"VERIFY OK: {len(current)} pool cards match the rebuild "
              f"(ordered, dup-checked); {len(deltas)} upgrades applicable; "
              "char entry loader-complete.")
    else:
        _fail("VERIFY FAILED (see above).")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--split", action="store_true",
                   help="bootstrap the local supplement + char facts from "
                        "existing artifacts")
    g.add_argument("--verify", action="store_true",
                   help="validate the current pool + char entry against a rebuild")
    args = ap.parse_args()
    if args.split:
        do_split()
    elif args.verify:
        do_verify()
    else:
        do_build()
