"""Build game_ref/ironclad_pool.yaml — the loader-shaped real_ironclad pool.

This is the last-mile step the loader docstring names
(extract_base_game_pool.py -> build_ironclad_sheet.py). It exists because the
two artifacts do not line up on their own:

  * extract_base_game_pool.py emits `ironclad-cards.yaml`, a TWO-document sheet
    (document 1 = the 35 cards the JSON extractor could fully express; document
    2 = `excluded:`, the 52 it could not — their power/scaling values are not
    in the JSON, only in the sts2.dll PowerVar/DynamicVar ctor args).
  * loader.EXTERNAL_CARD_SHEETS reads a SINGLE-document list named
    `ironclad_pool.yaml`, and the measured pool is 57 cards = those 35 + 22
    "pass-4" cards whose values were hand-recovered from the DLL ctor args.

So the pool has TWO inputs, and one of them (the pass-4 supplement) is data
the extractor cannot produce. To keep the pipeline reproducible without
committing decompiled data, the split is:

  * COMMITTED (this tool): the merge — doc 1 + supplement -> single-doc pool.
  * LOCAL / gitignored (game_ref/): both data inputs. `ironclad-cards.yaml`
    from the extractor, and `ironclad_pool_pass4.yaml`, the 22 hand-recovered
    cards. Neither ever leaves game_ref/ (.gitignore) — they are base-game
    reference material.

Usage (from repo root):
  python -m tools.build_ironclad_sheet --split   # bootstrap the supplement
  python -m tools.build_ironclad_sheet           # rebuild the pool
  python -m tools.build_ironclad_sheet --verify   # rebuild to a temp + compare

`--split` reads an existing ironclad_pool.yaml and writes back the cards that
are NOT in the extractor's document 1 — i.e. it recovers the local supplement
from a pool you already have, so the two-input pipeline can regenerate it
thereafter. It is how the supplement was first materialised out of the
one-off measurement-run pool.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
GAME_REF = REPO / "game_ref"
EXTRACTOR_SHEET = GAME_REF / "ironclad-cards.yaml"   # 2-doc; we read doc 1
SUPPLEMENT = GAME_REF / "ironclad_pool_pass4.yaml"   # local, gitignored
POOL = GAME_REF / "ironclad_pool.yaml"               # loader input

POOL_HEADER = """\
# MACHINE-GENERATED by tools/build_ironclad_sheet.py -- do not hand-edit.
# loader.EXTERNAL_CARD_SHEETS reads this as a single-document card list.
#
# Two inputs, both LOCAL / gitignored (game_ref/, .gitignore):
#   1. ironclad-cards.yaml document 1  -- the extractor's expressible cards.
#   2. ironclad_pool_pass4.yaml        -- the pass-4 supplement, hand-recovered
#                                         from the sts2.dll ctor args the JSON
#                                         extractor cannot parse.
# Rebuild:  python -m tools.build_ironclad_sheet
"""

SUPPLEMENT_HEADER = """\
# LOCAL ARTIFACT -- game_ref/ is gitignored. The "pass-4" supplement: cards
# recovered by hand from the sts2.dll PowerVar/DynamicVar ctor args that the
# JSON extractor (extract_base_game_pool.py) cannot parse, hence absent from
# ironclad-cards.yaml document 1. Merged with document 1 into ironclad_pool.yaml
# by tools/build_ironclad_sheet.py. Base-game reference: never copy into
# docs/ or tier0/content/.
"""


def _doc1_cards() -> list[dict]:
    if not EXTRACTOR_SHEET.exists():
        sys.exit(f"missing {EXTRACTOR_SHEET.relative_to(REPO)} — run "
                 "extract_base_game_pool.py first (needs the local sts2.dll).")
    docs = list(yaml.safe_load_all(EXTRACTOR_SHEET.read_text()))
    if not docs or not isinstance(docs[0], list):
        sys.exit(f"{EXTRACTOR_SHEET.name}: document 1 is not a card list.")
    return docs[0]


def _dump(cards: list[dict], header: str, path: Path) -> None:
    body = yaml.safe_dump(cards, sort_keys=False, default_flow_style=False,
                          allow_unicode=True, width=100)
    path.write_text(header + body)


def do_split() -> None:
    if not POOL.exists():
        sys.exit(f"--split needs an existing {POOL.name} to recover the "
                 "supplement from.")
    doc1_ids = {c["id"] for c in _doc1_cards()}
    pool = yaml.safe_load(POOL.read_text()) or []
    supp = [c for c in pool if c["id"] not in doc1_ids]
    supp.sort(key=lambda c: c["id"])
    _dump(supp, SUPPLEMENT_HEADER, SUPPLEMENT)
    print(f"wrote {SUPPLEMENT.relative_to(REPO)}: {len(supp)} supplement cards "
          f"({len(pool)} pool - {len(doc1_ids)} extractor).")


def _build_cards() -> list[dict]:
    doc1 = _doc1_cards()
    supp = []
    if SUPPLEMENT.exists():
        supp = yaml.safe_load(SUPPLEMENT.read_text()) or []
    else:
        print(f"WARNING: no {SUPPLEMENT.name}; pool will hold only the "
              f"{len(doc1)} extractor cards, not the measured 57.",
              file=sys.stderr)
    by_id: dict[str, dict] = {}
    for c in doc1 + supp:
        by_id[c["id"]] = c
    return [by_id[k] for k in sorted(by_id)]


def do_build(out: Path = POOL) -> list[dict]:
    cards = _build_cards()
    _dump(cards, POOL_HEADER, out)
    print(f"wrote {out.relative_to(REPO)}: {len(cards)} cards.")
    return cards


def do_verify() -> None:
    if not POOL.exists():
        sys.exit(f"--verify needs an existing {POOL.name} to compare against.")
    current = {c["id"]: c for c in (yaml.safe_load(POOL.read_text()) or [])}
    rebuilt = {c["id"]: c for c in _build_cards()}
    if current == rebuilt:
        print(f"VERIFY OK: rebuild is semantically identical to {POOL.name} "
              f"({len(current)} cards).")
        return
    only_cur = sorted(set(current) - set(rebuilt))
    only_new = sorted(set(rebuilt) - set(current))
    diff_fields = [k for k in current.keys() & rebuilt.keys()
                   if current[k] != rebuilt[k]]
    print("VERIFY FAILED:")
    if only_cur:
        print(f"  in pool, not in rebuild: {only_cur}")
    if only_new:
        print(f"  in rebuild, not in pool: {only_new}")
    if diff_fields:
        print(f"  differing cards: {diff_fields}")
    sys.exit(1)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--split", action="store_true",
                   help="recover the pass-4 supplement from an existing pool")
    g.add_argument("--verify", action="store_true",
                   help="rebuild in memory and compare to the current pool")
    args = ap.parse_args()
    if args.split:
        do_split()
    elif args.verify:
        do_verify()
    else:
        do_build()
