"""Build the loader-shaped real_<character> artifacts from local inputs.

This is the last-mile step the loader docstring names
(extract_base_game_pool.py -> build_official_sheet.py). A faithful loader entry
needs THREE local files, and the card/character pair does not drop out of the
extractor ready to use:

  game_ref/<char>_pool.yaml         -- a SINGLE-document merged card list
  game_ref/<char>-upgrades.yaml     -- one applicable upgrade per pool card
  game_ref/char_real_<char>.yaml    -- the character entry (hp, deck, relics)

Inputs (all LOCAL / gitignored in game_ref/, never committed -- base-game
reference material):

  <char>-cards.yaml          extractor output; TWO docs (doc 1 = the cards the
                             structural extractor can express, doc 2 = the
                             `excluded:` list with per-card reasons).
  <char>_pool_pass*.yaml     ordered, hand-authored tier0-DSL translation
                             layers for cards the strict structural extractor
                             deliberately holds back. These are NOT
                             tool-regenerable: each pass records reviewed
                             design judgment, while numeric values and upgrade
                             deltas still come from the local DLL.
  <char>_char_facts.yaml     the character facts (id/name/hp/starting_deck/
                             relic_hooks), decompiled from the character model.

`<char>-upgrades.yaml` is generated by extract_base_game_pool.py from the
DLL: extractor rows carry their own effect provenance, and the local pass
rows supply provenance for their otherwise-mechanical OnUpgrade recovery.

Only THIS TOOL is committed; every data input stays in game_ref/.

WHY IT IS PARAMETERISED (2026-07-27, Silent anchor sprint)
----------------------------------------------------------
This was `build_ironclad_sheet.py` with its inputs and outputs written into
module constants. A second OFFICIAL anchor needs the same three guarantees
over a different file set, and a clone would have been two copies of the
fail-closed logic drifting apart. The per-character REGISTRY below is the
whole difference: paths follow one naming convention, and the only genuinely
per-character fact is which reviewed supplement layers are REQUIRED -- which
is exactly the fact that must stay explicit, because "required" is what makes
a missing layer an error instead of a smaller pool.

Guarantees (the review findings this closes):
  * FAIL CLOSED. If a required supplement or the char facts are missing, the
    build ERRORS before writing anything -- it never overwrites a full
    reference with a stub of whatever the extractor happened to express.
  * NO SILENT DRIFT. doc 1 and the supplements must be disjoint; any shared id
    is an error (if the extractor starts expressing a card, its stale hand-
    recovered twin must be pruned from the supplement, not silently win).
    Duplicate ids within either input are errors too.
  * HONEST VERIFY. --verify checks the on-disk pool for duplicate ids and
    compares against the rebuild as an ORDERED list (not just id-keyed dicts),
    so ordering and duplication differences surface rather than hide.

Usage (from repo root):
  python -m tools.build_official_sheet --split           # recover one layer
  python -m tools.build_official_sheet                   # rebuild pool
  python -m tools.build_official_sheet --verify          # validate artifacts
  python -m tools.build_official_sheet --character silent --verify

`--character` defaults to ironclad, and `python -m tools.build_ironclad_sheet`
remains a working entry point (klee-mod/build/validate.ps1 calls it).
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
GAME_REF = REPO / "game_ref"

CHAR_FIELDS = ("id", "name", "hp", "starting_deck", "relic_hooks")
# Carried through when the facts declare them, required of nobody. A
# character's own starting relic goes here when it has an AMOUNT on it and so
# cannot be a bare `relic_hooks` string -- Ring of the Snake (ask A1) is
# `combat_start_draw: 2`. Optional rather than required because Ironclad's
# Burning Blood genuinely needs no such entry, and a required-empty field
# would make his facts file lie about having been considered.
CHAR_OPTIONAL_FIELDS = ("starting_relic_effects",)


@dataclass(frozen=True)
class CharacterSpec:
    """Every path one OFFICIAL anchor's assembly touches.

    Paths are derived from the character name because the naming convention
    is already load-bearing elsewhere (the extractor writes `<char>-cards.yaml`,
    the loader reads `<char>_pool.yaml`, the distinctness report globs
    `*_pool.yaml`). They are still FIELDS rather than properties so a test can
    point one spec at a tmp_path without touching the registry.
    """

    character: str
    supplements: tuple[Path, ...]
    extractor_sheet: Path
    char_facts: Path
    pool: Path
    upgrades: Path
    char_out: Path

    @property
    def char_id(self) -> str:
        return f"real_{self.character}"


def spec_for(character: str, supplements: tuple[str, ...],
             root: Path = GAME_REF) -> CharacterSpec:
    char = character.lower()
    return CharacterSpec(
        character=char,
        supplements=tuple(root / name for name in supplements),
        extractor_sheet=root / f"{char}-cards.yaml",   # 2-doc; we read doc 1
        char_facts=root / f"{char}_char_facts.yaml",
        pool=root / f"{char}_pool.yaml",               # loader input
        upgrades=root / f"{char}-upgrades.yaml",       # loader input
        char_out=root / f"char_real_{char}.yaml",      # loader input
    )


# The REQUIRED reviewed layers, per character. Listing them (rather than
# globbing `*_pool_pass*.yaml`) is the fail-closed guarantee itself: a glob
# turns a deleted layer into a quietly smaller pool, which is how game_ref
# was destroyed twice. Adding a pass means adding a line here AND to
# loader.EXTERNAL_CARD_LAYERS -- test_real_silent/test_real_ironclad pin that
# the two lists agree.
CHARACTERS: dict[str, CharacterSpec] = {
    "ironclad": spec_for("ironclad", (
        "ironclad_pool_pass4.yaml",       # 22 reviewed cards
        "ironclad_pool_pass5.yaml",       # engine-ready expansion
        "ironclad_pool_pass6.yaml",       # bounded history/formulas
    )),
    "silent": spec_for("silent", (
        "silent_pool_pass1.yaml",         # discard / poison / dexterity
        "silent_pool_pass2.yaml",         # foreach / conditional / formulas
        "silent_pool_pass3.yaml",         # the Shiv token and its creators
        "silent_pool_pass4.yaml",         # runtime counts + the reward channel
        "silent_pool_pass5.yaml",         # payload powers + self-power reads
    )),
}

POOL_HEADER = """\
# MACHINE-GENERATED by tools/build_official_sheet.py -- do not hand-edit.
# loader.EXTERNAL_CARD_SHEETS reads this as a single-document card list.
# LOCAL inputs (game_ref/, gitignored): {sheet} document 1
# (extractor) + the ordered {char}_pool_pass*.yaml review layers.
# Rebuild:  python -m tools.build_official_sheet --character {char}
"""

SUPPLEMENT_HEADER = """\
# LOCAL ARTIFACT -- game_ref/ is gitignored. Reviewed Tier-0 translations
# absent from {sheet} document 1. Every supplement must stay
# disjoint from document 1 and every other layer. Merged into
# {char}_pool.yaml by build_official_sheet.py.
"""

CHAR_FACTS_HEADER = """\
# LOCAL ARTIFACT -- game_ref/ is gitignored. Decompiled {char} character
# facts (ilspycmd -t MegaCrit.Sts2.Core.Models.Characters.{Char}): StartingHp,
# StartingDeck, StartingRelics. The loader-required fields only;
# build_official_sheet.py emits char_real_{char}.yaml from them.
"""

CHAR_OUT_HEADER = """\
# MACHINE-GENERATED by tools/build_official_sheet.py from local
# game_ref/{char}_char_facts.yaml -- loader-shaped stub. The design rulings
# for real_{char} (why packages/constraints/bands are deliberately absent)
# live in the hand-authored artifact / design notes, not in this generated
# file. LOCAL: never copy into docs/ or tier0/content/.
"""


def _fail(msg: str) -> "None":
    sys.exit(f"build_official_sheet: {msg}")


def _rel(p: Path) -> str:
    try:
        return str(p.relative_to(REPO))
    except ValueError:                       # a tmp_path spec in a test
        return str(p)


def _dup_ids(cards: list[dict]) -> list[str]:
    seen: set[str] = set()
    dupes: list[str] = []
    for c in cards:
        cid = c["id"]
        if cid in seen and cid not in dupes:
            dupes.append(cid)
        seen.add(cid)
    return sorted(dupes)


def _doc1_cards(spec: CharacterSpec) -> list[dict]:
    if not spec.extractor_sheet.exists():
        _fail(f"missing {_rel(spec.extractor_sheet)} -- run "
              f"extract_base_game_pool.py {spec.character.capitalize()} "
              "--emit-sheet first (needs the local sts2.dll).")
    docs = list(yaml.safe_load_all(spec.extractor_sheet.read_text()))
    if not docs or not isinstance(docs[0], list):
        _fail(f"{spec.extractor_sheet.name}: document 1 is not a card list.")
    return docs[0]


def _dump(obj, header: str, path: Path) -> None:
    body = yaml.safe_dump(obj, sort_keys=False, default_flow_style=False,
                          allow_unicode=True, width=100)
    path.write_text(header + body)


# --- validation shared by build and verify ------------------------------

def _validated_pool_cards(spec: CharacterSpec) -> list[dict]:
    """doc1 + required supplement layers, validated and sorted by id."""
    doc1 = _doc1_cards(spec)
    d_dup = _dup_ids(doc1)
    if d_dup:
        _fail(f"duplicate ids in extractor doc 1: {d_dup}")
    merged = list(doc1)
    seen = {c["id"]: spec.extractor_sheet.name for c in doc1}
    for path in spec.supplements:
        if not path.exists():
            _fail(f"missing {_rel(path)} -- refusing to write a partial pool. "
                  "Restore the reviewed local layer; --split can recover it "
                  "only when an existing pool makes its boundary unambiguous.")
        rows = yaml.safe_load(path.read_text()) or []
        if not isinstance(rows, list) or not rows:
            _fail(f"{path.name} is not a non-empty card list.")
        dupes = _dup_ids(rows)
        if dupes:
            _fail(f"duplicate ids in {path.name}: {dupes}")
        overlap = sorted(c["id"] for c in rows if c["id"] in seen)
        if overlap:
            owners = {cid: seen[cid] for cid in overlap}
            _fail(f"{path.name} overlaps earlier layers on {owners} -- stale "
                  "copies must be removed from the later supplement.")
        merged.extend(rows)
        seen.update({c["id"]: path.name for c in rows})
    return sorted(merged, key=lambda c: c["id"])


def _char_facts(spec: CharacterSpec) -> dict:
    if not spec.char_facts.exists():
        _fail(f"missing {_rel(spec.char_facts)} -- cannot build the character "
              f"entry. Recover it with --split from an existing "
              f"{spec.char_out.name}.")
    facts = yaml.safe_load(spec.char_facts.read_text()) or {}
    missing = [k for k in CHAR_FIELDS if k not in facts]
    if missing:
        _fail(f"{spec.char_facts.name} missing required fields {missing}.")
    if not facts["starting_deck"]:
        _fail(f"{spec.char_facts.name}: starting_deck is empty.")
    return facts


def _validated_upgrades(spec: CharacterSpec,
                        cards: list[dict]) -> dict[str, dict]:
    """Require complete, applicable upgrade coverage for the merged pool."""
    if not spec.upgrades.exists():
        _fail(f"missing {_rel(spec.upgrades)} -- rerun extract_base_game_pool.py "
              "with --emit-sheet after restoring every supplement layer.")
    deltas = yaml.safe_load(spec.upgrades.read_text()) or {}
    if not isinstance(deltas, dict):
        _fail(f"{spec.upgrades.name} is not an id-to-delta mapping.")
    pool_ids = {card["id"] for card in cards}
    upgrade_ids = set(deltas)
    missing = sorted(pool_ids - upgrade_ids)
    extra = sorted(upgrade_ids - pool_ids)
    if missing:
        _fail(f"{spec.upgrades.name} missing upgrades for {missing}.")
    if extra:
        _fail(f"{spec.upgrades.name} has upgrades outside the pool: {extra}.")
    unexpressible = {}
    for cid, delta in deltas.items():
        if not isinstance(delta, dict):
            unexpressible[cid] = ["delta is not a mapping"]
        elif "_unexpressible" in delta:
            unexpressible[cid] = delta["_unexpressible"]
    if unexpressible:
        _fail(f"{spec.upgrades.name} has unexpressible deltas: {unexpressible}.")
    empty = sorted(cid for cid, delta in deltas.items() if not delta)
    if empty:
        _fail(f"{spec.upgrades.name} has empty upgrade deltas for {empty}.")
    return deltas


# --- commands -----------------------------------------------------------

def do_split(spec: CharacterSpec) -> None:
    heads = {"sheet": spec.extractor_sheet.name, "char": spec.character,
             "Char": spec.character.capitalize()}
    doc1_ids = {c["id"] for c in _doc1_cards(spec)}
    if spec.pool.exists():
        pool = yaml.safe_load(spec.pool.read_text()) or []
        missing = [path for path in spec.supplements if not path.exists()]
        if len(missing) > 1:
            _fail("multiple supplement layers are missing; the merged pool "
                  "does not preserve pass boundaries, so --split refuses to "
                  "guess. Restore at least all but one reviewed layer.")
        if missing:
            known = set(doc1_ids)
            for path in spec.supplements:
                if path.exists():
                    known.update(c["id"] for c in
                                 (yaml.safe_load(path.read_text()) or []))
            recovered = sorted((c for c in pool if c["id"] not in known),
                               key=lambda c: c["id"])
            if not recovered:
                _fail(f"cannot recover {missing[0].name}: the existing pool "
                      "contains no cards outside the known layers.")
            _dump(recovered, SUPPLEMENT_HEADER.format(**heads), missing[0])
            print(f"wrote {_rel(missing[0])}: {len(recovered)} recovered cards.")
        else:
            print("all supplement layers already exist; kept them unchanged.")
    else:
        print(f"no {spec.pool.name}; skipped supplement bootstrap.",
              file=sys.stderr)
    if spec.char_out.exists():
        cur = yaml.safe_load(spec.char_out.read_text()) or {}
        facts = {k: cur[k] for k in CHAR_FIELDS + CHAR_OPTIONAL_FIELDS
                 if k in cur}
        miss = [k for k in CHAR_FIELDS if k not in facts]
        if miss:
            _fail(f"{spec.char_out.name} missing {miss}; cannot bootstrap facts.")
        _dump(facts, CHAR_FACTS_HEADER.format(**heads), spec.char_facts)
        print(f"wrote {_rel(spec.char_facts)}: character facts "
              f"({facts['hp']} hp, {len(facts['starting_deck'])}-card deck).")
    else:
        print(f"no {spec.char_out.name}; skipped char-facts bootstrap.",
              file=sys.stderr)


def do_build(spec: CharacterSpec) -> None:
    heads = {"sheet": spec.extractor_sheet.name, "char": spec.character,
             "Char": spec.character.capitalize()}
    cards = _validated_pool_cards(spec)      # fails closed before any write
    _validated_upgrades(spec, cards)         # full coverage or no artifacts
    facts = _char_facts(spec)                # fails closed before any write
    _dump(cards, POOL_HEADER.format(**heads), spec.pool)
    print(f"wrote {_rel(spec.pool)}: {len(cards)} cards.")
    if spec.char_out.exists():
        print(f"kept {_rel(spec.char_out)} (hand-authored; not overwritten).")
    else:
        entry = {k: facts[k] for k in CHAR_FIELDS}
        entry.update({k: facts[k] for k in CHAR_OPTIONAL_FIELDS
                      if k in facts})
        _dump(entry, CHAR_OUT_HEADER.format(**heads), spec.char_out)
        print(f"wrote {_rel(spec.char_out)}: bootstrapped from char facts.")


def do_verify(spec: CharacterSpec) -> None:
    if not spec.pool.exists():
        _fail(f"--verify needs an existing {_rel(spec.pool)}.")
    current = yaml.safe_load(spec.pool.read_text()) or []
    cur_dup = _dup_ids(current)
    if cur_dup:
        _fail(f"{spec.pool.name} has duplicate ids: {cur_dup}")
    rebuilt = _validated_pool_cards(spec)    # validates inputs too
    deltas = _validated_upgrades(spec, rebuilt)
    ok = True
    if [c["id"] for c in current] != [c["id"] for c in rebuilt]:
        ok = False
        cur_ids, new_ids = {c["id"] for c in current}, {c["id"] for c in rebuilt}
        if cur_ids - new_ids:
            print(f"  in pool, not in rebuild: {sorted(cur_ids - new_ids)}")
        if new_ids - cur_ids:
            print(f"  in rebuild, not in pool: {sorted(new_ids - cur_ids)}")
        if cur_ids == new_ids:
            print("  same id set but DIFFERENT ORDER (pool is not sorted by id)")
    else:
        diff = [a["id"] for a, b in zip(current, rebuilt) if a != b]
        if diff:
            ok = False
            print(f"  cards differ in fields: {diff}")
    if not spec.char_out.exists():
        ok = False
        print(f"  missing {_rel(spec.char_out)} -- {spec.char_id} cannot "
              "instantiate.")
    else:
        cur = yaml.safe_load(spec.char_out.read_text()) or {}
        miss = [k for k in CHAR_FIELDS if k not in cur]
        if miss:
            ok = False
            print(f"  {spec.char_out.name} missing loader fields {miss}.")
        # char_out is hand-authored and never overwritten, so an optional
        # field added to the facts can silently fail to reach the loader --
        # and a character quietly missing her starting relic is exactly the
        # kind of understatement this anchor exists to avoid.
        facts = _char_facts(spec)            # fails closed if absent
        for key in CHAR_OPTIONAL_FIELDS:
            if facts.get(key) and cur.get(key) != facts[key]:
                ok = False
                print(f"  {spec.char_out.name}: {key} does not match "
                      f"{spec.char_facts.name} ({cur.get(key)!r} vs "
                      f"{facts[key]!r}).")
    if ok:
        print(f"VERIFY OK: {len(current)} pool cards match the rebuild "
              f"(ordered, dup-checked); {len(deltas)} upgrades applicable; "
              "char entry loader-complete.")
    else:
        _fail("VERIFY FAILED (see above).")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--character", default="ironclad",
                    choices=sorted(CHARACTERS),
                    help="which OFFICIAL anchor to assemble (default ironclad)")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--split", action="store_true",
                   help="bootstrap the local supplement + char facts from "
                        "existing artifacts")
    g.add_argument("--verify", action="store_true",
                   help="validate the current pool + char entry against a rebuild")
    args = ap.parse_args(argv)
    spec = CHARACTERS[args.character]
    if args.split:
        do_split(spec)
    elif args.verify:
        do_verify(spec)
    else:
        do_build(spec)
    return 0


if __name__ == "__main__":
    sys.exit(main())
