#!/usr/bin/env python3
"""Codegen for the hidden retired-id aliases (`EB-790`).

    python tools/gen_retired_card_aliases.py           # emit the C#
    python tools/gen_retired_card_aliases.py --check   # CI guard (staleness)

Reads `docs/retired-card-ids.yaml` -- whose header is the WHY, and is the one
place it is written down -- and emits one `RetiredCardAlias` subclass per row
into `klee-mod/KleeCode/Cards/Retired/Generated/`, plus a manifest.

DELIBERATELY NOT A `CharacterProfile`. `tools/gen_klee_cards.py` emits CARDS
from a SHEET: cost, rarity, effects, upgrade, art. An alias has none of those
-- it is an id and a pool pointer -- and routing it through the sheet emitter
would mean inventing sheet fields for a tombstone and teaching every sheet
gate to ignore them. It also must not inherit the emitter's blocked-row and
upgrade-expressibility gates, which ask "can this card ship?" of something
that has already been unshipped.

THE CLASS NAME IS NOT THE ID. Every other generated card in this repo takes
its id from its class name (BaseLib prefixes `ModelDb.GetEntry`, which is
`Slugify(type.Name)`). An alias must claim an id whose class no longer exists,
and often whose name a LIVE class has since re-used, so it names the id
explicitly with BaseLib's `[CustomID]` and takes a `Retired`-prefixed class
name that can never collide. That also makes the id a literal string a reader
can diff against the register and against a godot.log line.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
REGISTER = REPO / "docs" / "retired-card-ids.yaml"
OUT_DIR = REPO / "klee-mod" / "KleeCode" / "Cards" / "Retired" / "Generated"
MANIFEST = OUT_DIR / "manifest.json"
SCRIPT = "tools/gen_retired_card_aliases.py"
NEWLINE = "\n"

PREFIX = "KLEEMOD-"
ENTRY_RE = re.compile(r"^KLEEMOD-[A-Z][A-Z0-9_]*$")
POOLS = {"klee": "KleeCardPool",
         "furina": "FurinaCardPool",
         "kokomi": "KokomiCardPool"}


def rows(path: Path | None = None) -> list[dict]:
    """The register's rows, validated. Read at call time, not import time, so
    the negative tests can point this at a synthetic register."""
    path = path or REGISTER
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    out = doc.get("retired") or []
    seen: set[str] = set()
    for row in out:
        entry = str(row.get("id", ""))
        if not ENTRY_RE.match(entry):
            raise SystemExit(
                f"gen_retired_card_aliases: {entry!r} is not a `KLEEMOD-` "
                f"`ModelId.Entry`. The register holds the id EXACTLY as a save "
                f"holds it -- copy it out of the godot.log line or off the "
                f"class that is being deleted, never retype it.")
        if entry in seen:
            raise SystemExit(f"gen_retired_card_aliases: {entry} listed twice.")
        seen.add(entry)
        if row.get("owner") not in POOLS:
            raise SystemExit(
                f"gen_retired_card_aliases: {entry} has owner "
                f"{row.get('owner')!r}; expected one of {sorted(POOLS)}.")
    return out


def class_name(entry: str) -> str:
    """`KLEEMOD-PROTO_KO_FWOOSH` -> `RetiredProtoKoFwoosh`."""
    body = entry[len(PREFIX):]
    return "Retired" + "".join(part.capitalize() for part in body.split("_"))


def source(row: dict) -> str:
    entry = row["id"]
    pool = POOLS[row["owner"]]
    left = str(row.get("left", "")).replace("*/", "*").replace("\n", " ")
    return f'''// <auto-generated>
//     Generated by {SCRIPT} from docs/retired-card-ids.yaml.
//     DO NOT EDIT. Edits are lost on the next regen -- change the register.
//
//     A TOMBSTONE, not a card: it claims the id {entry} so an
//     old save validates, and does nothing else. See RetiredCardAlias.
//     Left the tree: {left}
// </auto-generated>

#nullable enable

using BaseLib.Utils.Attributes;
using KleeMod.Cards.Retired;
using MegaCrit.Sts2.Core.Models;

namespace KleeMod.Cards.Retired.Generated;

[CustomID("{entry}")]
public sealed class {class_name(entry)} : RetiredCardAlias
{{
    protected override CardPoolModel OwnerPool => ModelDb.CardPool<{pool}>();
}}
'''


def plan(register: Path | None = None) -> tuple[dict[str, str], str]:
    """(filename -> source, manifest bytes). `--check` and the write read the
    same object, which is the property three hand-kept copies could not hold."""
    listed = rows(register)
    generated = {f"{class_name(row['id'])}.cs": source(row) for row in listed}
    manifest = {
        "_comment": (
            f"Generated by {SCRIPT} from docs/retired-card-ids.yaml. One "
            f"hidden alias per retired card id (EB-790): registered in "
            f"ModelDb so a progress save validates, in no card pool, out of "
            f"the card library, and carrying no rule."),
        "aliases": [{"id": row["id"],
                     "class": class_name(row["id"]),
                     "owner": row["owner"]}
                    for row in sorted(listed, key=lambda r: r["id"])],
    }
    return generated, json.dumps(manifest, indent=2) + NEWLINE


def _check(generated: dict[str, str], manifest_src: str) -> int:
    stale = [name for name, src in generated.items()
             if not (OUT_DIR / name).exists()
             or (OUT_DIR / name).read_text(encoding="utf-8") != src]
    extra = sorted({p.name for p in OUT_DIR.glob("*.cs")} - set(generated))
    manifest_stale = (not MANIFEST.exists()
                      or MANIFEST.read_text(encoding="utf-8") != manifest_src)
    if stale or extra or manifest_stale:
        if stale:
            print(f"stale retired aliases: {', '.join(sorted(stale))}",
                  file=sys.stderr)
        if extra:
            print(f"retired alias files with no register row: "
                  f"{', '.join(extra)}", file=sys.stderr)
        if manifest_stale:
            print("stale retired-alias manifest", file=sys.stderr)
        print("run: python tools/gen_retired_card_aliases.py", file=sys.stderr)
        return 1
    print(f"gen_retired_card_aliases: {len(generated)} alias(es) up to date")
    return 0


def _write(generated: dict[str, str], manifest_src: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # Clear first, so a row removed from the register takes its class with it.
    for old in OUT_DIR.glob("*.cs"):
        old.unlink()
    # newline="\n" EXPLICITLY: write_text defaults to os.linesep, which on
    # Windows rewrites every generated file as CRLF against git's LF and shows
    # the whole tree as modified before anyone touched a register.
    for name, src in generated.items():
        (OUT_DIR / name).write_text(src, encoding="utf-8", newline="\n")
    MANIFEST.write_text(manifest_src, encoding="utf-8", newline="\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the emitted C# is not what is committed")
    args = ap.parse_args()
    generated, manifest_src = plan()
    if args.check:
        return _check(generated, manifest_src)
    _write(generated, manifest_src)
    print(f"gen_retired_card_aliases: wrote {len(generated)} alias(es)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
