#!/usr/bin/env python3
"""The sheet comment diet: a card sheet is rows, not an essay.

WHY THIS EXISTS. The docs sheets had drifted into being the project's
long-form memory. `docs/furina-cards.yaml` was 1,024 lines of which 825 were
comment; `docs/kokomi-cards.yaml` 820 of 1,024; `docs/prototype-surface.yaml`
859 of 1,022. Every one of those lines is loaded by any agent that opens the
sheet to change one number, and almost none of it is needed to change that
number. [USER], 2026-09-01: agent-facing docs should not load an agent's
context window with useless information.

The prose was not deleted. It moved to `docs/notes/<sheet>-provenance.md`,
verbatim, keyed by the id of the row it was attached to, so a reader who
wants the argument behind a number still has it one grep away and a reader
who wants the number does not pay for it.

WHAT IS CHECKED. One rule, on comment LINES only:

  * a run of comment-only lines attached to a row may be at most 3 lines;
  * the run at the top of the file -- the header -- may be at most 12.

A trailing comment on a row line (`kaboom: {damage: +3}  # 7->10`) is not a
comment line and is not counted: it sits beside its number, which is where a
short note belongs, and `lint_upgrade_comment_arithmetic` already recomputes
the arithmetic in it.

THE ESCAPE HATCH, AND WHY IT IS PER LINE. Two other lints READ this comment
text -- `lint_sheet_comments` recomputes the numbers quoted in it and
`lint_upgrade_comment_arithmetic` recomputes the `a -> b` pairs -- so a line
can be load-bearing even though it is prose. `# lint-comment-ok` on such a
line drops it from its run's length, leaving the run contiguous. Per line
rather than per block on purpose: a whole-block waiver would switch the diet
off for the block that most needs it, and the marker is meant to name the one
line another gate reads, not to buy the four around it.

  NO LINE CARRIES THE MARKER TODAY. The 2026-09-01 pass moved every long
  block out and both reading lints stayed clean, so the hatch ships unused.
  If you reach for it, say in the same diff which lint reads the line.

SCOPE. `docs/*-cards.yaml`, `docs/*-companions.yaml`, `docs/*-upgrades.yaml`
and `docs/prototype-surface.yaml`. NOT `docs/role-tempo-floors.yaml`: that
file is machine-generated by `tools/canon_role_tempo.py`, header and all, so
a cap on it would fail on prose no one can edit without editing the emitter.

    python tools/lint_sheet_comment_blocks.py
    python tools/lint_sheet_comment_blocks.py docs/klee-cards.yaml [...]

Exit 0 clean; exit 1 with one finding per over-long block.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"

ROW_CAP = 3
HEADER_CAP = 12

PATTERNS = ("*-cards.yaml", "*-companions.yaml", "*-upgrades.yaml")
NAMED = ("prototype-surface.yaml",)

# Machine-generated, header included -- see SCOPE in the docstring.
EXCLUDED = frozenset({"role-tempo-floors.yaml"})

COMMENT = re.compile(r"^\s*#")
MARKER = "lint-comment-ok"


def sheets() -> list[Path]:
    found: list[Path] = []
    for pattern in PATTERNS:
        found.extend(DOCS.glob(pattern))
    found.extend(DOCS / name for name in NAMED)
    return sorted({p for p in found
                   if p.exists() and p.name not in EXCLUDED},
                  key=lambda p: p.name)


def blocks(lines: list[str]) -> list[tuple[int, list[str]]]:
    """[(1-based line number of the first line, the run's lines)]."""
    out: list[tuple[int, list[str]]] = []
    i, n = 0, len(lines)
    while i < n:
        if COMMENT.match(lines[i]):
            j = i
            while j < n and COMMENT.match(lines[j]):
                j += 1
            out.append((i + 1, lines[i:j]))
            i = j
        else:
            i += 1
    return out


def lint_sheet(path: Path) -> tuple[list[str], int, int]:
    text = path.read_text(encoding="utf-8")
    lines = text.replace("\r\n", "\n").split("\n")
    findings: list[str] = []
    runs = blocks(lines)
    comment_lines = sum(len(span) for _, span in runs)
    for lineno, span in runs:
        counted = [line for line in span if MARKER not in line]
        header = lineno == 1
        cap = HEADER_CAP if header else ROW_CAP
        if len(counted) <= cap:
            continue
        where = "the file header" if header else f"the block at line {lineno}"
        findings.append(
            f"{path.name}:{lineno}: {where} is {len(counted)} comment "
            f"line(s), cap {cap}. Move it to "
            f"docs/notes/{path.stem}-provenance.md under the id of the row "
            f"it belongs to, or mark the one line another lint reads "
            f"`# {MARKER}`.")
    return findings, len(runs), comment_lines


def main(argv: list[str]) -> int:
    paths = [Path(a) for a in argv] or sheets()
    findings: list[str] = []
    runs = comments = 0
    for path in paths:
        bad, n_runs, n_comments = lint_sheet(path)
        findings.extend(bad)
        runs += n_runs
        comments += n_comments
    for line in findings:
        print(line)
    # Denominator, not just a verdict: a run that swept no sheet must not
    # read like a clean one (`lint_strict_domination`'s rule).
    print(f"scope: {len(paths)} sheet(s), {runs} comment block(s), "
          f"{comments} comment line(s); cap {ROW_CAP} per row block, "
          f"{HEADER_CAP} for a file header.")
    if findings:
        print(f"{len(findings)} finding(s). A card sheet is rows -- the "
              f"argument behind a number lives in docs/notes/.")
        return 1
    print("sheet comment diet OK.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
