#!/usr/bin/env python3
"""Vendored third-party source has not drifted off its pin.

Opened by the Understudy sprint (2026-08-04) with `vendor/`, which had no
precedent here. The rules it enforces are written down in `vendor/README.md`;
this file is the half that a 3am session cannot skip by not reading.

The check runs in BOTH directions, which is the only reason it is worth
having. A one-directional manifest ("every file I listed is still present and
still hashes to X") never notices a file quietly ADDED to a vendored tree --
and an added file is exactly what an accidental re-clone, a stray build
artifact, or a half-finished local patch looks like. Same shape as art_lint's
L11 and validate.ps1's `$pckDeferred` sweep, for the same reason.

What it asserts, per component under `vendor/<Name>/`:

  1. PROVENANCE.md exists and declares `upstream`, `pin`, `license`. The pin
     must look like a git sha, because "latest" is not a version (R70).
  2. The license is on the permissive list. `vendor/README.md` refuses
     copyleft-that-reaches-our-tree; a lint that only trusted the prose would
     be the structurally-invisible-defect pattern all over again.
  3. LICENSE is present. Upstream's copyright notice travels with the source
     or we are not entitled to carry it.
  4. Every carried file appears in UPSTREAM_MANIFEST.tsv and hashes as listed.
  5. Every manifest row exists on disk. (Direction two.)
  6. `status == upstream` files must NOT contain the `GItS LOCAL EDIT` marker,
     and `status == gits-modified` files MUST. A modified file that forgot to
     say so is the failure mode this catches; so is a marker left behind after
     a change was reverted.
  7. Everything under `gits/` carries `GItS LOCAL ADDITION` and is excluded
     from the upstream manifest entirely -- our code is not upstream's, and
     the hash list should not pretend otherwise.

`--write` regenerates the manifests. It is a deliberate act: read the diff.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
VENDOR = REPO / "vendor"

MANIFEST_NAME = "UPSTREAM_MANIFEST.tsv"
PROVENANCE_NAME = "PROVENANCE.md"

EDIT_MARKER = "GItS LOCAL EDIT"
ADDITION_MARKER = "GItS LOCAL ADDITION"

# Build output and editor droppings are not part of the snapshot.
SKIP_DIRS = {"bin", "obj", "out", "__pycache__", ".vs"}

# vendor/README.md refuses copyleft that reaches our tree; this is that
# refusal in executable form. Widen it with a ruling, not with a commit.
ALLOWED_LICENSES = {"MIT", "BSD-2-Clause", "BSD-3-Clause", "Apache-2.0", "ISC"}

REQUIRED_FIELDS = ("upstream", "pin", "license")
PIN_RE = re.compile(r"^[0-9a-f]{7,40}$")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def components() -> list[Path]:
    if not VENDOR.is_dir():
        return []
    return sorted(p for p in VENDOR.iterdir() if p.is_dir())


def carried_files(root: Path) -> list[Path]:
    """Every file in the snapshot that is claimed to be upstream's.

    Excludes our own additions (`gits/`), the two bookkeeping files, and
    build output.
    """
    out = []
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if rel.parts[0] == "gits":
            continue
        if set(rel.parts) & SKIP_DIRS:
            continue
        if rel.name in (MANIFEST_NAME, PROVENANCE_NAME):
            continue
        out.append(p)
    return out


def gits_files(root: Path) -> list[Path]:
    d = root / "gits"
    if not d.is_dir():
        return []
    return sorted(p for p in d.rglob("*") if p.is_file())


def parse_provenance(path: Path) -> dict[str, str]:
    fields: dict[str, str] = {}
    if not path.exists():
        return fields
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^([a-z][a-z0-9-]*):\s*(.+?)\s*$", line)
        if m and m.group(1) not in fields:
            fields[m.group(1)] = m.group(2)
    return fields


def read_manifest(path: Path) -> dict[str, tuple[str, str]]:
    rows: dict[str, tuple[str, str]] = {}
    if not path.exists():
        return rows
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            continue
        digest, status, rel = parts
        rows[rel] = (digest, status)
    return rows


def write_manifest(root: Path) -> None:
    lines = [
        "# Generated by tools/lint_vendor_pin.py --write. Do not hand-edit.",
        "# sha256\tstatus\tpath   (status: upstream | gits-modified)",
    ]
    for p in carried_files(root):
        rel = p.relative_to(root).as_posix()
        text = ""
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            pass
        status = "gits-modified" if EDIT_MARKER in text else "upstream"
        lines.append(f"{sha256(p)}\t{status}\t{rel}")
    (root / MANIFEST_NAME).write_text("\n".join(lines) + "\n", encoding="utf-8")


def check(root: Path) -> list[str]:
    name = root.name
    findings: list[str] = []

    prov = parse_provenance(root / PROVENANCE_NAME)
    if not prov:
        findings.append(f"{name}: no {PROVENANCE_NAME} (or it declares nothing)")
        return findings

    for field in REQUIRED_FIELDS:
        if field not in prov:
            findings.append(f"{name}: {PROVENANCE_NAME} is missing '{field}:'")

    pin = prov.get("pin", "")
    if pin and not PIN_RE.match(pin):
        findings.append(
            f"{name}: pin '{pin}' is not a git sha. 'latest' is not a version "
            f"-- see vendor/README.md")

    lic = prov.get("license", "")
    if lic and lic not in ALLOWED_LICENSES:
        findings.append(
            f"{name}: license '{lic}' is not on the permissive list "
            f"{sorted(ALLOWED_LICENSES)}. Widening this list is a ruling.")

    if not (root / "LICENSE").exists() and not (root / "LICENSE.md").exists():
        findings.append(f"{name}: upstream LICENSE is not carried alongside the source")

    manifest = read_manifest(root / MANIFEST_NAME)
    if not manifest:
        findings.append(
            f"{name}: no {MANIFEST_NAME}. Run: python tools/lint_vendor_pin.py --write")
        return findings

    on_disk = {p.relative_to(root).as_posix(): p for p in carried_files(root)}

    # Direction one: the tree against the list.
    for rel, path in sorted(on_disk.items()):
        if rel not in manifest:
            findings.append(
                f"{name}: '{rel}' is in the tree but not in {MANIFEST_NAME} "
                f"-- an unrecorded file in a pinned snapshot")
            continue
        digest, status = manifest[rel]
        actual = sha256(path)
        if actual != digest:
            findings.append(
                f"{name}: '{rel}' hash {actual[:12]} != recorded {digest[:12]} "
                f"-- the snapshot has drifted off its pin")
        text = ""
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            pass
        marked = EDIT_MARKER in text
        if status == "upstream" and marked:
            findings.append(
                f"{name}: '{rel}' carries a {EDIT_MARKER} marker but is "
                f"recorded as untouched upstream")
        if status == "gits-modified" and not marked:
            findings.append(
                f"{name}: '{rel}' is recorded as gits-modified but carries no "
                f"in-file {EDIT_MARKER} marker")
        if status not in ("upstream", "gits-modified"):
            findings.append(f"{name}: '{rel}' has unknown status '{status}'")

    # Direction two: the list against the tree.
    for rel in sorted(manifest):
        if rel not in on_disk:
            findings.append(
                f"{name}: {MANIFEST_NAME} lists '{rel}' but it is not in the tree")

    # Our own additions announce themselves.
    for path in gits_files(root):
        rel = path.relative_to(root).as_posix()
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if ADDITION_MARKER not in text:
            findings.append(
                f"{name}: '{rel}' is ours but carries no {ADDITION_MARKER} header")

    return findings


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true",
                    help="regenerate UPSTREAM_MANIFEST.tsv for every component")
    args = ap.parse_args()

    comps = components()
    if not comps:
        # Not a failure: the repo carried no vendored source before 2026-08-04
        # and may carry none again. Say so rather than printing a bare CLEAN.
        print("vendor pin lint: no components under vendor/ -- nothing to check")
        return 0

    if args.write:
        for root in comps:
            write_manifest(root)
            print(f"wrote {root.name}/{MANIFEST_NAME}")
        return 0

    findings = []
    for root in comps:
        findings += check(root)

    scope = ", ".join(
        f"{r.name} ({len(carried_files(r))} carried, {len(gits_files(r))} ours)"
        for r in comps)
    if findings:
        for f in findings:
            print(f"FINDING {f}")
        print(f"\nvendor pin lint: {len(findings)} finding(s) over {scope}")
        return 1

    print(f"vendor pin lint CLEAN over {scope}")
    print("scope (what this lint has NO opinion about): whether the pin is the "
          "RIGHT commit, whether upstream still exists, and whether the built "
          "dll matches the source -- those are a human's, a clone's and "
          "deploy_bridge.ps1's jobs respectively.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
