#!/usr/bin/env python3
r"""Remove a git worktree, and REFUSE if it is holding gitignored data.

**THE REFUSAL IS THE POINT** -- read it the same way `tools/backup_game_ref.py`
asks to be read. `git worktree remove` deletes GITIGNORED CONTENT out of a
CLEAN worktree. `git status` says clean because ignored files are ignored, so a
worktree holding the only copy of something looks empty to git and is removed
whole. **On 2026-08-24 a routine purge of stale worktrees took both surviving
`game_ref/` backups this way** (BACKLOG `EB-128`), which is how one deletion
became a fourth total loss of a decompile-derived, hand-layered tree that
cannot be committed and cannot be restored from history.

So this wrapper asks the one question `git worktree remove` does not:

    git -C <worktree> status --ignored --porcelain   ->   the `!!` lines

Every ignored path is classified against `EXPECTED`, an explicit allowlist of
gitignored things a worktree is *supposed* to grow -- build outputs, caches,
`klee-mod/local.props`, packaged binaries. Anything else stops the removal
(exit 2) and is printed by name. `--acknowledge` is the door: it says "I have
read that list and those files may die", and it is deliberately a flag you
have to type after seeing the list rather than one you can set and forget.

    python -m tools.purge_worktree ../GItS-foo             # check, then remove
    python -m tools.purge_worktree ../GItS-foo --dry-run   # check only
    python -m tools.purge_worktree ../GItS-foo --acknowledge

EXIT CODES: 0 removed (or clean under `--dry-run`), 2 REFUSED, 1 the removal
itself failed. A refusal is always exit 2 and always names what it found.

WHAT THIS TOOL NEVER DOES. It never deletes a file itself: the only removal is
`git worktree remove`, run as a subprocess, and every check happens before it.
It never touches the MAIN worktree -- the target must appear in
`git worktree list` as a linked worktree, so a mistyped path is a refusal
rather than a repository. And it never *repairs* anything it finds: the answer
to `game_ref/` living in a worktree is to move it out and back it up
(`tools/backup_game_ref.py`), which is a decision, not a cleanup step.

THE ALLOWLIST IS A LIST OF THINGS THAT ARE CHEAP TO LOSE, and that is the only
test for membership. `*.zip` is NOT on it although the repo ignores it: raw art
zips are shared out of band and a lost one is a request to somebody else.
`game_ref/`, `sts2_decompiled/`, `art/raw/`, `ImageGen/images/` and the capture
packets are not on it for the same reason, spelled out in `.gitignore` itself.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from fnmatch import fnmatch
from pathlib import Path

# --------------------------------------------------------------------------
# Gitignored paths a worktree is EXPECTED to grow. Membership means exactly
# one thing: losing this costs a rebuild, not a person's work or a tree that
# cannot be regenerated. A trailing slash means "a directory with this name at
# any depth"; everything else is matched against the basename as a glob.
#
# Anything not listed here is UNEXPECTED and stops the purge. That default is
# the whole mechanism -- a new ignored artifact is refused until somebody says
# out loud which side of the line it is on.
EXPECTED: tuple[str, ...] = (
    # Python / test caches and environments.
    ".venv/", "__pycache__/", ".pytest_cache/", "*.pyc", ".mypy_cache/",
    # C# build outputs and the machine-local build pointer (csharp-build-spec
    # §0.3). `local.props` names THIS machine's Steam install and is rewritten
    # by the build; it is the canonical cheap-to-lose ignored file.
    "local.props", "bin/", "obj/", "dist/", "*.user",
    # Packaged / compiled binaries, all regenerated by tools/build_pck.ps1.
    "*.pck", "*.pck.contract.txt", "*.dll", "*.pdb",
    # Locally rendered eyeball views and scratch tables.
    "card_gallery.html", "art/contact_sheet.html", "art/contact_sheet_*.html",
    "*.csv",
    # Soak/frame output. The COMMITTED phase0 logs are not ignored and so are
    # never in this list; these two directories are per-session scratch.
    "understudy/logs/soak/", "understudy/logs/frames/",
    # OS litter.
    ".DS_Store", "Thumbs.db",
)

# Ignored paths whose loss is the incident this tool exists for. They are
# refused like anything unlisted; naming them buys a LOUDER message and the
# restore point, which is the difference between "are you sure" and "here is
# what to do first".
IRREPLACEABLE: dict[str, str] = {
    "game_ref": ("decompile-derived, hand-layered, CANNOT be committed and "
                 "CANNOT be restored from history. Back it up with "
                 "`python -m tools.backup_game_ref` and move it out of this "
                 "worktree BEFORE removing anything (BACKLOG EB-128)"),
    "game_ref_backup": ("a `game_ref/` backup -- exactly what the 2026-08-24 "
                        "purge destroyed. Backups never live in worktrees "
                        "(OPERATIONS.md); the vault is the restore point"),
    "sts2_decompiled": "decompiled base-game material, re-extracted by hand",
    "game_assets": "extracted base-game assets, re-extracted by hand",
    "art": "Tier F art (art/raw, art/candidates, the capture packets)",
    "ImageGen": "generated art source (ImageGen/images)",
    ".sentinel": "patch_sentinel snapshots of base-game material",
    "docs": "local-only design mockups (docs/mockups)",
}


class Refusal(Exception):
    """A condition that stops the removal. Always exit 2, always named."""


def _git(args: list[str], cwd: Path | None = None) -> str:
    proc = subprocess.run(["git", *args], cwd=str(cwd) if cwd else None,
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise Refusal(f"git {' '.join(args)} failed: "
                      f"{(proc.stderr or proc.stdout).strip()}")
    return proc.stdout


def is_expected(path: str) -> bool:
    """Is this ignored path one of the cheap-to-lose kinds?

    `path` is a `git status --ignored --porcelain` payload: forward slashes,
    relative to the worktree root, with a TRAILING SLASH when git collapsed a
    wholly-ignored directory into one entry.
    """
    entry = path.strip().strip("/")
    if not entry:
        return False
    parts = entry.split("/")
    for pattern in EXPECTED:
        if pattern.endswith("/"):
            stem = pattern.rstrip("/")
            if "/" in stem:
                if entry == stem or entry.startswith(stem + "/"):
                    return True
            elif stem in parts:
                return True
        elif "/" in pattern:
            if fnmatch(entry, pattern):
                return True
        elif fnmatch(parts[-1], pattern):
            return True
    return False


# A collapsed directory holding nothing but expected files is expected. Above
# this many files it is reported UNEXPECTED unopened -- a refusal that costs a
# `--acknowledge` is cheaper than a purge that walks a hundred thousand paths.
WALK_BUDGET = 5000


def _dir_holds_only_expected(worktree: Path, rel: str) -> bool:
    """Does this collapsed ignored directory hold only cheap-to-lose files?

    `git status --ignored --porcelain` reports the SHALLOWEST directory whose
    every entry is ignored, so a worktree where `klee-mod/` itself is untracked
    reports `klee-mod/` and not `klee-mod/KleeCode/bin/`. Classifying the
    collapsed name alone would refuse a worktree holding nothing but build
    output, and a guard that refuses everything is a guard people route
    around. So the directory is opened and judged on what is actually in it.
    """
    root = (worktree / rel)
    if not root.is_dir():
        return False
    seen = 0
    for path in root.rglob("*"):
        if path.is_dir():
            continue
        seen += 1
        if seen > WALK_BUDGET:
            return False
        inner = f"{rel.rstrip('/')}/{path.relative_to(root).as_posix()}"
        if not is_expected(inner):
            return False
    return True                     # an empty ignored directory loses nothing


def why_irreplaceable(path: str) -> str | None:
    """The loud note for a path this repo has already lost once, or None."""
    head = path.strip().strip("/").split("/")[0]
    return IRREPLACEABLE.get(head)


def ignored_paths(worktree: Path) -> list[str]:
    """The `!!` lines of `git status --ignored --porcelain`, payloads only."""
    out = _git(["status", "--ignored", "--porcelain"], cwd=worktree)
    found = []
    for line in out.splitlines():
        if line.startswith("!! "):
            payload = line[3:].strip()
            # Paths with unusual characters come back quoted; the quotes are
            # git's, not part of the name.
            if len(payload) > 1 and payload[0] == '"' and payload[-1] == '"':
                payload = payload[1:-1]
            found.append(payload)
    return sorted(found)


def linked_worktrees(repo: Path) -> list[Path]:
    """Every LINKED worktree of `repo` -- the main one is excluded.

    `git worktree list --porcelain` prints the main worktree first. Excluding
    it here is what makes a mistyped path a refusal instead of a repository.
    """
    out = _git(["worktree", "list", "--porcelain"], cwd=repo)
    paths = [line[len("worktree "):].strip()
             for line in out.splitlines() if line.startswith("worktree ")]
    return [Path(p).resolve() for p in paths[1:]]


def check(worktree: Path, repo: Path) -> list[str]:
    """Return the UNEXPECTED ignored paths, or raise a Refusal.

    Raising covers the questions that are not about content at all: is this a
    worktree, is it THIS repository's, is it the main checkout.
    """
    worktree = worktree.resolve()
    if not worktree.is_dir():
        raise Refusal(f"{worktree} is not a directory")
    known = linked_worktrees(repo)
    if worktree not in known:
        raise Refusal(
            f"{worktree} is not a linked worktree of {repo}. "
            f"`git worktree list` knows: "
            f"{', '.join(str(p) for p in known) or '(none)'}. "
            f"This tool never removes the main checkout and never deletes a "
            f"plain directory")
    unexpected = []
    for path in ignored_paths(worktree):
        if is_expected(path):
            continue
        if (worktree / path).is_dir() and _dir_holds_only_expected(worktree,
                                                                   path):
            continue
        unexpected.append(path)
    return unexpected


def report(worktree: Path, unexpected: list[str]) -> str:
    lines = [f"REFUSING to remove {worktree}",
             "",
             f"`git worktree remove` would DELETE {len(unexpected)} "
             f"gitignored path(s) this tool was not told to expect. git "
             f"reports the worktree clean because ignored files are ignored:",
             ""]
    for path in unexpected:
        note = why_irreplaceable(path)
        lines.append(f"  !! {path}")
        if note:
            lines.append(f"     ^^ {note}")
    lines += [
        "",
        "Move anything you care about OUT of the worktree first (backups "
        "never live in worktrees -- OPERATIONS.md), then either re-run with "
        "--acknowledge or add the path to EXPECTED in this file if it is "
        "genuinely cheap to lose.",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("worktree", help="path to the worktree to remove")
    ap.add_argument("--repo", default=None,
                    help="the repository whose worktree list is authoritative "
                         "(default: this script's own checkout)")
    ap.add_argument("--dry-run", action="store_true",
                    help="run every check and remove nothing")
    ap.add_argument("--acknowledge", action="store_true",
                    help="I have read the list of unexpected ignored paths "
                         "and they may be deleted")
    ap.add_argument("--force", action="store_true",
                    help="passed through to `git worktree remove` for a "
                         "worktree with TRACKED modifications. It has no "
                         "effect on this tool's own ignored-data refusal")
    args = ap.parse_args(argv)

    repo = Path(args.repo).resolve() if args.repo \
        else Path(__file__).resolve().parent.parent
    worktree = Path(args.worktree)
    try:
        unexpected = check(worktree, repo)
    except Refusal as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2

    worktree = worktree.resolve()
    if unexpected and not args.acknowledge:
        print(report(worktree, unexpected), file=sys.stderr)
        return 2
    if unexpected:
        print(f"--acknowledge: deleting {len(unexpected)} unexpected ignored "
              f"path(s) with the worktree:")
        for path in unexpected:
            print(f"  !! {path}")
    if args.dry_run:
        print(f"DRY RUN: {worktree} would be removed"
              + (" (acknowledged)" if unexpected else " (nothing unexpected)"))
        return 0

    cmd = ["worktree", "remove", str(worktree)] + (["--force"]
                                                   if args.force else [])
    try:
        _git(cmd, cwd=repo)
    except Refusal as exc:
        print(f"removal failed: {exc}", file=sys.stderr)
        return 1
    print(f"removed {worktree}")
    return 0


if __name__ == "__main__":                                # pragma: no cover
    raise SystemExit(main())
