"""First-pass role x tempo tags for the three GItS sheets -> a REVIEW column.

Track A / T2 (docs/track-a-kickoff-brief.md). Writes:

  docs/role-tempo-review.tsv    every card, authored `solve` beside the
                                suggested one, plus the new `tempo_band`
                                proposal and the tag-through trail.
  docs/role-tempo-tagthrough.md the token -> roles-cashed-into table, per
                                fight band, per character.

THIS TOOL WRITES NOTHING TO A SHEET, and that is a rule rather than a
convenience. `solve` is a ratified field on three ratified sheets; a token's
payoff set is a DESIGN FACT, not a code fact; and the charter puts both behind
[USER] gate A-G1. So the suggestions land in their own file, clearly labelled
provisional, and the lint that reads them says so on every line of its output
until the gate closes.

WHAT A DIVERGENCE MEANS (and what it does not)
-----------------------------------------------
The review file flags every card where the suggested `solve` differs from the
authored one. A divergence is NOT an error on either side. Three of them are
already known to be systematic and are the most useful thing in the file:

  * the sheets tag a damage card that reads a meter as `frontload` in some
    places and `scaling, frontload` in others (applause_line vs crescendo vs
    all_streams_flow). The suggester is consistent; the sheets are not, and
    that inconsistency predates this track.
  * the sheets use `utility` for enemy debuffs AND for deck manipulation AND
    for "I could not think of one". A0.2 protects that space, so the
    suggester never argues with a `utility` tag -- it only adds what it can
    see beside it.
  * a carrier's inherited roles are new information by construction. No sheet
    row was ever tagged with what its token cashes into, so every carrier
    diverges, and that IS the tag-through rule doing its job.

USAGE
-----
    python tools/suggest_role_tempo_tags.py
    python tools/suggest_role_tempo_tags.py --check   # CI: is the file stale?
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from tools import role_tempo as rt              # noqa: E402

REVIEW = REPO / "docs" / "role-tempo-review.tsv"
TAGTHROUGH = REPO / "docs" / "role-tempo-tagthrough.md"

COLUMNS = ("character", "id", "rarity", "archetypes", "role",
           "solve_authored", "solve_suggested", "diverges",
           "tempo_fight", "tempo_run", "aoe",
           "generates", "reads", "inherited_early", "inherited_mid",
           "inherited_late")


def build() -> tuple[str, str]:
    rows_out = ["\t".join(COLUMNS)]
    payoff_tables: dict[str, dict] = {}
    for character, path in rt.SHEETS.items():
        rows = rt.load_rows(path)
        scans, payoffs = rt.classify_pool(rows, character)
        payoff_tables[character] = payoffs
        for row in rows:
            scan = scans[row["id"]]
            authored = sorted(row.get("solve") or [])
            suggested = scan["solve"]
            rows_out.append("\t".join((
                character,
                row["id"],
                str(row.get("rarity", "")),
                ",".join(row.get("archetypes") or []),
                str(row.get("role", "")),
                ",".join(authored),
                ",".join(suggested),
                "YES" if authored != suggested else "",
                ",".join(scan["fight"]),
                ",".join(scan["run"]),
                "aoe" if scan["aoe"] else "",
                ",".join(sorted(scan["generates"])),
                ",".join(sorted(scan["reads"])),
                ",".join(sorted(scan["inherited"]["early"])),
                ",".join(sorted(scan["inherited"]["mid"])),
                ",".join(sorted(scan["inherited"]["late"])),
            )))

    doc = [
        "# Tag-through: what each token cashes into",
        "",
        "MACHINE-GENERATED by `tools/suggest_role_tempo_tags.py`. Charter",
        "A0.1: *a mechanic-carrier card inherits the `solve` roles its token or",
        "resource cashes into.* This is that table, and it is the artifact",
        "[USER] gate **A-G1** exists to review — a token's payoff set is a",
        "design fact, so the machine may propose it and may not ratify it.",
        "",
        "**PROVISIONAL until A-G1 closes.** Nothing here has been written to a",
        "sheet.",
        "",
        "## How to read a row",
        "",
        "Each cell lists the roles a card that GENERATES this token thereby",
        "inherits, at that fight band. **An empty cell is the finding**, not a",
        "tagging failure: the charter's corollary says a carrier that inherits",
        "no role at a band is a structural defect of the *resource*.",
        "",
        "Two derivations feed this table and they are not interchangeable:",
        "",
        "- **METERS** (`fanfare`, `encore`, `charge`, `burst`, `exhaust_pile`,",
        "  `salon_member` as a stage counter) are DERIVED. The payoff set is",
        "  the union of what the meter's readers deliver, at the band those",
        "  readers are live at, attributed per effect — a reader that both",
        "  reads the meter and does something unrelated credits the meter only",
        "  with the line that actually read it.",
        "- **ENTITIES** (typed Salon members, bombs, the Bake-Kurage, sparks,",
        "  the Spotlight, auras) are HAND-AUTHORED in",
        "  `tools/role_tempo.py::ENTITY_PAYOFFS`, because an entity acts on its",
        "  own schedule and no card reads it. Each entry there carries one line",
        "  of provenance quoting the sheet that defines it. Those lines are the",
        "  ones to argue with.",
        "",
    ]
    for character, payoffs in payoff_tables.items():
        rows = rt.load_rows(rt.SHEETS[character])
        used = set()
        for row in rows:
            used |= rt.scan_row(row, character)["generates"]
        if not used:
            continue
        doc += [f"## {character}", "",
                "| token | fight: early | fight: mid | fight: late |",
                "|---|---|---|---|"]
        for token in sorted(used):
            table = payoffs.get(token, {b: set() for b in rt.FIGHT_BANDS})
            cells = []
            for band in rt.FIGHT_BANDS:
                roles = sorted(table[band] - {"utility"})
                cells.append(", ".join(f"`{r}`" for r in roles)
                             or "**— nothing —**")
            doc.append(f"| `{token}` | " + " | ".join(cells) + " |")
        doc.append("")
    return "\n".join(rows_out) + "\n", "\n".join(doc)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed files are stale")
    args = ap.parse_args(argv)
    tsv, doc = build()
    if args.check:
        stale = [p.name for p, want in ((REVIEW, tsv), (TAGTHROUGH, doc))
                 if not p.exists()
                 or p.read_text(encoding="utf-8").replace("\r\n", "\n") != want]
        if stale:
            print("STALE: " + ", ".join(stale)
                  + "  -- rerun tools/suggest_role_tempo_tags.py")
            return 1
        print("role/tempo review artifacts are current")
        return 0
    REVIEW.write_text(tsv, encoding="utf-8")
    TAGTHROUGH.write_text(doc, encoding="utf-8")
    n = tsv.count("\n") - 1
    diverge = sum(1 for line in tsv.splitlines()[1:]
                  if line.split("\t")[7] == "YES")
    print(f"  wrote {REVIEW.relative_to(REPO)} ({n} cards, "
          f"{diverge} diverging from the authored solve)")
    print(f"  wrote {TAGTHROUGH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
