"""The role x tempo tags for the three GItS sheets: derive, land, and pin.

Track A / T2 (docs/track-a-kickoff-brief.md). Writes:

  docs/role-tempo-review.tsv    every card, the sheet's `solve` beside the
                                derived one, the `tempo_band` landing, and the
                                tag-through trail.
  docs/role-tempo-tagthrough.md the token -> roles-cashed-into table, per
                                fight band, per character, with each meter's
                                bounded/unbounded property (R91/2b).

A-G1 IS CLOSED (2026-08-04) AND THE TAGS HAVE LANDED
-----------------------------------------------------
This tool used to refuse to touch a sheet, because `solve` is a ratified field
and a token's payoff set is a DESIGN FACT that the machine may propose and may
not ratify. [USER] ratified it: `docs/axis-validity-countersign-2026-08-04.md`,
recorded as R91. So `--land` now exists and writes both fields onto the three
sheets, and the REVIEW COLUMN RETIRES -- `diverges` is empty on every row the
moment the sheets and the classifier agree.

That inverts what the file is for. It was a proposal awaiting a gate; it is now
a PARITY ARTIFACT. `--check` fails when a sheet and the classifier disagree,
which is the drift gate: hand-edit a `solve` on a sheet without changing the
rule that produced it and CI says so.

WHAT LANDED, in one paragraph
------------------------------
R91/2a confirmed the seven ENTITY_PAYOFFS as proposed. R91/2b kept the
salon_member double-credit and added the bounded/unbounded property to every
meter, caps read from `tier0/constants.py`. R91/2c settled the question most of
the 135 divergences rode on: a damage card that reads a meter is `scaling`, and
also `frontload` only if it deals damage with the meter at zero. R91/2d fixed
the sustain boundary (your own HP ledger only) and put `sustain` on the
never-linted list beside `utility` and `support`.

USAGE
-----
    python tools/suggest_role_tempo_tags.py           # refresh the artifacts
    python tools/suggest_role_tempo_tags.py --land    # write the three sheets
    python tools/suggest_role_tempo_tags.py --check   # CI: artifacts + sheets
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from tools import role_tempo as rt              # noqa: E402

REVIEW = REPO / "docs" / "role-tempo-review.tsv"
TAGTHROUGH = REPO / "docs" / "role-tempo-tagthrough.md"

COLUMNS = ("character", "id", "rarity", "archetypes", "role",
           "solve_authored", "solve_suggested", "diverges",
           "tempo_fight", "tempo_run", "aoe",
           "generates", "reads", "inherited_early", "inherited_mid",
           "inherited_late")


def build() -> tuple[str, str]:
    rows_out = ["\t".join(COLUMNS)]
    payoff_tables: dict[str, dict] = {}
    for character, path in rt.SHEETS.items():
        rows = rt.load_rows(path)
        scans, payoffs = rt.classify_pool(rows, character)
        payoff_tables[character] = payoffs
        for row in rows:
            scan = scans[row["id"]]
            authored = sorted(row.get("solve") or [])
            suggested = scan["solve"]
            rows_out.append("\t".join((
                character,
                row["id"],
                str(row.get("rarity", "")),
                ",".join(row.get("archetypes") or []),
                str(row.get("role", "")),
                ",".join(authored),
                ",".join(suggested),
                "YES" if authored != suggested else "",
                ",".join(scan["fight"]),
                ",".join(scan["run"]),
                "aoe" if scan["aoe"] else "",
                ",".join(sorted(scan["generates"])),
                ",".join(sorted(scan["reads"])),
                ",".join(sorted(scan["inherited"]["early"])),
                ",".join(sorted(scan["inherited"]["mid"])),
                ",".join(sorted(scan["inherited"]["late"])),
            )))

    doc = [
        "# Tag-through: what each token cashes into",
        "",
        "MACHINE-GENERATED by `tools/suggest_role_tempo_tags.py`. Charter",
        "A0.1: *a mechanic-carrier card inherits the `solve` roles its token or",
        "resource cashes into.* This is that table, and it is the artifact",
        "[USER] gate **A-G1** existed to review — a token's payoff set is a",
        "design fact, so the machine may propose it and may not ratify it.",
        "",
        "**A-G1 CLOSED 2026-08-04** "
        "(`docs/axis-validity-countersign-2026-08-04.md`, recorded as R91).",
        "The seven `ENTITY_PAYOFFS` were confirmed as proposed; the",
        "`salon_member` double-credit was kept; these tags are LANDED on the",
        "three sheets and this file is now the parity record, not a proposal.",
        "",
        "## Meters: bounded or unbounded (R91/2b)",
        "",
        "[USER]'s amendment to the double-credit. A card that reads a CAPPED",
        "meter may really be *frontload after a setup tax* rather than true",
        "scaling — which depends on how fast the meter fills, and that is",
        "unmeasured. The tags stay as proposed and the property becomes",
        "visible instead, so the revisit has something to key on. Canon's",
        "precedents, both named in the ruling: orb slots are the bounded one,",
        "Focus (and Strength) the unbounded one.",
        "",
        "| meter | bounded? | cap | read from | why |",
        "|---|---|---|---|---|",
    ]
    for token in sorted(rt.METERS):
        bounded, value, const = rt.meter_cap(token)
        _b, _c, why = rt.METERS[token]
        cap = "—" if value is None else f"`{value}`"
        src = f"`tier0.constants.{const}`" if const else "— (no cap constant)"
        doc.append(f"| `{token}` | {'BOUNDED' if bounded else 'unbounded'} | "
                   f"{cap} | {src} | {why} |")
    doc += [
        "",
        "**Pre-registered in Track B (R91/2b):** the Salon fill-time",
        "measurement — *the turn the Salon first fills*, and *the fraction of",
        "fight-turns it sits full*. If bounded-meter readers plateau early on",
        "Track B's output curves, the `scaling` tag for those readers gets",
        "revisited with data in hand. Not revisited before then, and not on",
        "anybody's intuition.",
        "",
        "## How to read a row",
        "",
        "Each cell lists the roles a card that GENERATES this token thereby",
        "inherits, at that fight band. **An empty cell is the finding**, not a",
        "tagging failure: the charter's corollary says a carrier that inherits",
        "no role at a band is a structural defect of the *resource*.",
        "",
        "Two derivations feed this table and they are not interchangeable:",
        "",
        "- **METERS** (`fanfare`, `encore`, `charge`, `burst`, `exhaust_pile`,",
        "  `salon_member` as a stage counter) are DERIVED. The payoff set is",
        "  the union of what the meter's readers deliver, at the band those",
        "  readers are live at, attributed per effect — a reader that both",
        "  reads the meter and does something unrelated credits the meter only",
        "  with the line that actually read it.",
        "- **ENTITIES** (typed Salon members, bombs, the Bake-Kurage, sparks,",
        "  the Spotlight, auras) are HAND-AUTHORED in",
        "  `tools/role_tempo.py::ENTITY_PAYOFFS`, because an entity acts on its",
        "  own schedule and no card reads it. Each entry there carries one line",
        "  of provenance quoting the sheet that defines it. Those lines are the",
        "  ones to argue with.",
        "",
    ]
    for character, payoffs in payoff_tables.items():
        rows = rt.load_rows(rt.SHEETS[character])
        used = set()
        for row in rows:
            used |= rt.scan_row(row, character)["generates"]
        if not used:
            continue
        doc += [f"## {character}", "",
                "| token | fight: early | fight: mid | fight: late |",
                "|---|---|---|---|"]
        for token in sorted(used):
            table = payoffs.get(token, {b: set() for b in rt.FIGHT_BANDS})
            cells = []
            for band in rt.FIGHT_BANDS:
                roles = sorted(table[band] - {"utility"})
                cells.append(", ".join(f"`{r}`" for r in roles)
                             or "**— nothing —**")
            doc.append(f"| `{token}` | " + " | ".join(cells) + " |")
        doc.append("")
    return "\n".join(rows_out) + "\n", "\n".join(doc)


# --- landing (A-G1 closed; R91) ---------------------------------------------

ROW = re.compile(r"^- \{id: (?P<id>\w+),")
SOLVE_FIELD = re.compile(r"solve: \[[^\]]*\]")
TEMPO_FIELD = re.compile(r", tempo_band: \{[^}]*\}")


def _render(scan: dict) -> tuple[str, str]:
    solve = "solve: [" + ", ".join(scan["solve"]) + "]"
    tempo = (", tempo_band: {fight: [" + ", ".join(scan["fight"])
             + "], run: [" + ", ".join(scan["run"]) + "]}")
    return solve, tempo


def land() -> int:
    """Write `solve` and `tempo_band` onto the three sheets, in place.

    TEXTUAL, not a YAML round-trip, and that is not laziness: these sheets are
    the design record and every one of them carries more comment than data --
    provenance lines, ruling references, red-pen history. `yaml.dump` would
    reformat 219 rows and delete all of it. Every row on all three sheets
    carries `solve: [...]` on its own `- {id: ...}` line (checked, 219/219), so
    a line-scoped substitution is exact.
    """
    touched = 0
    for character, path in rt.SHEETS.items():
        rows = rt.load_rows(path)
        scans, _ = rt.classify_pool(rows, character)
        lines = path.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            m = ROW.match(line)
            if not m or m.group("id") not in scans:
                continue
            solve, tempo = _render(scans[m.group("id")])
            new = SOLVE_FIELD.sub(solve, line, count=1)
            new = TEMPO_FIELD.sub("", new)
            new = new.replace(solve, solve + tempo, 1)
            if new != line:
                lines[i] = new
                touched += 1
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"  landed {path.name} ({len(rows)} rows)")
    print(f"  {touched} rows rewritten")
    return 0


def sheets_drifted() -> list[str]:
    """Rows whose sheet fields disagree with the classifier. The drift gate."""
    bad = []
    for character, path in rt.SHEETS.items():
        rows = rt.load_rows(path)
        scans, _ = rt.classify_pool(rows, character)
        for row in rows:
            scan = scans[row["id"]]
            want_band = {"fight": scan["fight"], "run": scan["run"]}
            if sorted(row.get("solve") or []) != scan["solve"]:
                bad.append(f"{character}/{row['id']}: solve "
                           f"{sorted(row.get('solve') or [])} != {scan['solve']}")
            if row.get("tempo_band") != want_band:
                bad.append(f"{character}/{row['id']}: tempo_band "
                           f"{row.get('tempo_band')} != {want_band}")
    return bad


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed files or the sheets are stale")
    ap.add_argument("--land", action="store_true",
                    help="write solve + tempo_band onto the three sheets")
    args = ap.parse_args(argv)
    if args.land:
        land()
    tsv, doc = build()
    if args.check:
        stale = [p.name for p, want in ((REVIEW, tsv), (TAGTHROUGH, doc))
                 if not p.exists()
                 or p.read_text(encoding="utf-8").replace("\r\n", "\n") != want]
        if stale:
            print("STALE: " + ", ".join(stale)
                  + "  -- rerun tools/suggest_role_tempo_tags.py")
            return 1
        drift = sheets_drifted()
        if drift:
            print("SHEET DRIFT: a landed tag no longer matches the classifier")
            for line in drift[:20]:
                print("    " + line)
            print("Re-run with --land, or change the rule that produced it.")
            return 1
        print("role/tempo artifacts current; three sheets match the classifier")
        return 0
    REVIEW.write_text(tsv, encoding="utf-8")
    TAGTHROUGH.write_text(doc, encoding="utf-8")
    n = tsv.count("\n") - 1
    diverge = sum(1 for line in tsv.splitlines()[1:]
                  if line.split("\t")[7] == "YES")
    print(f"  wrote {REVIEW.relative_to(REPO)} ({n} cards, "
          f"{diverge} diverging from the authored solve)")
    print(f"  wrote {TAGTHROUGH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
